// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: db494cf871a8

package operations

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/models/shared"
	"net/http"
)

// EncodingFormat - The format of the output embeddings
type EncodingFormat string

const (
	EncodingFormatFloat  EncodingFormat = "float"
	EncodingFormatBase64 EncodingFormat = "base64"
)

func (e EncodingFormat) ToPointer() *EncodingFormat {
	return &e
}
func (e *EncodingFormat) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "float":
		fallthrough
	case "base64":
		*e = EncodingFormat(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EncodingFormat: %v", v)
	}
}

type ImageURL struct {
	URL string `json:"url"`
}

func (i ImageURL) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *ImageURL) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *ImageURL) GetURL() string {
	if i == nil {
		return ""
	}
	return i.URL
}

type ContentImageURL struct {
	ImageURL ImageURL `json:"image_url"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_ string `const:"image_url" json:"type"`
}

func (c ContentImageURL) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ContentImageURL) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ContentImageURL) GetImageURL() ImageURL {
	if c == nil {
		return ImageURL{}
	}
	return c.ImageURL
}

func (c *ContentImageURL) GetType() string {
	return "image_url"
}

type ContentText struct {
	Text string `json:"text"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_ string `const:"text" json:"type"`
}

func (c ContentText) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ContentText) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ContentText) GetText() string {
	if c == nil {
		return ""
	}
	return c.Text
}

func (c *ContentText) GetType() string {
	return "text"
}

type ContentType string

const (
	ContentTypeText       ContentType = "text"
	ContentTypeImageURL   ContentType = "image_url"
	ContentTypeInputAudio ContentType = "input_audio"
	ContentTypeInputVideo ContentType = "input_video"
	ContentTypeInputFile  ContentType = "input_file"
)

type Content struct {
	ContentText           *ContentText                  `queryParam:"inline" union:"member"`
	ContentImageURL       *ContentImageURL              `queryParam:"inline" union:"member"`
	ContentPartInputAudio *shared.ContentPartInputAudio `queryParam:"inline" union:"member"`
	ContentPartInputVideo *shared.ContentPartInputVideo `queryParam:"inline" union:"member"`
	ContentPartInputFile  *shared.ContentPartInputFile  `queryParam:"inline" union:"member"`

	Type ContentType
}

func CreateContentText(text ContentText) Content {
	typ := ContentTypeText

	return Content{
		ContentText: &text,
		Type:        typ,
	}
}

func CreateContentImageURL(imageURL ContentImageURL) Content {
	typ := ContentTypeImageURL

	return Content{
		ContentImageURL: &imageURL,
		Type:            typ,
	}
}

func CreateContentInputAudio(inputAudio shared.ContentPartInputAudio) Content {
	typ := ContentTypeInputAudio

	return Content{
		ContentPartInputAudio: &inputAudio,
		Type:                  typ,
	}
}

func CreateContentInputVideo(inputVideo shared.ContentPartInputVideo) Content {
	typ := ContentTypeInputVideo

	return Content{
		ContentPartInputVideo: &inputVideo,
		Type:                  typ,
	}
}

func CreateContentInputFile(inputFile shared.ContentPartInputFile) Content {
	typ := ContentTypeInputFile

	return Content{
		ContentPartInputFile: &inputFile,
		Type:                 typ,
	}
}

func (u *Content) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Type string `json:"type"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.Type {
	case "text":
		contentText := new(ContentText)
		if err := utils.UnmarshalJSON(data, &contentText, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == text) type ContentText within Content: %w", string(data), err)
		}

		u.ContentText = contentText
		u.Type = ContentTypeText
		return nil
	case "image_url":
		contentImageURL := new(ContentImageURL)
		if err := utils.UnmarshalJSON(data, &contentImageURL, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == image_url) type ContentImageURL within Content: %w", string(data), err)
		}

		u.ContentImageURL = contentImageURL
		u.Type = ContentTypeImageURL
		return nil
	case "input_audio":
		contentPartInputAudio := new(shared.ContentPartInputAudio)
		if err := utils.UnmarshalJSON(data, &contentPartInputAudio, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == input_audio) type shared.ContentPartInputAudio within Content: %w", string(data), err)
		}

		u.ContentPartInputAudio = contentPartInputAudio
		u.Type = ContentTypeInputAudio
		return nil
	case "input_video":
		contentPartInputVideo := new(shared.ContentPartInputVideo)
		if err := utils.UnmarshalJSON(data, &contentPartInputVideo, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == input_video) type shared.ContentPartInputVideo within Content: %w", string(data), err)
		}

		u.ContentPartInputVideo = contentPartInputVideo
		u.Type = ContentTypeInputVideo
		return nil
	case "input_file":
		contentPartInputFile := new(shared.ContentPartInputFile)
		if err := utils.UnmarshalJSON(data, &contentPartInputFile, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == input_file) type shared.ContentPartInputFile within Content: %w", string(data), err)
		}

		u.ContentPartInputFile = contentPartInputFile
		u.Type = ContentTypeInputFile
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for Content", string(data))
}

func (u Content) MarshalJSON() ([]byte, error) {
	if u.ContentText != nil {
		return utils.MarshalJSON(u.ContentText, "", true)
	}

	if u.ContentImageURL != nil {
		return utils.MarshalJSON(u.ContentImageURL, "", true)
	}

	if u.ContentPartInputAudio != nil {
		return utils.MarshalJSON(u.ContentPartInputAudio, "", true)
	}

	if u.ContentPartInputVideo != nil {
		return utils.MarshalJSON(u.ContentPartInputVideo, "", true)
	}

	if u.ContentPartInputFile != nil {
		return utils.MarshalJSON(u.ContentPartInputFile, "", true)
	}

	return nil, errors.New("could not marshal union type Content: all fields are null")
}

type Input struct {
	Content []Content `json:"content"`
}

func (i Input) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *Input) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *Input) GetContent() []Content {
	if i == nil {
		return []Content{}
	}
	return i.Content
}

type InputUnionType string

const (
	InputUnionTypeStr                  InputUnionType = "str"
	InputUnionTypeArrayOfStr           InputUnionType = "arrayOfStr"
	InputUnionTypeArrayOfNumber        InputUnionType = "arrayOfNumber"
	InputUnionTypeArrayOfArrayOfNumber InputUnionType = "arrayOfArrayOfNumber"
	InputUnionTypeArrayOfInput         InputUnionType = "arrayOfInput"
)

// InputUnion - Text, token, or multimodal input(s) to embed
type InputUnion struct {
	Str                  *string     `queryParam:"inline" union:"member"`
	ArrayOfStr           []string    `queryParam:"inline" union:"member"`
	ArrayOfNumber        []float64   `queryParam:"inline" union:"member"`
	ArrayOfArrayOfNumber [][]float64 `queryParam:"inline" union:"member"`
	ArrayOfInput         []Input     `queryParam:"inline" union:"member"`

	Type InputUnionType
}

func CreateInputUnionStr(str string) InputUnion {
	typ := InputUnionTypeStr

	return InputUnion{
		Str:  &str,
		Type: typ,
	}
}

func CreateInputUnionArrayOfStr(arrayOfStr []string) InputUnion {
	typ := InputUnionTypeArrayOfStr

	return InputUnion{
		ArrayOfStr: arrayOfStr,
		Type:       typ,
	}
}

func CreateInputUnionArrayOfNumber(arrayOfNumber []float64) InputUnion {
	typ := InputUnionTypeArrayOfNumber

	return InputUnion{
		ArrayOfNumber: arrayOfNumber,
		Type:          typ,
	}
}

func CreateInputUnionArrayOfArrayOfNumber(arrayOfArrayOfNumber [][]float64) InputUnion {
	typ := InputUnionTypeArrayOfArrayOfNumber

	return InputUnion{
		ArrayOfArrayOfNumber: arrayOfArrayOfNumber,
		Type:                 typ,
	}
}

func CreateInputUnionArrayOfInput(arrayOfInput []Input) InputUnion {
	typ := InputUnionTypeArrayOfInput

	return InputUnion{
		ArrayOfInput: arrayOfInput,
		Type:         typ,
	}
}

func (u *InputUnion) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  InputUnionTypeStr,
			Value: &str,
		})
	}

	var arrayOfStr []string = []string{}
	if err := utils.UnmarshalJSON(data, &arrayOfStr, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  InputUnionTypeArrayOfStr,
			Value: arrayOfStr,
		})
	}

	var arrayOfNumber []float64 = []float64{}
	if err := utils.UnmarshalJSON(data, &arrayOfNumber, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  InputUnionTypeArrayOfNumber,
			Value: arrayOfNumber,
		})
	}

	var arrayOfArrayOfNumber [][]float64 = [][]float64{}
	if err := utils.UnmarshalJSON(data, &arrayOfArrayOfNumber, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  InputUnionTypeArrayOfArrayOfNumber,
			Value: arrayOfArrayOfNumber,
		})
	}

	var arrayOfInput []Input = []Input{}
	if err := utils.UnmarshalJSON(data, &arrayOfInput, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  InputUnionTypeArrayOfInput,
			Value: arrayOfInput,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for InputUnion", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for InputUnion", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(InputUnionType)
	switch best.Type {
	case InputUnionTypeStr:
		u.Str = best.Value.(*string)
		return nil
	case InputUnionTypeArrayOfStr:
		u.ArrayOfStr = best.Value.([]string)
		return nil
	case InputUnionTypeArrayOfNumber:
		u.ArrayOfNumber = best.Value.([]float64)
		return nil
	case InputUnionTypeArrayOfArrayOfNumber:
		u.ArrayOfArrayOfNumber = best.Value.([][]float64)
		return nil
	case InputUnionTypeArrayOfInput:
		u.ArrayOfInput = best.Value.([]Input)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for InputUnion", string(data))
}

func (u InputUnion) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.ArrayOfStr != nil {
		return utils.MarshalJSON(u.ArrayOfStr, "", true)
	}

	if u.ArrayOfNumber != nil {
		return utils.MarshalJSON(u.ArrayOfNumber, "", true)
	}

	if u.ArrayOfArrayOfNumber != nil {
		return utils.MarshalJSON(u.ArrayOfArrayOfNumber, "", true)
	}

	if u.ArrayOfInput != nil {
		return utils.MarshalJSON(u.ArrayOfInput, "", true)
	}

	return nil, errors.New("could not marshal union type InputUnion: all fields are null")
}

// CreateEmbeddingsRequest - Embeddings request input
type CreateEmbeddingsRequest struct {
	// The number of dimensions for the output embeddings
	Dimensions *int64 `json:"dimensions,omitzero"`
	// The format of the output embeddings
	EncodingFormat *EncodingFormat `json:"encoding_format,omitzero"`
	// Text, token, or multimodal input(s) to embed
	Input InputUnion `json:"input"`
	// The type of input (e.g. search_query, search_document)
	InputType *string `json:"input_type,omitzero"`
	// The model to use for embeddings
	Model    string                      `json:"model"`
	Provider *shared.ProviderPreferences `json:"provider,omitzero"`
	// A unique identifier for the end-user
	User *string `json:"user,omitzero"`
}

func (c CreateEmbeddingsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateEmbeddingsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateEmbeddingsRequest) GetDimensions() *int64 {
	if c == nil {
		return nil
	}
	return c.Dimensions
}

func (c *CreateEmbeddingsRequest) GetEncodingFormat() *EncodingFormat {
	if c == nil {
		return nil
	}
	return c.EncodingFormat
}

func (c *CreateEmbeddingsRequest) GetInput() InputUnion {
	if c == nil {
		return InputUnion{}
	}
	return c.Input
}

func (c *CreateEmbeddingsRequest) GetInputType() *string {
	if c == nil {
		return nil
	}
	return c.InputType
}

func (c *CreateEmbeddingsRequest) GetModel() string {
	if c == nil {
		return ""
	}
	return c.Model
}

func (c *CreateEmbeddingsRequest) GetProvider() *shared.ProviderPreferences {
	if c == nil {
		return nil
	}
	return c.Provider
}

func (c *CreateEmbeddingsRequest) GetUser() *string {
	if c == nil {
		return nil
	}
	return c.User
}

type EmbeddingType string

const (
	EmbeddingTypeArrayOfNumber EmbeddingType = "arrayOfNumber"
	EmbeddingTypeStr           EmbeddingType = "str"
)

// Embedding vector as an array of floats or a base64 string
type Embedding struct {
	ArrayOfNumber []float64 `queryParam:"inline" union:"member"`
	Str           *string   `queryParam:"inline" union:"member"`

	Type EmbeddingType
}

func CreateEmbeddingArrayOfNumber(arrayOfNumber []float64) Embedding {
	typ := EmbeddingTypeArrayOfNumber

	return Embedding{
		ArrayOfNumber: arrayOfNumber,
		Type:          typ,
	}
}

func CreateEmbeddingStr(str string) Embedding {
	typ := EmbeddingTypeStr

	return Embedding{
		Str:  &str,
		Type: typ,
	}
}

func (u *Embedding) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var arrayOfNumber []float64 = []float64{}
	if err := utils.UnmarshalJSON(data, &arrayOfNumber, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  EmbeddingTypeArrayOfNumber,
			Value: arrayOfNumber,
		})
	}

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  EmbeddingTypeStr,
			Value: &str,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for Embedding", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for Embedding", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(EmbeddingType)
	switch best.Type {
	case EmbeddingTypeArrayOfNumber:
		u.ArrayOfNumber = best.Value.([]float64)
		return nil
	case EmbeddingTypeStr:
		u.Str = best.Value.(*string)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for Embedding", string(data))
}

func (u Embedding) MarshalJSON() ([]byte, error) {
	if u.ArrayOfNumber != nil {
		return utils.MarshalJSON(u.ArrayOfNumber, "", true)
	}

	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	return nil, errors.New("could not marshal union type Embedding: all fields are null")
}

type ObjectEmbedding string

const (
	ObjectEmbeddingEmbedding ObjectEmbedding = "embedding"
)

func (e ObjectEmbedding) ToPointer() *ObjectEmbedding {
	return &e
}
func (e *ObjectEmbedding) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "embedding":
		*e = ObjectEmbedding(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ObjectEmbedding: %v", v)
	}
}

// CreateEmbeddingsData - A single embedding object
type CreateEmbeddingsData struct {
	// Embedding vector as an array of floats or a base64 string
	Embedding Embedding `json:"embedding"`
	// Index of the embedding in the input list
	Index  *int64          `json:"index,omitzero"`
	Object ObjectEmbedding `json:"object"`
}

func (c *CreateEmbeddingsData) GetEmbedding() Embedding {
	if c == nil {
		return Embedding{}
	}
	return c.Embedding
}

func (c *CreateEmbeddingsData) GetIndex() *int64 {
	if c == nil {
		return nil
	}
	return c.Index
}

func (c *CreateEmbeddingsData) GetObject() ObjectEmbedding {
	if c == nil {
		return ObjectEmbedding("")
	}
	return c.Object
}

type Object string

const (
	ObjectList Object = "list"
)

func (e Object) ToPointer() *Object {
	return &e
}
func (e *Object) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "list":
		*e = Object(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Object: %v", v)
	}
}

// PromptTokensDetails - Per-modality token breakdown. Only present when the input contains 2+ modalities (e.g. text + image) and the upstream provider returns modality-level usage data. Only non-zero modality counts are included.
type PromptTokensDetails struct {
	// Number of audio tokens in the input
	AudioTokens *int64 `json:"audio_tokens,omitzero"`
	// Number of file/document tokens in the input
	FileTokens *int64 `json:"file_tokens,omitzero"`
	// Number of image tokens in the input
	ImageTokens *int64 `json:"image_tokens,omitzero"`
	// Number of text tokens in the input
	TextTokens *int64 `json:"text_tokens,omitzero"`
	// Number of video tokens in the input
	VideoTokens *int64 `json:"video_tokens,omitzero"`
}

func (p *PromptTokensDetails) GetAudioTokens() *int64 {
	if p == nil {
		return nil
	}
	return p.AudioTokens
}

func (p *PromptTokensDetails) GetFileTokens() *int64 {
	if p == nil {
		return nil
	}
	return p.FileTokens
}

func (p *PromptTokensDetails) GetImageTokens() *int64 {
	if p == nil {
		return nil
	}
	return p.ImageTokens
}

func (p *PromptTokensDetails) GetTextTokens() *int64 {
	if p == nil {
		return nil
	}
	return p.TextTokens
}

func (p *PromptTokensDetails) GetVideoTokens() *int64 {
	if p == nil {
		return nil
	}
	return p.VideoTokens
}

// CreateEmbeddingsUsage - Token usage statistics
type CreateEmbeddingsUsage struct {
	// Cost of the request in credits
	Cost *float64 `json:"cost,omitzero"`
	// Breakdown of upstream inference costs
	CostDetails *shared.CostDetails `json:"cost_details,omitzero"`
	// Whether a request was made using a Bring Your Own Key configuration
	IsByok *bool `json:"is_byok,omitzero"`
	// Number of tokens in the input
	PromptTokens int64 `json:"prompt_tokens"`
	// Per-modality token breakdown. Only present when the input contains 2+ modalities (e.g. text + image) and the upstream provider returns modality-level usage data. Only non-zero modality counts are included.
	PromptTokensDetails *PromptTokensDetails `json:"prompt_tokens_details,omitzero"`
	// Total number of tokens used
	TotalTokens int64 `json:"total_tokens"`
}

func (c CreateEmbeddingsUsage) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateEmbeddingsUsage) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateEmbeddingsUsage) GetCost() *float64 {
	if c == nil {
		return nil
	}
	return c.Cost
}

func (c *CreateEmbeddingsUsage) GetCostDetails() *shared.CostDetails {
	if c == nil {
		return nil
	}
	return c.CostDetails
}

func (c *CreateEmbeddingsUsage) GetIsByok() *bool {
	if c == nil {
		return nil
	}
	return c.IsByok
}

func (c *CreateEmbeddingsUsage) GetPromptTokens() int64 {
	if c == nil {
		return 0
	}
	return c.PromptTokens
}

func (c *CreateEmbeddingsUsage) GetPromptTokensDetails() *PromptTokensDetails {
	if c == nil {
		return nil
	}
	return c.PromptTokensDetails
}

func (c *CreateEmbeddingsUsage) GetTotalTokens() int64 {
	if c == nil {
		return 0
	}
	return c.TotalTokens
}

// CreateEmbeddingsResponseBody - Embeddings response containing embedding vectors
type CreateEmbeddingsResponseBody struct {
	// List of embedding objects
	Data []CreateEmbeddingsData `json:"data"`
	// Unique identifier for the embeddings response
	ID *string `json:"id,omitzero"`
	// The model used for embeddings
	Model  string `json:"model"`
	Object Object `json:"object"`
	// Token usage statistics
	Usage *CreateEmbeddingsUsage `json:"usage,omitzero"`
}

func (c CreateEmbeddingsResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateEmbeddingsResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateEmbeddingsResponseBody) GetData() []CreateEmbeddingsData {
	if c == nil {
		return []CreateEmbeddingsData{}
	}
	return c.Data
}

func (c *CreateEmbeddingsResponseBody) GetID() *string {
	if c == nil {
		return nil
	}
	return c.ID
}

func (c *CreateEmbeddingsResponseBody) GetModel() string {
	if c == nil {
		return ""
	}
	return c.Model
}

func (c *CreateEmbeddingsResponseBody) GetObject() Object {
	if c == nil {
		return Object("")
	}
	return c.Object
}

func (c *CreateEmbeddingsResponseBody) GetUsage() *CreateEmbeddingsUsage {
	if c == nil {
		return nil
	}
	return c.Usage
}

type CreateEmbeddingsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Embedding response
	Object *CreateEmbeddingsResponseBody
	// Embedding response
	Res *string
	// Bad Request - Invalid request parameters or malformed input
	BadRequestResponse *shared.BadRequestResponse
	// Unauthorized - Authentication required or invalid credentials
	UnauthorizedResponse *shared.UnauthorizedResponse
	// Payment Required - Insufficient credits or quota to complete request
	PaymentRequiredResponse *shared.PaymentRequiredResponse
	// Not Found - Resource does not exist
	NotFoundResponse *shared.NotFoundResponse
	// Request Timeout - Operation exceeded time limit
	RequestTimeoutResponse *shared.RequestTimeoutResponse
	// Payload Too Large - Request payload exceeds size limits
	PayloadTooLargeResponse *shared.PayloadTooLargeResponse
	// Too Many Requests - Rate limit exceeded
	TooManyRequestsResponse *shared.TooManyRequestsResponse
	// Internal Server Error - Unexpected server error
	InternalServerResponse *shared.InternalServerResponse
	// Bad Gateway - Provider/upstream API failure
	BadGatewayResponse *shared.BadGatewayResponse
	// Service Unavailable - Service temporarily unavailable
	ServiceUnavailableResponse *shared.ServiceUnavailableResponse
	// Infrastructure Timeout - Provider request timed out at edge network
	EdgeNetworkTimeoutResponse *shared.EdgeNetworkTimeoutResponse
	// Provider Overloaded - Provider is temporarily overloaded
	ProviderOverloadedResponse *shared.ProviderOverloadedResponse
}

func (c CreateEmbeddingsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateEmbeddingsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateEmbeddingsResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateEmbeddingsResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateEmbeddingsResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateEmbeddingsResponse) GetObject() *CreateEmbeddingsResponseBody {
	if c == nil {
		return nil
	}
	return c.Object
}

func (c *CreateEmbeddingsResponse) GetRes() *string {
	if c == nil {
		return nil
	}
	return c.Res
}

func (c *CreateEmbeddingsResponse) GetBadRequestResponse() *shared.BadRequestResponse {
	if c == nil {
		return nil
	}
	return c.BadRequestResponse
}

func (c *CreateEmbeddingsResponse) GetUnauthorizedResponse() *shared.UnauthorizedResponse {
	if c == nil {
		return nil
	}
	return c.UnauthorizedResponse
}

func (c *CreateEmbeddingsResponse) GetPaymentRequiredResponse() *shared.PaymentRequiredResponse {
	if c == nil {
		return nil
	}
	return c.PaymentRequiredResponse
}

func (c *CreateEmbeddingsResponse) GetNotFoundResponse() *shared.NotFoundResponse {
	if c == nil {
		return nil
	}
	return c.NotFoundResponse
}

func (c *CreateEmbeddingsResponse) GetRequestTimeoutResponse() *shared.RequestTimeoutResponse {
	if c == nil {
		return nil
	}
	return c.RequestTimeoutResponse
}

func (c *CreateEmbeddingsResponse) GetPayloadTooLargeResponse() *shared.PayloadTooLargeResponse {
	if c == nil {
		return nil
	}
	return c.PayloadTooLargeResponse
}

func (c *CreateEmbeddingsResponse) GetTooManyRequestsResponse() *shared.TooManyRequestsResponse {
	if c == nil {
		return nil
	}
	return c.TooManyRequestsResponse
}

func (c *CreateEmbeddingsResponse) GetInternalServerResponse() *shared.InternalServerResponse {
	if c == nil {
		return nil
	}
	return c.InternalServerResponse
}

func (c *CreateEmbeddingsResponse) GetBadGatewayResponse() *shared.BadGatewayResponse {
	if c == nil {
		return nil
	}
	return c.BadGatewayResponse
}

func (c *CreateEmbeddingsResponse) GetServiceUnavailableResponse() *shared.ServiceUnavailableResponse {
	if c == nil {
		return nil
	}
	return c.ServiceUnavailableResponse
}

func (c *CreateEmbeddingsResponse) GetEdgeNetworkTimeoutResponse() *shared.EdgeNetworkTimeoutResponse {
	if c == nil {
		return nil
	}
	return c.EdgeNetworkTimeoutResponse
}

func (c *CreateEmbeddingsResponse) GetProviderOverloadedResponse() *shared.ProviderOverloadedResponse {
	if c == nil {
		return nil
	}
	return c.ProviderOverloadedResponse
}
