// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 5fc62c624a09

package operations

import (
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/models/shared"
	"net/http"
)

type CreateBYOKKeyResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// BYOK credential created successfully
	CreateBYOKKeyResponse *shared.CreateBYOKKeyResponse
	// Bad Request - Invalid request parameters or malformed input
	BadRequestResponse *shared.BadRequestResponse
	// Unauthorized - Authentication required or invalid credentials
	UnauthorizedResponse *shared.UnauthorizedResponse
	// Forbidden - Authentication successful but insufficient permissions
	ForbiddenResponse *shared.ForbiddenResponse
	// Internal Server Error - Unexpected server error
	InternalServerResponse *shared.InternalServerResponse
}

func (c CreateBYOKKeyResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateBYOKKeyResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateBYOKKeyResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateBYOKKeyResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateBYOKKeyResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateBYOKKeyResponse) GetCreateBYOKKeyResponse() *shared.CreateBYOKKeyResponse {
	if c == nil {
		return nil
	}
	return c.CreateBYOKKeyResponse
}

func (c *CreateBYOKKeyResponse) GetBadRequestResponse() *shared.BadRequestResponse {
	if c == nil {
		return nil
	}
	return c.BadRequestResponse
}

func (c *CreateBYOKKeyResponse) GetUnauthorizedResponse() *shared.UnauthorizedResponse {
	if c == nil {
		return nil
	}
	return c.UnauthorizedResponse
}

func (c *CreateBYOKKeyResponse) GetForbiddenResponse() *shared.ForbiddenResponse {
	if c == nil {
		return nil
	}
	return c.ForbiddenResponse
}

func (c *CreateBYOKKeyResponse) GetInternalServerResponse() *shared.InternalServerResponse {
	if c == nil {
		return nil
	}
	return c.InternalServerResponse
}
