// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 06b09af9d428

package operations

import (
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/models/shared"
	"net/http"
)

type DisablePrivateEndpointRequest struct {
	// Stable identifier of the private endpoint.
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (d *DisablePrivateEndpointRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

type DisablePrivateEndpointResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The endpoint after the change
	ManagedPrivateEndpointResponse *shared.ManagedPrivateEndpointResponse
	// Bad Request - Invalid request parameters or malformed input
	BadRequestResponse *shared.BadRequestResponse
	// Unauthorized - Authentication required or invalid credentials
	UnauthorizedResponse *shared.UnauthorizedResponse
	// Forbidden - Authentication successful but insufficient permissions
	ForbiddenResponse *shared.ForbiddenResponse
	// Not Found - Resource does not exist
	NotFoundResponse *shared.NotFoundResponse
	// Conflict - Resource conflict or concurrent modification
	ConflictResponse *shared.ConflictResponse
	// Unprocessable Entity - Semantic validation failure
	UnprocessableEntityResponse *shared.UnprocessableEntityResponse
	// Internal Server Error - Unexpected server error
	InternalServerResponse *shared.InternalServerResponse
	// Bad Gateway - Provider/upstream API failure
	BadGatewayResponse *shared.BadGatewayResponse
}

func (d DisablePrivateEndpointResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DisablePrivateEndpointResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DisablePrivateEndpointResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DisablePrivateEndpointResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DisablePrivateEndpointResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}

func (d *DisablePrivateEndpointResponse) GetManagedPrivateEndpointResponse() *shared.ManagedPrivateEndpointResponse {
	if d == nil {
		return nil
	}
	return d.ManagedPrivateEndpointResponse
}

func (d *DisablePrivateEndpointResponse) GetBadRequestResponse() *shared.BadRequestResponse {
	if d == nil {
		return nil
	}
	return d.BadRequestResponse
}

func (d *DisablePrivateEndpointResponse) GetUnauthorizedResponse() *shared.UnauthorizedResponse {
	if d == nil {
		return nil
	}
	return d.UnauthorizedResponse
}

func (d *DisablePrivateEndpointResponse) GetForbiddenResponse() *shared.ForbiddenResponse {
	if d == nil {
		return nil
	}
	return d.ForbiddenResponse
}

func (d *DisablePrivateEndpointResponse) GetNotFoundResponse() *shared.NotFoundResponse {
	if d == nil {
		return nil
	}
	return d.NotFoundResponse
}

func (d *DisablePrivateEndpointResponse) GetConflictResponse() *shared.ConflictResponse {
	if d == nil {
		return nil
	}
	return d.ConflictResponse
}

func (d *DisablePrivateEndpointResponse) GetUnprocessableEntityResponse() *shared.UnprocessableEntityResponse {
	if d == nil {
		return nil
	}
	return d.UnprocessableEntityResponse
}

func (d *DisablePrivateEndpointResponse) GetInternalServerResponse() *shared.InternalServerResponse {
	if d == nil {
		return nil
	}
	return d.InternalServerResponse
}

func (d *DisablePrivateEndpointResponse) GetBadGatewayResponse() *shared.BadGatewayResponse {
	if d == nil {
		return nil
	}
	return d.BadGatewayResponse
}
