// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/openrouter/terraform-provider-openrouter/internal/sdk/internal/utils"
	"github.com/openrouter/terraform-provider-openrouter/internal/sdk/models/shared"
	"net/http"
	"time"
)

type GetKeyRequest struct {
	// The hash identifier of the API key to retrieve
	Hash string `pathParam:"style=simple,explode=false,name=hash"`
}

func (g *GetKeyRequest) GetHash() string {
	if g == nil {
		return ""
	}
	return g.Hash
}

// GetKeyData - The API key information
type GetKeyData struct {
	// Total external BYOK usage (in USD) for the API key
	ByokUsage float64 `json:"byok_usage"`
	// External BYOK usage (in USD) for the current UTC day
	ByokUsageDaily float64 `json:"byok_usage_daily"`
	// External BYOK usage (in USD) for current UTC month
	ByokUsageMonthly float64 `json:"byok_usage_monthly"`
	// External BYOK usage (in USD) for the current UTC week (Monday-Sunday)
	ByokUsageWeekly float64 `json:"byok_usage_weekly"`
	// ISO 8601 timestamp of when the API key was created
	CreatedAt string `json:"created_at"`
	// The user ID of the key creator. For organization-owned keys, this is the member who created the key. For individual users, this is the user's own ID.
	CreatorUserID *string `json:"creator_user_id"`
	// Whether the API key is disabled
	Disabled bool `json:"disabled"`
	// ISO 8601 UTC timestamp when the API key expires, or null if no expiration
	ExpiresAt *time.Time `json:"expires_at,omitzero"`
	// Unique hash identifier for the API key
	Hash string `json:"hash"`
	// Whether to include external BYOK usage in the credit limit
	IncludeByokInLimit bool `json:"include_byok_in_limit"`
	// Human-readable label for the API key
	Label string `json:"label"`
	// Spending limit for the API key in USD
	Limit *float64 `json:"limit"`
	// Remaining spending limit in USD
	LimitRemaining *float64 `json:"limit_remaining"`
	// Type of limit reset for the API key
	LimitReset *string `json:"limit_reset"`
	// Name of the API key
	Name string `json:"name"`
	// ISO 8601 timestamp of when the API key was last updated
	UpdatedAt *string `json:"updated_at"`
	// Total OpenRouter credit usage (in USD) for the API key
	Usage float64 `json:"usage"`
	// OpenRouter credit usage (in USD) for the current UTC day
	UsageDaily float64 `json:"usage_daily"`
	// OpenRouter credit usage (in USD) for the current UTC month
	UsageMonthly float64 `json:"usage_monthly"`
	// OpenRouter credit usage (in USD) for the current UTC week (Monday-Sunday)
	UsageWeekly float64 `json:"usage_weekly"`
	// The workspace ID this API key belongs to.
	WorkspaceID string `json:"workspace_id"`
}

func (g GetKeyData) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetKeyData) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetKeyData) GetByokUsage() float64 {
	if g == nil {
		return 0.0
	}
	return g.ByokUsage
}

func (g *GetKeyData) GetByokUsageDaily() float64 {
	if g == nil {
		return 0.0
	}
	return g.ByokUsageDaily
}

func (g *GetKeyData) GetByokUsageMonthly() float64 {
	if g == nil {
		return 0.0
	}
	return g.ByokUsageMonthly
}

func (g *GetKeyData) GetByokUsageWeekly() float64 {
	if g == nil {
		return 0.0
	}
	return g.ByokUsageWeekly
}

func (g *GetKeyData) GetCreatedAt() string {
	if g == nil {
		return ""
	}
	return g.CreatedAt
}

func (g *GetKeyData) GetCreatorUserID() *string {
	if g == nil {
		return nil
	}
	return g.CreatorUserID
}

func (g *GetKeyData) GetDisabled() bool {
	if g == nil {
		return false
	}
	return g.Disabled
}

func (g *GetKeyData) GetExpiresAt() *time.Time {
	if g == nil {
		return nil
	}
	return g.ExpiresAt
}

func (g *GetKeyData) GetHash() string {
	if g == nil {
		return ""
	}
	return g.Hash
}

func (g *GetKeyData) GetIncludeByokInLimit() bool {
	if g == nil {
		return false
	}
	return g.IncludeByokInLimit
}

func (g *GetKeyData) GetLabel() string {
	if g == nil {
		return ""
	}
	return g.Label
}

func (g *GetKeyData) GetLimit() *float64 {
	if g == nil {
		return nil
	}
	return g.Limit
}

func (g *GetKeyData) GetLimitRemaining() *float64 {
	if g == nil {
		return nil
	}
	return g.LimitRemaining
}

func (g *GetKeyData) GetLimitReset() *string {
	if g == nil {
		return nil
	}
	return g.LimitReset
}

func (g *GetKeyData) GetName() string {
	if g == nil {
		return ""
	}
	return g.Name
}

func (g *GetKeyData) GetUpdatedAt() *string {
	if g == nil {
		return nil
	}
	return g.UpdatedAt
}

func (g *GetKeyData) GetUsage() float64 {
	if g == nil {
		return 0.0
	}
	return g.Usage
}

func (g *GetKeyData) GetUsageDaily() float64 {
	if g == nil {
		return 0.0
	}
	return g.UsageDaily
}

func (g *GetKeyData) GetUsageMonthly() float64 {
	if g == nil {
		return 0.0
	}
	return g.UsageMonthly
}

func (g *GetKeyData) GetUsageWeekly() float64 {
	if g == nil {
		return 0.0
	}
	return g.UsageWeekly
}

func (g *GetKeyData) GetWorkspaceID() string {
	if g == nil {
		return ""
	}
	return g.WorkspaceID
}

// GetKeyResponseBody - API key details
type GetKeyResponseBody struct {
	// The API key information
	Data GetKeyData `json:"data"`
}

func (g *GetKeyResponseBody) GetData() GetKeyData {
	if g == nil {
		return GetKeyData{}
	}
	return g.Data
}

type GetKeyResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// API key details
	Object *GetKeyResponseBody
	// Unauthorized - Authentication required or invalid credentials
	UnauthorizedResponse *shared.UnauthorizedResponse
	// Not Found - Resource does not exist
	NotFoundResponse *shared.NotFoundResponse
	// Too Many Requests - Rate limit exceeded
	TooManyRequestsResponse *shared.TooManyRequestsResponse
	// Internal Server Error - Unexpected server error
	InternalServerResponse *shared.InternalServerResponse
}

func (g GetKeyResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetKeyResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetKeyResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetKeyResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetKeyResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetKeyResponse) GetObject() *GetKeyResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}

func (g *GetKeyResponse) GetUnauthorizedResponse() *shared.UnauthorizedResponse {
	if g == nil {
		return nil
	}
	return g.UnauthorizedResponse
}

func (g *GetKeyResponse) GetNotFoundResponse() *shared.NotFoundResponse {
	if g == nil {
		return nil
	}
	return g.NotFoundResponse
}

func (g *GetKeyResponse) GetTooManyRequestsResponse() *shared.TooManyRequestsResponse {
	if g == nil {
		return nil
	}
	return g.TooManyRequestsResponse
}

func (g *GetKeyResponse) GetInternalServerResponse() *shared.InternalServerResponse {
	if g == nil {
		return nil
	}
	return g.InternalServerResponse
}
