// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/openrouter/terraform-provider-openrouter/internal/sdk/internal/utils"
	"github.com/openrouter/terraform-provider-openrouter/internal/sdk/models/shared"
	"net/http"
)

type GetPresetVersionRequest struct {
	// URL-safe slug identifying the preset.
	Slug string `pathParam:"style=simple,explode=false,name=slug"`
	// Version number of the preset.
	Version string `pathParam:"style=simple,explode=false,name=version"`
}

func (g *GetPresetVersionRequest) GetSlug() string {
	if g == nil {
		return ""
	}
	return g.Slug
}

func (g *GetPresetVersionRequest) GetVersion() string {
	if g == nil {
		return ""
	}
	return g.Version
}

type GetPresetVersionResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The requested preset version.
	GetPresetVersionResponse *shared.GetPresetVersionResponse
	// Bad Request - Invalid request parameters or malformed input
	BadRequestResponse *shared.BadRequestResponse
	// Unauthorized - Authentication required or invalid credentials
	UnauthorizedResponse *shared.UnauthorizedResponse
	// Not Found - Resource does not exist
	NotFoundResponse *shared.NotFoundResponse
	// Internal Server Error - Unexpected server error
	InternalServerResponse *shared.InternalServerResponse
}

func (g GetPresetVersionResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetPresetVersionResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetPresetVersionResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetPresetVersionResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetPresetVersionResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetPresetVersionResponse) GetGetPresetVersionResponse() *shared.GetPresetVersionResponse {
	if g == nil {
		return nil
	}
	return g.GetPresetVersionResponse
}

func (g *GetPresetVersionResponse) GetBadRequestResponse() *shared.BadRequestResponse {
	if g == nil {
		return nil
	}
	return g.BadRequestResponse
}

func (g *GetPresetVersionResponse) GetUnauthorizedResponse() *shared.UnauthorizedResponse {
	if g == nil {
		return nil
	}
	return g.UnauthorizedResponse
}

func (g *GetPresetVersionResponse) GetNotFoundResponse() *shared.NotFoundResponse {
	if g == nil {
		return nil
	}
	return g.NotFoundResponse
}

func (g *GetPresetVersionResponse) GetInternalServerResponse() *shared.InternalServerResponse {
	if g == nil {
		return nil
	}
	return g.InternalServerResponse
}
