// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/models/shared"
	"net/http"
)

type ListImageModelsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// List of image generation models
	ImageModelsListResponse *shared.ImageModelsListResponse
	// Internal Server Error - Unexpected server error
	InternalServerResponse *shared.InternalServerResponse
}

func (l ListImageModelsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListImageModelsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListImageModelsResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListImageModelsResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListImageModelsResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListImageModelsResponse) GetImageModelsListResponse() *shared.ImageModelsListResponse {
	if l == nil {
		return nil
	}
	return l.ImageModelsListResponse
}

func (l *ListImageModelsResponse) GetInternalServerResponse() *shared.InternalServerResponse {
	if l == nil {
		return nil
	}
	return l.InternalServerResponse
}
