// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/models/shared"
	"net/http"
)

type ListWorkspaceBudgetsRequest struct {
	// The workspace ID (UUID) or slug
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (l *ListWorkspaceBudgetsRequest) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

type ListWorkspaceBudgetsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Budgets retrieved successfully
	ListWorkspaceBudgetsResponse *shared.ListWorkspaceBudgetsResponse
	// Unauthorized - Authentication required or invalid credentials
	UnauthorizedResponse *shared.UnauthorizedResponse
	// Not Found - Resource does not exist
	NotFoundResponse *shared.NotFoundResponse
	// Internal Server Error - Unexpected server error
	InternalServerResponse *shared.InternalServerResponse
}

func (l ListWorkspaceBudgetsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListWorkspaceBudgetsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListWorkspaceBudgetsResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListWorkspaceBudgetsResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListWorkspaceBudgetsResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListWorkspaceBudgetsResponse) GetListWorkspaceBudgetsResponse() *shared.ListWorkspaceBudgetsResponse {
	if l == nil {
		return nil
	}
	return l.ListWorkspaceBudgetsResponse
}

func (l *ListWorkspaceBudgetsResponse) GetUnauthorizedResponse() *shared.UnauthorizedResponse {
	if l == nil {
		return nil
	}
	return l.UnauthorizedResponse
}

func (l *ListWorkspaceBudgetsResponse) GetNotFoundResponse() *shared.NotFoundResponse {
	if l == nil {
		return nil
	}
	return l.NotFoundResponse
}

func (l *ListWorkspaceBudgetsResponse) GetInternalServerResponse() *shared.InternalServerResponse {
	if l == nil {
		return nil
	}
	return l.InternalServerResponse
}
