// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: a0a08686de63

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/models/shared"
	"net/http"
)

// Order - Sort direction. Only `asc` is supported by OpenRouter storage.
type Order string

const (
	OrderAsc  Order = "asc"
	OrderDesc Order = "desc"
)

func (e Order) ToPointer() *Order {
	return &e
}
func (e *Order) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "asc":
		fallthrough
	case "desc":
		*e = Order(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Order: %v", v)
	}
}

type ListFilesRequest struct {
	// Maximum number of files to return (1–1000).
	Limit *int64 `queryParam:"style=form,explode=true,name=limit"`
	// Opaque pagination cursor from a previous response.
	Cursor *string `queryParam:"style=form,explode=true,name=cursor"`
	// Workspace to scope the request to. Defaults to the caller’s default workspace.
	WorkspaceID *string `queryParam:"style=form,explode=true,name=workspace_id"`
	// Store or read this file on the named provider using your own API key for it. Omit to use OpenRouter storage.
	Provider *shared.FileProvider `queryParam:"style=form,explode=true,name=provider"`
	// OpenAI-style forward cursor: the id to list after.
	After *string `queryParam:"style=form,explode=true,name=after"`
	// Anthropic-style forward cursor: the id to list after.
	AfterID *string `queryParam:"style=form,explode=true,name=after_id"`
	// Anthropic-style reverse cursor. Not supported by OpenRouter storage.
	BeforeID *string `queryParam:"style=form,explode=true,name=before_id"`
	// Sort direction. Only `asc` is supported by OpenRouter storage.
	Order *Order `queryParam:"style=form,explode=true,name=order"`
}

func (l *ListFilesRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListFilesRequest) GetCursor() *string {
	if l == nil {
		return nil
	}
	return l.Cursor
}

func (l *ListFilesRequest) GetWorkspaceID() *string {
	if l == nil {
		return nil
	}
	return l.WorkspaceID
}

func (l *ListFilesRequest) GetProvider() *shared.FileProvider {
	if l == nil {
		return nil
	}
	return l.Provider
}

func (l *ListFilesRequest) GetAfter() *string {
	if l == nil {
		return nil
	}
	return l.After
}

func (l *ListFilesRequest) GetAfterID() *string {
	if l == nil {
		return nil
	}
	return l.AfterID
}

func (l *ListFilesRequest) GetBeforeID() *string {
	if l == nil {
		return nil
	}
	return l.BeforeID
}

func (l *ListFilesRequest) GetOrder() *Order {
	if l == nil {
		return nil
	}
	return l.Order
}

type ListFilesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// A page of files.
	FileListResponse *shared.FileListResponse
	// Bad Request - Invalid request parameters or malformed input
	BadRequestResponse *shared.BadRequestResponse
	// Unauthorized - Authentication required or invalid credentials
	UnauthorizedResponse *shared.UnauthorizedResponse
	// Forbidden - Authentication successful but insufficient permissions
	ForbiddenResponse *shared.ForbiddenResponse
	// Too Many Requests - Rate limit exceeded
	TooManyRequestsResponse *shared.TooManyRequestsResponse
	// Internal Server Error - Unexpected server error
	InternalServerResponse *shared.InternalServerResponse
	// Bad Gateway - Provider/upstream API failure
	BadGatewayResponse *shared.BadGatewayResponse
	// Service Unavailable - Service temporarily unavailable
	ServiceUnavailableResponse *shared.ServiceUnavailableResponse

	Next func() (*ListFilesResponse, error)
}

func (l ListFilesResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListFilesResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListFilesResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListFilesResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListFilesResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListFilesResponse) GetFileListResponse() *shared.FileListResponse {
	if l == nil {
		return nil
	}
	return l.FileListResponse
}

func (l *ListFilesResponse) GetFileListResponseAnthropic() *shared.AnthropicFileList {
	if v := l.GetFileListResponse(); v != nil {
		return v.AnthropicFileList
	}
	return nil
}

func (l *ListFilesResponse) GetFileListResponseOpenai() *shared.OpenAIFileList {
	if v := l.GetFileListResponse(); v != nil {
		return v.OpenAIFileList
	}
	return nil
}

func (l *ListFilesResponse) GetFileListResponseOpenrouter() *shared.OpenRouterFileList {
	if v := l.GetFileListResponse(); v != nil {
		return v.OpenRouterFileList
	}
	return nil
}

func (l *ListFilesResponse) GetBadRequestResponse() *shared.BadRequestResponse {
	if l == nil {
		return nil
	}
	return l.BadRequestResponse
}

func (l *ListFilesResponse) GetUnauthorizedResponse() *shared.UnauthorizedResponse {
	if l == nil {
		return nil
	}
	return l.UnauthorizedResponse
}

func (l *ListFilesResponse) GetForbiddenResponse() *shared.ForbiddenResponse {
	if l == nil {
		return nil
	}
	return l.ForbiddenResponse
}

func (l *ListFilesResponse) GetTooManyRequestsResponse() *shared.TooManyRequestsResponse {
	if l == nil {
		return nil
	}
	return l.TooManyRequestsResponse
}

func (l *ListFilesResponse) GetInternalServerResponse() *shared.InternalServerResponse {
	if l == nil {
		return nil
	}
	return l.InternalServerResponse
}

func (l *ListFilesResponse) GetBadGatewayResponse() *shared.BadGatewayResponse {
	if l == nil {
		return nil
	}
	return l.BadGatewayResponse
}

func (l *ListFilesResponse) GetServiceUnavailableResponse() *shared.ServiceUnavailableResponse {
	if l == nil {
		return nil
	}
	return l.ServiceUnavailableResponse
}
