// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: a6e3d7c77c58

package operations

import (
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/models/shared"
	"net/http"
)

type ListInternVaultSecretsRequest struct {
	// UUID of an intern in the workspace selected by the API key.
	InternID string `pathParam:"style=simple,explode=false,name=internId"`
	// Page size, 1 to 100. Defaults to 100.
	Limit *int64 `default:"100" queryParam:"style=form,explode=true,name=limit"`
	// Number of secrets to skip, 0 to 10000. Defaults to 0.
	Offset *int64 `default:"0" queryParam:"style=form,explode=true,name=offset"`
}

func (l ListInternVaultSecretsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListInternVaultSecretsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListInternVaultSecretsRequest) GetInternID() string {
	if l == nil {
		return ""
	}
	return l.InternID
}

func (l *ListInternVaultSecretsRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListInternVaultSecretsRequest) GetOffset() *int64 {
	if l == nil {
		return nil
	}
	return l.Offset
}

type ListInternVaultSecretsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// One page of secret metadata.
	VaultSecretListResponse *shared.VaultSecretListResponse
	// Bad Request - The secret name, path, query or JSON body failed validation. The vault returns 400 for a malformed request as well.
	BadRequestResponse *shared.BadRequestResponse
	// Unauthorized - Missing or unknown API key. Provisioning keys cannot call vault routes.
	UnauthorizedResponse *shared.UnauthorizedResponse
	// Forbidden - The key has no usable workspace scope, or the request arrived on a regional hostname.
	ForbiddenResponse *shared.ForbiddenResponse
	// Not Found - The intern is not in the selected workspace, the secret does not exist in the selected scope, or the caller is outside the intern programme.
	NotFoundResponse *shared.NotFoundResponse
	// Request Timeout - The route deadline passed before the request completed, or the request body stopped arriving.
	RequestTimeoutResponse *shared.RequestTimeoutResponse
	// Too Many Requests - The vault rate limit was reached.
	TooManyRequestsResponse *shared.TooManyRequestsResponse
	// Internal Server Error - Scope lookup failed.
	InternalServerResponse *shared.InternalServerResponse
	// Bad Gateway - The vault could not be reached or returned an unexpected response.
	BadGatewayResponse *shared.BadGatewayResponse
	// Service Unavailable - Vault writes are disabled for the caller, or the vault is not configured.
	ServiceUnavailableResponse *shared.ServiceUnavailableResponse
	// Gateway Timeout - The vault did not answer in time.
	GatewayTimeoutResponse *shared.GatewayTimeoutResponse
}

func (l ListInternVaultSecretsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListInternVaultSecretsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListInternVaultSecretsResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListInternVaultSecretsResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListInternVaultSecretsResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListInternVaultSecretsResponse) GetVaultSecretListResponse() *shared.VaultSecretListResponse {
	if l == nil {
		return nil
	}
	return l.VaultSecretListResponse
}

func (l *ListInternVaultSecretsResponse) GetBadRequestResponse() *shared.BadRequestResponse {
	if l == nil {
		return nil
	}
	return l.BadRequestResponse
}

func (l *ListInternVaultSecretsResponse) GetUnauthorizedResponse() *shared.UnauthorizedResponse {
	if l == nil {
		return nil
	}
	return l.UnauthorizedResponse
}

func (l *ListInternVaultSecretsResponse) GetForbiddenResponse() *shared.ForbiddenResponse {
	if l == nil {
		return nil
	}
	return l.ForbiddenResponse
}

func (l *ListInternVaultSecretsResponse) GetNotFoundResponse() *shared.NotFoundResponse {
	if l == nil {
		return nil
	}
	return l.NotFoundResponse
}

func (l *ListInternVaultSecretsResponse) GetRequestTimeoutResponse() *shared.RequestTimeoutResponse {
	if l == nil {
		return nil
	}
	return l.RequestTimeoutResponse
}

func (l *ListInternVaultSecretsResponse) GetTooManyRequestsResponse() *shared.TooManyRequestsResponse {
	if l == nil {
		return nil
	}
	return l.TooManyRequestsResponse
}

func (l *ListInternVaultSecretsResponse) GetInternalServerResponse() *shared.InternalServerResponse {
	if l == nil {
		return nil
	}
	return l.InternalServerResponse
}

func (l *ListInternVaultSecretsResponse) GetBadGatewayResponse() *shared.BadGatewayResponse {
	if l == nil {
		return nil
	}
	return l.BadGatewayResponse
}

func (l *ListInternVaultSecretsResponse) GetServiceUnavailableResponse() *shared.ServiceUnavailableResponse {
	if l == nil {
		return nil
	}
	return l.ServiceUnavailableResponse
}

func (l *ListInternVaultSecretsResponse) GetGatewayTimeoutResponse() *shared.GatewayTimeoutResponse {
	if l == nil {
		return nil
	}
	return l.GatewayTimeoutResponse
}
