// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: b7da3df5652a

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/models/shared"
	"net/http"
)

type ListOrganizationMembersRequest struct {
	// Number of records to skip for pagination
	Offset *int64 `default:"0" queryParam:"style=form,explode=true,name=offset"`
	// Maximum number of records to return (max 100)
	Limit *int64 `default:"50" queryParam:"style=form,explode=true,name=limit"`
}

func (l ListOrganizationMembersRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListOrganizationMembersRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListOrganizationMembersRequest) GetOffset() *int64 {
	if l == nil {
		return nil
	}
	return l.Offset
}

func (l *ListOrganizationMembersRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

// Role of the member in the organization
type Role string

const (
	RoleOrgAdmin  Role = "org:admin"
	RoleOrgMember Role = "org:member"
)

func (e Role) ToPointer() *Role {
	return &e
}
func (e *Role) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "org:admin":
		fallthrough
	case "org:member":
		*e = Role(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Role: %v", v)
	}
}

type ListOrganizationMembersData struct {
	// Email address of the member
	Email string `json:"email"`
	// First name of the member
	FirstName *string `json:"first_name"`
	// User ID of the organization member
	ID string `json:"id"`
	// Last name of the member
	LastName *string `json:"last_name"`
	// Role of the member in the organization
	Role Role `json:"role"`
}

func (l *ListOrganizationMembersData) GetEmail() string {
	if l == nil {
		return ""
	}
	return l.Email
}

func (l *ListOrganizationMembersData) GetFirstName() *string {
	if l == nil {
		return nil
	}
	return l.FirstName
}

func (l *ListOrganizationMembersData) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

func (l *ListOrganizationMembersData) GetLastName() *string {
	if l == nil {
		return nil
	}
	return l.LastName
}

func (l *ListOrganizationMembersData) GetRole() Role {
	if l == nil {
		return Role("")
	}
	return l.Role
}

// ListOrganizationMembersResponseBody - List of organization members
type ListOrganizationMembersResponseBody struct {
	// List of organization members
	Data []ListOrganizationMembersData `json:"data"`
	// Total number of members in the organization
	TotalCount int64 `json:"total_count"`
}

func (l *ListOrganizationMembersResponseBody) GetData() []ListOrganizationMembersData {
	if l == nil {
		return []ListOrganizationMembersData{}
	}
	return l.Data
}

func (l *ListOrganizationMembersResponseBody) GetTotalCount() int64 {
	if l == nil {
		return 0
	}
	return l.TotalCount
}

type ListOrganizationMembersResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// List of organization members
	Object *ListOrganizationMembersResponseBody
	// Unauthorized - Authentication required or invalid credentials
	UnauthorizedResponse *shared.UnauthorizedResponse
	// Not Found - Resource does not exist
	NotFoundResponse *shared.NotFoundResponse
	// Internal Server Error - Unexpected server error
	InternalServerResponse *shared.InternalServerResponse

	Next func() (*ListOrganizationMembersResponse, error)
}

func (l ListOrganizationMembersResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListOrganizationMembersResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListOrganizationMembersResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListOrganizationMembersResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListOrganizationMembersResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListOrganizationMembersResponse) GetObject() *ListOrganizationMembersResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}

func (l *ListOrganizationMembersResponse) GetUnauthorizedResponse() *shared.UnauthorizedResponse {
	if l == nil {
		return nil
	}
	return l.UnauthorizedResponse
}

func (l *ListOrganizationMembersResponse) GetNotFoundResponse() *shared.NotFoundResponse {
	if l == nil {
		return nil
	}
	return l.NotFoundResponse
}

func (l *ListOrganizationMembersResponse) GetInternalServerResponse() *shared.InternalServerResponse {
	if l == nil {
		return nil
	}
	return l.InternalServerResponse
}
