// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/models/shared"
	"net/http"
	"time"
)

// ClassifierDimensions - Group results by custom classifier tags, breaking down metrics by the specified dimension values. Requires an active classifier on the workspace.
type ClassifierDimensions struct {
	// UUID of the classifier whose tags to group by.
	ClassifierID   string   `json:"classifier_id"`
	DimensionNames []string `json:"dimension_names,omitzero"`
	// When true, also include generations that have no tag from this classifier. Defaults to false, which returns only classified generations.
	IncludeNulls *bool `json:"include_nulls,omitzero"`
}

func (c ClassifierDimensions) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ClassifierDimensions) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ClassifierDimensions) GetClassifierID() string {
	if c == nil {
		return ""
	}
	return c.ClassifierID
}

func (c *ClassifierDimensions) GetDimensionNames() []string {
	if c == nil {
		return nil
	}
	return c.DimensionNames
}

func (c *ClassifierDimensions) GetIncludeNulls() *bool {
	if c == nil {
		return nil
	}
	return c.IncludeNulls
}

type ValueClassifierFiltersType string

const (
	ValueClassifierFiltersTypeStr    ValueClassifierFiltersType = "str"
	ValueClassifierFiltersTypeNumber ValueClassifierFiltersType = "number"
)

type ValueClassifierFilters struct {
	Str    *string  `queryParam:"inline" union:"member"`
	Number *float64 `queryParam:"inline" union:"member"`

	Type ValueClassifierFiltersType
}

func CreateValueClassifierFiltersStr(str string) ValueClassifierFilters {
	typ := ValueClassifierFiltersTypeStr

	return ValueClassifierFilters{
		Str:  &str,
		Type: typ,
	}
}

func CreateValueClassifierFiltersNumber(number float64) ValueClassifierFilters {
	typ := ValueClassifierFiltersTypeNumber

	return ValueClassifierFilters{
		Number: &number,
		Type:   typ,
	}
}

func (u *ValueClassifierFilters) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ValueClassifierFiltersTypeStr,
			Value: &str,
		})
	}

	var number float64 = float64(0)
	if err := utils.UnmarshalJSON(data, &number, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ValueClassifierFiltersTypeNumber,
			Value: &number,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for ValueClassifierFilters", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for ValueClassifierFilters", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(ValueClassifierFiltersType)
	switch best.Type {
	case ValueClassifierFiltersTypeStr:
		u.Str = best.Value.(*string)
		return nil
	case ValueClassifierFiltersTypeNumber:
		u.Number = best.Value.(*float64)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for ValueClassifierFilters", string(data))
}

func (u ValueClassifierFilters) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.Number != nil {
		return utils.MarshalJSON(u.Number, "", true)
	}

	return nil, errors.New("could not marshal union type ValueClassifierFilters: all fields are null")
}

type ClassifierFiltersValueType string

const (
	ClassifierFiltersValueTypeStr                           ClassifierFiltersValueType = "str"
	ClassifierFiltersValueTypeNumber                        ClassifierFiltersValueType = "number"
	ClassifierFiltersValueTypeArrayOfValueClassifierFilters ClassifierFiltersValueType = "arrayOfValueClassifierFilters"
)

// ClassifierFiltersValue - Filter value. Use a scalar (string or number) for eq/neq, or an array for in/not_in.
type ClassifierFiltersValue struct {
	Str                           *string                  `queryParam:"inline" union:"member"`
	Number                        *float64                 `queryParam:"inline" union:"member"`
	ArrayOfValueClassifierFilters []ValueClassifierFilters `queryParam:"inline" union:"member"`

	Type ClassifierFiltersValueType
}

func CreateClassifierFiltersValueStr(str string) ClassifierFiltersValue {
	typ := ClassifierFiltersValueTypeStr

	return ClassifierFiltersValue{
		Str:  &str,
		Type: typ,
	}
}

func CreateClassifierFiltersValueNumber(number float64) ClassifierFiltersValue {
	typ := ClassifierFiltersValueTypeNumber

	return ClassifierFiltersValue{
		Number: &number,
		Type:   typ,
	}
}

func CreateClassifierFiltersValueArrayOfValueClassifierFilters(arrayOfValueClassifierFilters []ValueClassifierFilters) ClassifierFiltersValue {
	typ := ClassifierFiltersValueTypeArrayOfValueClassifierFilters

	return ClassifierFiltersValue{
		ArrayOfValueClassifierFilters: arrayOfValueClassifierFilters,
		Type:                          typ,
	}
}

func (u *ClassifierFiltersValue) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ClassifierFiltersValueTypeStr,
			Value: &str,
		})
	}

	var number float64 = float64(0)
	if err := utils.UnmarshalJSON(data, &number, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ClassifierFiltersValueTypeNumber,
			Value: &number,
		})
	}

	var arrayOfValueClassifierFilters []ValueClassifierFilters = []ValueClassifierFilters{}
	if err := utils.UnmarshalJSON(data, &arrayOfValueClassifierFilters, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ClassifierFiltersValueTypeArrayOfValueClassifierFilters,
			Value: arrayOfValueClassifierFilters,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for ClassifierFiltersValue", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for ClassifierFiltersValue", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(ClassifierFiltersValueType)
	switch best.Type {
	case ClassifierFiltersValueTypeStr:
		u.Str = best.Value.(*string)
		return nil
	case ClassifierFiltersValueTypeNumber:
		u.Number = best.Value.(*float64)
		return nil
	case ClassifierFiltersValueTypeArrayOfValueClassifierFilters:
		u.ArrayOfValueClassifierFilters = best.Value.([]ValueClassifierFilters)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for ClassifierFiltersValue", string(data))
}

func (u ClassifierFiltersValue) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.Number != nil {
		return utils.MarshalJSON(u.Number, "", true)
	}

	if u.ArrayOfValueClassifierFilters != nil {
		return utils.MarshalJSON(u.ArrayOfValueClassifierFilters, "", true)
	}

	return nil, errors.New("could not marshal union type ClassifierFiltersValue: all fields are null")
}

type ClassifierFiltersFilter struct {
	// Classifier dimension name to filter on (snake_case identifier, e.g. "department", "work_type").
	Field string `json:"field"`
	// Filter operator. Only equality/set operators are supported (eq, neq, in, not_in) — ordered comparisons are not available because classification values are strings.
	Operator string `json:"operator"`
	// Filter value. Use a scalar (string or number) for eq/neq, or an array for in/not_in.
	Value ClassifierFiltersValue `json:"value"`
}

func (c *ClassifierFiltersFilter) GetField() string {
	if c == nil {
		return ""
	}
	return c.Field
}

func (c *ClassifierFiltersFilter) GetOperator() string {
	if c == nil {
		return ""
	}
	return c.Operator
}

func (c *ClassifierFiltersFilter) GetValue() ClassifierFiltersValue {
	if c == nil {
		return ClassifierFiltersValue{}
	}
	return c.Value
}

// ClassifierFilters - Filter results to generations with specific classifier tag values. Can be combined with classifier_dimensions (must use the same classifier_id) or used independently with standard dimensions.
type ClassifierFilters struct {
	// UUID of the classifier whose tags to filter by. Must match classifier_dimensions.classifier_id when both are specified.
	ClassifierID string                    `json:"classifier_id"`
	Filters      []ClassifierFiltersFilter `json:"filters"`
}

func (c *ClassifierFilters) GetClassifierID() string {
	if c == nil {
		return ""
	}
	return c.ClassifierID
}

func (c *ClassifierFilters) GetFilters() []ClassifierFiltersFilter {
	if c == nil {
		return []ClassifierFiltersFilter{}
	}
	return c.Filters
}

type Value2Type string

const (
	Value2TypeStr    Value2Type = "str"
	Value2TypeNumber Value2Type = "number"
)

type Value2 struct {
	Str    *string  `queryParam:"inline" union:"member"`
	Number *float64 `queryParam:"inline" union:"member"`

	Type Value2Type
}

func CreateValue2Str(str string) Value2 {
	typ := Value2TypeStr

	return Value2{
		Str:  &str,
		Type: typ,
	}
}

func CreateValue2Number(number float64) Value2 {
	typ := Value2TypeNumber

	return Value2{
		Number: &number,
		Type:   typ,
	}
}

func (u *Value2) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  Value2TypeStr,
			Value: &str,
		})
	}

	var number float64 = float64(0)
	if err := utils.UnmarshalJSON(data, &number, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  Value2TypeNumber,
			Value: &number,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for Value2", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for Value2", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(Value2Type)
	switch best.Type {
	case Value2TypeStr:
		u.Str = best.Value.(*string)
		return nil
	case Value2TypeNumber:
		u.Number = best.Value.(*float64)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for Value2", string(data))
}

func (u Value2) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.Number != nil {
		return utils.MarshalJSON(u.Number, "", true)
	}

	return nil, errors.New("could not marshal union type Value2: all fields are null")
}

type Value1Type string

const (
	Value1TypeStr           Value1Type = "str"
	Value1TypeNumber        Value1Type = "number"
	Value1TypeArrayOfValue2 Value1Type = "arrayOfValue2"
)

// Value1 - Filter value (scalar or array depending on operator). Several dimensions are enriched in responses (returned as human-readable labels), but filters must use the underlying ID: `api_key_id` — numeric ID (from generation metadata) or key hash (64-char hex from GET /api/v1/keys, resolved server-side); `user` — Clerk user ID (e.g. "user_abc123"), not the display name; `workspace` — workspace UUID, not the workspace name (filtering or grouping by the account default workspace also covers activity recorded before workspace resolution existed, which is attributed to that default workspace); `app` — numeric app ID, not the app title; `model` — permaslug (e.g. "openai/gpt-4o"), not the display name. Other dimensions (provider, origin, country, etc.) are not enriched and accept the value as returned.
type Value1 struct {
	Str           *string  `queryParam:"inline" union:"member"`
	Number        *float64 `queryParam:"inline" union:"member"`
	ArrayOfValue2 []Value2 `queryParam:"inline" union:"member"`

	Type Value1Type
}

func CreateValue1Str(str string) Value1 {
	typ := Value1TypeStr

	return Value1{
		Str:  &str,
		Type: typ,
	}
}

func CreateValue1Number(number float64) Value1 {
	typ := Value1TypeNumber

	return Value1{
		Number: &number,
		Type:   typ,
	}
}

func CreateValue1ArrayOfValue2(arrayOfValue2 []Value2) Value1 {
	typ := Value1TypeArrayOfValue2

	return Value1{
		ArrayOfValue2: arrayOfValue2,
		Type:          typ,
	}
}

func (u *Value1) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  Value1TypeStr,
			Value: &str,
		})
	}

	var number float64 = float64(0)
	if err := utils.UnmarshalJSON(data, &number, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  Value1TypeNumber,
			Value: &number,
		})
	}

	var arrayOfValue2 []Value2 = []Value2{}
	if err := utils.UnmarshalJSON(data, &arrayOfValue2, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  Value1TypeArrayOfValue2,
			Value: arrayOfValue2,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for Value1", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for Value1", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(Value1Type)
	switch best.Type {
	case Value1TypeStr:
		u.Str = best.Value.(*string)
		return nil
	case Value1TypeNumber:
		u.Number = best.Value.(*float64)
		return nil
	case Value1TypeArrayOfValue2:
		u.ArrayOfValue2 = best.Value.([]Value2)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for Value1", string(data))
}

func (u Value1) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.Number != nil {
		return utils.MarshalJSON(u.Number, "", true)
	}

	if u.ArrayOfValue2 != nil {
		return utils.MarshalJSON(u.ArrayOfValue2, "", true)
	}

	return nil, errors.New("could not marshal union type Value1: all fields are null")
}

type Filter struct {
	// Dimension to filter on. Use the /meta endpoint for available dimensions.
	Field string `json:"field"`
	// Filter operator
	Operator string `json:"operator"`
	// Filter value (scalar or array depending on operator). Several dimensions are enriched in responses (returned as human-readable labels), but filters must use the underlying ID: `api_key_id` — numeric ID (from generation metadata) or key hash (64-char hex from GET /api/v1/keys, resolved server-side); `user` — Clerk user ID (e.g. "user_abc123"), not the display name; `workspace` — workspace UUID, not the workspace name (filtering or grouping by the account default workspace also covers activity recorded before workspace resolution existed, which is attributed to that default workspace); `app` — numeric app ID, not the app title; `model` — permaslug (e.g. "openai/gpt-4o"), not the display name. Other dimensions (provider, origin, country, etc.) are not enriched and accept the value as returned.
	Value Value1 `json:"value"`
}

func (f *Filter) GetField() string {
	if f == nil {
		return ""
	}
	return f.Field
}

func (f *Filter) GetOperator() string {
	if f == nil {
		return ""
	}
	return f.Operator
}

func (f *Filter) GetValue() Value1 {
	if f == nil {
		return Value1{}
	}
	return f.Value
}

type Direction string

const (
	DirectionAsc  Direction = "asc"
	DirectionDesc Direction = "desc"
)

func (e Direction) ToPointer() *Direction {
	return &e
}
func (e *Direction) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "asc":
		fallthrough
	case "desc":
		*e = Direction(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Direction: %v", v)
	}
}

type OrderBy struct {
	Direction Direction `json:"direction"`
	// Field to order by: a metric included in `metrics` (or "request_count", which may be ordered by without being requested), a requested dimension, or "date".
	Field string `json:"field"`
}

func (o *OrderBy) GetDirection() Direction {
	if o == nil {
		return Direction("")
	}
	return o.Direction
}

func (o *OrderBy) GetField() string {
	if o == nil {
		return ""
	}
	return o.Field
}

type TimeRange struct {
	End   time.Time `json:"end"`
	Start time.Time `json:"start"`
}

func (t TimeRange) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TimeRange) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TimeRange) GetEnd() time.Time {
	if t == nil {
		return time.Time{}
	}
	return t.End
}

func (t *TimeRange) GetStart() time.Time {
	if t == nil {
		return time.Time{}
	}
	return t.Start
}

type QueryAnalyticsRequest struct {
	// Group results by custom classifier tags, breaking down metrics by the specified dimension values. Requires an active classifier on the workspace.
	ClassifierDimensions *ClassifierDimensions `json:"classifier_dimensions,omitzero"`
	// Filter results to generations with specific classifier tag values. Can be combined with classifier_dimensions (must use the same classifier_id) or used independently with standard dimensions.
	ClassifierFilters *ClassifierFilters `json:"classifier_filters,omitzero"`
	Dimensions        []string           `json:"dimensions,omitzero"`
	Filters           []Filter           `json:"filters,omitzero"`
	// Time granularity
	Granularity *string `json:"granularity,omitzero"`
	// Maximum rows per distinct combination of dimensions. When omitted on time-series queries (granularity + dimensions), auto-computed to avoid truncating time windows. Explicit values override the default and may truncate time buckets if set lower than the number of buckets in the range. Ignored when no dimensions are specified.
	GroupLimit *int64 `json:"group_limit,omitzero"`
	// Maximum total rows returned. Defaults to 1000. On time-series queries with dimensions and no explicit group_limit, the server may raise this to accommodate the expected number of unique time-bucket/dimension combinations.
	Limit     *int64     `json:"limit,omitzero"`
	Metrics   []string   `json:"metrics"`
	OrderBy   *OrderBy   `json:"order_by,omitzero"`
	TimeRange *TimeRange `json:"time_range,omitzero"`
}

func (q QueryAnalyticsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *QueryAnalyticsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (q *QueryAnalyticsRequest) GetClassifierDimensions() *ClassifierDimensions {
	if q == nil {
		return nil
	}
	return q.ClassifierDimensions
}

func (q *QueryAnalyticsRequest) GetClassifierFilters() *ClassifierFilters {
	if q == nil {
		return nil
	}
	return q.ClassifierFilters
}

func (q *QueryAnalyticsRequest) GetDimensions() []string {
	if q == nil {
		return nil
	}
	return q.Dimensions
}

func (q *QueryAnalyticsRequest) GetFilters() []Filter {
	if q == nil {
		return nil
	}
	return q.Filters
}

func (q *QueryAnalyticsRequest) GetGranularity() *string {
	if q == nil {
		return nil
	}
	return q.Granularity
}

func (q *QueryAnalyticsRequest) GetGroupLimit() *int64 {
	if q == nil {
		return nil
	}
	return q.GroupLimit
}

func (q *QueryAnalyticsRequest) GetLimit() *int64 {
	if q == nil {
		return nil
	}
	return q.Limit
}

func (q *QueryAnalyticsRequest) GetMetrics() []string {
	if q == nil {
		return []string{}
	}
	return q.Metrics
}

func (q *QueryAnalyticsRequest) GetOrderBy() *OrderBy {
	if q == nil {
		return nil
	}
	return q.OrderBy
}

func (q *QueryAnalyticsRequest) GetTimeRange() *TimeRange {
	if q == nil {
		return nil
	}
	return q.TimeRange
}

// QueryAnalyticsData1 - A row of analytics data with metric/dimension values
type QueryAnalyticsData1 struct {
}

// #region class-body-queryanalyticsdata1
// #endregion class-body-queryanalyticsdata1

type Metadata struct {
	QueryTimeMs float64 `json:"query_time_ms"`
	RowCount    int64   `json:"row_count"`
	Truncated   bool    `json:"truncated"`
}

func (m *Metadata) GetQueryTimeMs() float64 {
	if m == nil {
		return 0.0
	}
	return m.QueryTimeMs
}

func (m *Metadata) GetRowCount() int64 {
	if m == nil {
		return 0
	}
	return m.RowCount
}

func (m *Metadata) GetTruncated() bool {
	if m == nil {
		return false
	}
	return m.Truncated
}

type QueryAnalyticsData2 struct {
	CachedAt *float64              `json:"cachedAt,omitzero"`
	Data     []QueryAnalyticsData1 `json:"data"`
	Metadata Metadata              `json:"metadata"`
	// Warnings about filter resolution issues (e.g. unresolvable api_key_id hashes). The query still runs normally; these inform the caller that some filter values could not be resolved.
	Warnings []string `json:"warnings,omitzero"`
}

func (q QueryAnalyticsData2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *QueryAnalyticsData2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (q *QueryAnalyticsData2) GetCachedAt() *float64 {
	if q == nil {
		return nil
	}
	return q.CachedAt
}

func (q *QueryAnalyticsData2) GetData() []QueryAnalyticsData1 {
	if q == nil {
		return []QueryAnalyticsData1{}
	}
	return q.Data
}

func (q *QueryAnalyticsData2) GetMetadata() Metadata {
	if q == nil {
		return Metadata{}
	}
	return q.Metadata
}

func (q *QueryAnalyticsData2) GetWarnings() []string {
	if q == nil {
		return nil
	}
	return q.Warnings
}

// #region class-body-queryanalyticsdata2
// #endregion class-body-queryanalyticsdata2

// QueryAnalyticsResponseBody - Analytics query results
type QueryAnalyticsResponseBody struct {
	Data QueryAnalyticsData2 `json:"data"`
}

func (q *QueryAnalyticsResponseBody) GetData() QueryAnalyticsData2 {
	if q == nil {
		return QueryAnalyticsData2{}
	}
	return q.Data
}

type QueryAnalyticsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Analytics query results
	Object *QueryAnalyticsResponseBody
	// Bad Request - Invalid request parameters or malformed input
	BadRequestResponse *shared.BadRequestResponse
	// Unauthorized - Authentication required or invalid credentials
	UnauthorizedResponse *shared.UnauthorizedResponse
	// Forbidden - Authentication successful but insufficient permissions
	ForbiddenResponse *shared.ForbiddenResponse
	// Request Timeout - Operation exceeded time limit
	RequestTimeoutResponse *shared.RequestTimeoutResponse
	// Internal Server Error - Unexpected server error
	InternalServerResponse *shared.InternalServerResponse
}

func (q QueryAnalyticsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *QueryAnalyticsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (q *QueryAnalyticsResponse) GetContentType() string {
	if q == nil {
		return ""
	}
	return q.ContentType
}

func (q *QueryAnalyticsResponse) GetStatusCode() int {
	if q == nil {
		return 0
	}
	return q.StatusCode
}

func (q *QueryAnalyticsResponse) GetRawResponse() *http.Response {
	if q == nil {
		return nil
	}
	return q.RawResponse
}

func (q *QueryAnalyticsResponse) GetObject() *QueryAnalyticsResponseBody {
	if q == nil {
		return nil
	}
	return q.Object
}

func (q *QueryAnalyticsResponse) GetBadRequestResponse() *shared.BadRequestResponse {
	if q == nil {
		return nil
	}
	return q.BadRequestResponse
}

func (q *QueryAnalyticsResponse) GetUnauthorizedResponse() *shared.UnauthorizedResponse {
	if q == nil {
		return nil
	}
	return q.UnauthorizedResponse
}

func (q *QueryAnalyticsResponse) GetForbiddenResponse() *shared.ForbiddenResponse {
	if q == nil {
		return nil
	}
	return q.ForbiddenResponse
}

func (q *QueryAnalyticsResponse) GetRequestTimeoutResponse() *shared.RequestTimeoutResponse {
	if q == nil {
		return nil
	}
	return q.RequestTimeoutResponse
}

func (q *QueryAnalyticsResponse) GetInternalServerResponse() *shared.InternalServerResponse {
	if q == nil {
		return nil
	}
	return q.InternalServerResponse
}
