// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: c967413fefe5

package operations

import (
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/models/shared"
	"net/http"
)

type SubmitGenerationFeedbackResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Feedback recorded successfully
	SubmitGenerationFeedbackResponse *shared.SubmitGenerationFeedbackResponse
	// Bad Request - Invalid request parameters or malformed input
	BadRequestResponse *shared.BadRequestResponse
	// Unauthorized - Authentication required or invalid credentials
	UnauthorizedResponse *shared.UnauthorizedResponse
	// Not Found - Resource does not exist
	NotFoundResponse *shared.NotFoundResponse
	// Too Many Requests - Rate limit exceeded
	TooManyRequestsResponse *shared.TooManyRequestsResponse
	// Internal Server Error - Unexpected server error
	InternalServerResponse *shared.InternalServerResponse
}

func (s SubmitGenerationFeedbackResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SubmitGenerationFeedbackResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SubmitGenerationFeedbackResponse) GetContentType() string {
	if s == nil {
		return ""
	}
	return s.ContentType
}

func (s *SubmitGenerationFeedbackResponse) GetStatusCode() int {
	if s == nil {
		return 0
	}
	return s.StatusCode
}

func (s *SubmitGenerationFeedbackResponse) GetRawResponse() *http.Response {
	if s == nil {
		return nil
	}
	return s.RawResponse
}

func (s *SubmitGenerationFeedbackResponse) GetSubmitGenerationFeedbackResponse() *shared.SubmitGenerationFeedbackResponse {
	if s == nil {
		return nil
	}
	return s.SubmitGenerationFeedbackResponse
}

func (s *SubmitGenerationFeedbackResponse) GetBadRequestResponse() *shared.BadRequestResponse {
	if s == nil {
		return nil
	}
	return s.BadRequestResponse
}

func (s *SubmitGenerationFeedbackResponse) GetUnauthorizedResponse() *shared.UnauthorizedResponse {
	if s == nil {
		return nil
	}
	return s.UnauthorizedResponse
}

func (s *SubmitGenerationFeedbackResponse) GetNotFoundResponse() *shared.NotFoundResponse {
	if s == nil {
		return nil
	}
	return s.NotFoundResponse
}

func (s *SubmitGenerationFeedbackResponse) GetTooManyRequestsResponse() *shared.TooManyRequestsResponse {
	if s == nil {
		return nil
	}
	return s.TooManyRequestsResponse
}

func (s *SubmitGenerationFeedbackResponse) GetInternalServerResponse() *shared.InternalServerResponse {
	if s == nil {
		return nil
	}
	return s.InternalServerResponse
}
