// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/models/shared"
	"net/http"
	"time"
)

// UpdateKeysLimitReset - New limit reset type for the API key (daily, weekly, monthly, or null for no reset). Resets happen automatically at midnight UTC, and weeks are Monday through Sunday.
type UpdateKeysLimitReset string

const (
	UpdateKeysLimitResetDaily   UpdateKeysLimitReset = "daily"
	UpdateKeysLimitResetWeekly  UpdateKeysLimitReset = "weekly"
	UpdateKeysLimitResetMonthly UpdateKeysLimitReset = "monthly"
)

func (e UpdateKeysLimitReset) ToPointer() *UpdateKeysLimitReset {
	return &e
}
func (e *UpdateKeysLimitReset) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "daily":
		fallthrough
	case "weekly":
		fallthrough
	case "monthly":
		*e = UpdateKeysLimitReset(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UpdateKeysLimitReset: %v", v)
	}
}

type UpdateKeysRequestBody struct {
	// Whether to disable the API key
	Disabled *bool `json:"disabled,omitzero"`
	// Whether to include BYOK usage in the limit
	IncludeByokInLimit *bool `json:"include_byok_in_limit,omitzero"`
	// New spending limit for the API key in USD
	Limit *float64 `json:"limit,omitzero"`
	// New limit reset type for the API key (daily, weekly, monthly, or null for no reset). Resets happen automatically at midnight UTC, and weeks are Monday through Sunday.
	LimitReset *UpdateKeysLimitReset `json:"limit_reset,omitzero"`
	// New name for the API key
	Name *string `json:"name,omitzero"`
}

func (u *UpdateKeysRequestBody) GetDisabled() *bool {
	if u == nil {
		return nil
	}
	return u.Disabled
}

func (u *UpdateKeysRequestBody) GetIncludeByokInLimit() *bool {
	if u == nil {
		return nil
	}
	return u.IncludeByokInLimit
}

func (u *UpdateKeysRequestBody) GetLimit() *float64 {
	if u == nil {
		return nil
	}
	return u.Limit
}

func (u *UpdateKeysRequestBody) GetLimitReset() *UpdateKeysLimitReset {
	if u == nil {
		return nil
	}
	return u.LimitReset
}

func (u *UpdateKeysRequestBody) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

type UpdateKeysRequest struct {
	// The hash identifier of the API key to update
	Hash string                `pathParam:"style=simple,explode=false,name=hash"`
	Body UpdateKeysRequestBody `request:"mediaType=application/json"`
}

func (u *UpdateKeysRequest) GetHash() string {
	if u == nil {
		return ""
	}
	return u.Hash
}

func (u *UpdateKeysRequest) GetBody() UpdateKeysRequestBody {
	if u == nil {
		return UpdateKeysRequestBody{}
	}
	return u.Body
}

// UpdateKeysData - The updated API key information
type UpdateKeysData struct {
	// Total external BYOK usage (in USD) for the API key
	ByokUsage float64 `json:"byok_usage"`
	// External BYOK usage (in USD) for the current UTC day
	ByokUsageDaily float64 `json:"byok_usage_daily"`
	// External BYOK usage (in USD) for current UTC month
	ByokUsageMonthly float64 `json:"byok_usage_monthly"`
	// External BYOK usage (in USD) for the current UTC week (Monday-Sunday)
	ByokUsageWeekly float64 `json:"byok_usage_weekly"`
	// ISO 8601 timestamp of when the API key was created
	CreatedAt string `json:"created_at"`
	// The user ID of the key creator. For organization-owned keys, this is the member who created the key. For individual users, this is the user's own ID.
	CreatorUserID *string `json:"creator_user_id"`
	// Whether the API key is disabled
	Disabled bool `json:"disabled"`
	// ISO 8601 UTC timestamp when the API key expires, or null if no expiration
	ExpiresAt *time.Time `json:"expires_at,omitzero"`
	// Unique hash identifier for the API key
	Hash string `json:"hash"`
	// Whether to include external BYOK usage in the credit limit
	IncludeByokInLimit bool `json:"include_byok_in_limit"`
	// Human-readable label for the API key
	Label string `json:"label"`
	// Spending limit for the API key in USD
	Limit *float64 `json:"limit"`
	// Remaining spending limit in USD
	LimitRemaining *float64 `json:"limit_remaining"`
	// Type of limit reset for the API key
	LimitReset *string `json:"limit_reset"`
	// Name of the API key
	Name string `json:"name"`
	// ISO 8601 timestamp of when the API key was last updated
	UpdatedAt *string `json:"updated_at"`
	// Total OpenRouter credit usage (in USD) for the API key
	Usage float64 `json:"usage"`
	// OpenRouter credit usage (in USD) for the current UTC day
	UsageDaily float64 `json:"usage_daily"`
	// OpenRouter credit usage (in USD) for the current UTC month
	UsageMonthly float64 `json:"usage_monthly"`
	// OpenRouter credit usage (in USD) for the current UTC week (Monday-Sunday)
	UsageWeekly float64 `json:"usage_weekly"`
	// The workspace ID this API key belongs to.
	WorkspaceID string `json:"workspace_id"`
}

func (u UpdateKeysData) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateKeysData) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateKeysData) GetByokUsage() float64 {
	if u == nil {
		return 0.0
	}
	return u.ByokUsage
}

func (u *UpdateKeysData) GetByokUsageDaily() float64 {
	if u == nil {
		return 0.0
	}
	return u.ByokUsageDaily
}

func (u *UpdateKeysData) GetByokUsageMonthly() float64 {
	if u == nil {
		return 0.0
	}
	return u.ByokUsageMonthly
}

func (u *UpdateKeysData) GetByokUsageWeekly() float64 {
	if u == nil {
		return 0.0
	}
	return u.ByokUsageWeekly
}

func (u *UpdateKeysData) GetCreatedAt() string {
	if u == nil {
		return ""
	}
	return u.CreatedAt
}

func (u *UpdateKeysData) GetCreatorUserID() *string {
	if u == nil {
		return nil
	}
	return u.CreatorUserID
}

func (u *UpdateKeysData) GetDisabled() bool {
	if u == nil {
		return false
	}
	return u.Disabled
}

func (u *UpdateKeysData) GetExpiresAt() *time.Time {
	if u == nil {
		return nil
	}
	return u.ExpiresAt
}

func (u *UpdateKeysData) GetHash() string {
	if u == nil {
		return ""
	}
	return u.Hash
}

func (u *UpdateKeysData) GetIncludeByokInLimit() bool {
	if u == nil {
		return false
	}
	return u.IncludeByokInLimit
}

func (u *UpdateKeysData) GetLabel() string {
	if u == nil {
		return ""
	}
	return u.Label
}

func (u *UpdateKeysData) GetLimit() *float64 {
	if u == nil {
		return nil
	}
	return u.Limit
}

func (u *UpdateKeysData) GetLimitRemaining() *float64 {
	if u == nil {
		return nil
	}
	return u.LimitRemaining
}

func (u *UpdateKeysData) GetLimitReset() *string {
	if u == nil {
		return nil
	}
	return u.LimitReset
}

func (u *UpdateKeysData) GetName() string {
	if u == nil {
		return ""
	}
	return u.Name
}

func (u *UpdateKeysData) GetUpdatedAt() *string {
	if u == nil {
		return nil
	}
	return u.UpdatedAt
}

func (u *UpdateKeysData) GetUsage() float64 {
	if u == nil {
		return 0.0
	}
	return u.Usage
}

func (u *UpdateKeysData) GetUsageDaily() float64 {
	if u == nil {
		return 0.0
	}
	return u.UsageDaily
}

func (u *UpdateKeysData) GetUsageMonthly() float64 {
	if u == nil {
		return 0.0
	}
	return u.UsageMonthly
}

func (u *UpdateKeysData) GetUsageWeekly() float64 {
	if u == nil {
		return 0.0
	}
	return u.UsageWeekly
}

func (u *UpdateKeysData) GetWorkspaceID() string {
	if u == nil {
		return ""
	}
	return u.WorkspaceID
}

// UpdateKeysResponseBody - API key updated successfully
type UpdateKeysResponseBody struct {
	// The updated API key information
	Data UpdateKeysData `json:"data"`
}

func (u *UpdateKeysResponseBody) GetData() UpdateKeysData {
	if u == nil {
		return UpdateKeysData{}
	}
	return u.Data
}

type UpdateKeysResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// API key updated successfully
	Object *UpdateKeysResponseBody
	// Bad Request - Invalid request parameters or malformed input
	BadRequestResponse *shared.BadRequestResponse
	// Unauthorized - Authentication required or invalid credentials
	UnauthorizedResponse *shared.UnauthorizedResponse
	// Not Found - Resource does not exist
	NotFoundResponse *shared.NotFoundResponse
	// Too Many Requests - Rate limit exceeded
	TooManyRequestsResponse *shared.TooManyRequestsResponse
	// Internal Server Error - Unexpected server error
	InternalServerResponse *shared.InternalServerResponse
}

func (u UpdateKeysResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateKeysResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateKeysResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdateKeysResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdateKeysResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpdateKeysResponse) GetObject() *UpdateKeysResponseBody {
	if u == nil {
		return nil
	}
	return u.Object
}

func (u *UpdateKeysResponse) GetBadRequestResponse() *shared.BadRequestResponse {
	if u == nil {
		return nil
	}
	return u.BadRequestResponse
}

func (u *UpdateKeysResponse) GetUnauthorizedResponse() *shared.UnauthorizedResponse {
	if u == nil {
		return nil
	}
	return u.UnauthorizedResponse
}

func (u *UpdateKeysResponse) GetNotFoundResponse() *shared.NotFoundResponse {
	if u == nil {
		return nil
	}
	return u.NotFoundResponse
}

func (u *UpdateKeysResponse) GetTooManyRequestsResponse() *shared.TooManyRequestsResponse {
	if u == nil {
		return nil
	}
	return u.TooManyRequestsResponse
}

func (u *UpdateKeysResponse) GetInternalServerResponse() *shared.InternalServerResponse {
	if u == nil {
		return nil
	}
	return u.InternalServerResponse
}
