// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
)

// AdvisorNestedTool - A tool made available to the advisor sub-agent. Only OpenRouter server tools (e.g. openrouter:web_search) are supported; function tools are rejected because the advisor has no way to execute them. The advisor tool may not list itself.
type AdvisorNestedTool struct {
	Parameters           map[string]any `json:"parameters,omitzero"`
	Type                 string         `json:"type"`
	AdditionalProperties map[string]any `additionalProperties:"true" json:"-"`
}

func (a AdvisorNestedTool) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AdvisorNestedTool) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AdvisorNestedTool) GetParameters() map[string]any {
	if a == nil {
		return nil
	}
	return a.Parameters
}

func (a *AdvisorNestedTool) GetType() string {
	if a == nil {
		return ""
	}
	return a.Type
}

func (a *AdvisorNestedTool) GetAdditionalProperties() map[string]any {
	if a == nil {
		return nil
	}
	return a.AdditionalProperties
}
