// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 000c5485f4eb

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
)

type AlignmentChatImageImageURL struct {
	URL string `json:"url"`
}

func (a AlignmentChatImageImageURL) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AlignmentChatImageImageURL) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AlignmentChatImageImageURL) GetURL() string {
	if a == nil {
		return ""
	}
	return a.URL
}

type AlignmentChatImageType string

const (
	AlignmentChatImageTypeImageURL AlignmentChatImageType = "image_url"
)

func (e AlignmentChatImageType) ToPointer() *AlignmentChatImageType {
	return &e
}
func (e *AlignmentChatImageType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "image_url":
		*e = AlignmentChatImageType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AlignmentChatImageType: %v", v)
	}
}

type AlignmentChatImage struct {
	ImageURL AlignmentChatImageImageURL `json:"image_url"`
	Type     AlignmentChatImageType     `json:"type"`
}

func (a AlignmentChatImage) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AlignmentChatImage) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AlignmentChatImage) GetImageURL() AlignmentChatImageImageURL {
	if a == nil {
		return AlignmentChatImageImageURL{}
	}
	return a.ImageURL
}

func (a *AlignmentChatImage) GetType() AlignmentChatImageType {
	if a == nil {
		return AlignmentChatImageType("")
	}
	return a.Type
}
