// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 6babf9e600da

package shared

import (
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
)

type AnthropicTextEditorCodeExecutionCreateResult struct {
	IsFileUpdate bool `json:"is_file_update"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_ string `const:"text_editor_code_execution_create_result" json:"type"`
}

func (a AnthropicTextEditorCodeExecutionCreateResult) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AnthropicTextEditorCodeExecutionCreateResult) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AnthropicTextEditorCodeExecutionCreateResult) GetIsFileUpdate() bool {
	if a == nil {
		return false
	}
	return a.IsFileUpdate
}

func (a *AnthropicTextEditorCodeExecutionCreateResult) GetType() string {
	return "text_editor_code_execution_create_result"
}
