// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/openrouter/terraform-provider-openrouter/internal/sdk/internal/utils"
)

type AnthropicInputTokensTrigger struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_ string `const:"input_tokens" json:"type"`
	Value int64  `json:"value"`
}

func (a AnthropicInputTokensTrigger) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AnthropicInputTokensTrigger) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AnthropicInputTokensTrigger) GetType() string {
	return "input_tokens"
}

func (a *AnthropicInputTokensTrigger) GetValue() int64 {
	if a == nil {
		return 0
	}
	return a.Value
}
