// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/speakeasy/terraform-provider-openrouter/internal/sdk/internal/utils"
)

type AnthropicInputTokensClearAtLeastType string

const (
	AnthropicInputTokensClearAtLeastTypeInputTokens AnthropicInputTokensClearAtLeastType = "input_tokens"
)

func (e AnthropicInputTokensClearAtLeastType) ToPointer() *AnthropicInputTokensClearAtLeastType {
	return &e
}
func (e *AnthropicInputTokensClearAtLeastType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "input_tokens":
		*e = AnthropicInputTokensClearAtLeastType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AnthropicInputTokensClearAtLeastType: %v", v)
	}
}

type AnthropicInputTokensClearAtLeast struct {
	Type  AnthropicInputTokensClearAtLeastType `json:"type"`
	Value int64                                `json:"value"`
}

func (a AnthropicInputTokensClearAtLeast) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AnthropicInputTokensClearAtLeast) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AnthropicInputTokensClearAtLeast) GetType() AnthropicInputTokensClearAtLeastType {
	if a == nil {
		return AnthropicInputTokensClearAtLeastType("")
	}
	return a.Type
}

func (a *AnthropicInputTokensClearAtLeast) GetValue() int64 {
	if a == nil {
		return 0
	}
	return a.Value
}
