// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 4498e53a4edb

package shared

import (
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
)

type AnthropicCacheCreation struct {
	Ephemeral1hInputTokens int64 `json:"ephemeral_1h_input_tokens"`
	Ephemeral5mInputTokens int64 `json:"ephemeral_5m_input_tokens"`
}

func (a AnthropicCacheCreation) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AnthropicCacheCreation) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AnthropicCacheCreation) GetEphemeral1hInputTokens() int64 {
	if a == nil {
		return 0
	}
	return a.Ephemeral1hInputTokens
}

func (a *AnthropicCacheCreation) GetEphemeral5mInputTokens() int64 {
	if a == nil {
		return 0
	}
	return a.Ephemeral5mInputTokens
}
