// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: d9e41668753e

package shared

import (
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
)

type AnthropicCitationSearchResultLocation struct {
	CitedText         string  `json:"cited_text"`
	EndBlockIndex     int64   `json:"end_block_index"`
	SearchResultIndex int64   `json:"search_result_index"`
	Source            string  `json:"source"`
	StartBlockIndex   int64   `json:"start_block_index"`
	Title             *string `json:"title"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_ string `const:"search_result_location" json:"type"`
}

func (a AnthropicCitationSearchResultLocation) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AnthropicCitationSearchResultLocation) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AnthropicCitationSearchResultLocation) GetCitedText() string {
	if a == nil {
		return ""
	}
	return a.CitedText
}

func (a *AnthropicCitationSearchResultLocation) GetEndBlockIndex() int64 {
	if a == nil {
		return 0
	}
	return a.EndBlockIndex
}

func (a *AnthropicCitationSearchResultLocation) GetSearchResultIndex() int64 {
	if a == nil {
		return 0
	}
	return a.SearchResultIndex
}

func (a *AnthropicCitationSearchResultLocation) GetSource() string {
	if a == nil {
		return ""
	}
	return a.Source
}

func (a *AnthropicCitationSearchResultLocation) GetStartBlockIndex() int64 {
	if a == nil {
		return 0
	}
	return a.StartBlockIndex
}

func (a *AnthropicCitationSearchResultLocation) GetTitle() *string {
	if a == nil {
		return nil
	}
	return a.Title
}

func (a *AnthropicCitationSearchResultLocation) GetType() string {
	return "search_result_location"
}
