// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 731e9e9611a4

package shared

import (
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
)

type AnthropicTextBlock struct {
	Citations []AnthropicTextCitation `json:"citations"`
	Text      string                  `json:"text"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_ string `const:"text" json:"type"`
}

func (a AnthropicTextBlock) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AnthropicTextBlock) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AnthropicTextBlock) GetCitations() []AnthropicTextCitation {
	if a == nil {
		return nil
	}
	return a.Citations
}

func (a *AnthropicTextBlock) GetText() string {
	if a == nil {
		return ""
	}
	return a.Text
}

func (a *AnthropicTextBlock) GetType() string {
	return "text"
}
