// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 7ed274475457

package shared

import (
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
)

type AnthropicCodeExecution20250825Caller struct {
	ToolID string `json:"tool_id"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_ string `const:"code_execution_20250825" json:"type"`
}

func (a AnthropicCodeExecution20250825Caller) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AnthropicCodeExecution20250825Caller) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AnthropicCodeExecution20250825Caller) GetToolID() string {
	if a == nil {
		return ""
	}
	return a.ToolID
}

func (a *AnthropicCodeExecution20250825Caller) GetType() string {
	return "code_execution_20250825"
}

// #region class-body-anthropiccodeexecution20250825caller
// #endregion class-body-anthropiccodeexecution20250825caller
