// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: ddb777a5fc64

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
)

type AnthropicWebFetchToolResultErrorErrorCode string

const (
	AnthropicWebFetchToolResultErrorErrorCodeContentTooLarge        AnthropicWebFetchToolResultErrorErrorCode = "content_too_large"
	AnthropicWebFetchToolResultErrorErrorCodeInvalidToolInput       AnthropicWebFetchToolResultErrorErrorCode = "invalid_tool_input"
	AnthropicWebFetchToolResultErrorErrorCodeURLTooLong             AnthropicWebFetchToolResultErrorErrorCode = "url_too_long"
	AnthropicWebFetchToolResultErrorErrorCodeURLNotAllowed          AnthropicWebFetchToolResultErrorErrorCode = "url_not_allowed"
	AnthropicWebFetchToolResultErrorErrorCodeURLNotInPriorContext   AnthropicWebFetchToolResultErrorErrorCode = "url_not_in_prior_context"
	AnthropicWebFetchToolResultErrorErrorCodeURLNotAccessible       AnthropicWebFetchToolResultErrorErrorCode = "url_not_accessible"
	AnthropicWebFetchToolResultErrorErrorCodeUnsupportedContentType AnthropicWebFetchToolResultErrorErrorCode = "unsupported_content_type"
	AnthropicWebFetchToolResultErrorErrorCodeTooManyRequests        AnthropicWebFetchToolResultErrorErrorCode = "too_many_requests"
	AnthropicWebFetchToolResultErrorErrorCodeMaxUsesExceeded        AnthropicWebFetchToolResultErrorErrorCode = "max_uses_exceeded"
	AnthropicWebFetchToolResultErrorErrorCodeUnavailable            AnthropicWebFetchToolResultErrorErrorCode = "unavailable"
)

func (e AnthropicWebFetchToolResultErrorErrorCode) ToPointer() *AnthropicWebFetchToolResultErrorErrorCode {
	return &e
}
func (e *AnthropicWebFetchToolResultErrorErrorCode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "content_too_large":
		fallthrough
	case "invalid_tool_input":
		fallthrough
	case "url_too_long":
		fallthrough
	case "url_not_allowed":
		fallthrough
	case "url_not_in_prior_context":
		fallthrough
	case "url_not_accessible":
		fallthrough
	case "unsupported_content_type":
		fallthrough
	case "too_many_requests":
		fallthrough
	case "max_uses_exceeded":
		fallthrough
	case "unavailable":
		*e = AnthropicWebFetchToolResultErrorErrorCode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AnthropicWebFetchToolResultErrorErrorCode: %v", v)
	}
}

type AnthropicWebFetchToolResultError struct {
	ErrorCode AnthropicWebFetchToolResultErrorErrorCode `json:"error_code"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_ string `const:"web_fetch_tool_result_error" json:"type"`
}

func (a AnthropicWebFetchToolResultError) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AnthropicWebFetchToolResultError) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AnthropicWebFetchToolResultError) GetErrorCode() AnthropicWebFetchToolResultErrorErrorCode {
	if a == nil {
		return AnthropicWebFetchToolResultErrorErrorCode("")
	}
	return a.ErrorCode
}

func (a *AnthropicWebFetchToolResultError) GetType() string {
	return "web_fetch_tool_result_error"
}
