// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 9ea3b834a11c

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
)

type AnthropicWebSearchToolUserLocationType string

const (
	AnthropicWebSearchToolUserLocationTypeApproximate AnthropicWebSearchToolUserLocationType = "approximate"
)

func (e AnthropicWebSearchToolUserLocationType) ToPointer() *AnthropicWebSearchToolUserLocationType {
	return &e
}
func (e *AnthropicWebSearchToolUserLocationType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "approximate":
		*e = AnthropicWebSearchToolUserLocationType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AnthropicWebSearchToolUserLocationType: %v", v)
	}
}

type AnthropicWebSearchToolUserLocation struct {
	City     *string                                `json:"city,omitzero"`
	Country  *string                                `json:"country,omitzero"`
	Region   *string                                `json:"region,omitzero"`
	Timezone *string                                `json:"timezone,omitzero"`
	Type     AnthropicWebSearchToolUserLocationType `json:"type"`
}

func (a AnthropicWebSearchToolUserLocation) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AnthropicWebSearchToolUserLocation) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AnthropicWebSearchToolUserLocation) GetCity() *string {
	if a == nil {
		return nil
	}
	return a.City
}

func (a *AnthropicWebSearchToolUserLocation) GetCountry() *string {
	if a == nil {
		return nil
	}
	return a.Country
}

func (a *AnthropicWebSearchToolUserLocation) GetRegion() *string {
	if a == nil {
		return nil
	}
	return a.Region
}

func (a *AnthropicWebSearchToolUserLocation) GetTimezone() *string {
	if a == nil {
		return nil
	}
	return a.Timezone
}

func (a *AnthropicWebSearchToolUserLocation) GetType() AnthropicWebSearchToolUserLocationType {
	if a == nil {
		return AnthropicWebSearchToolUserLocationType("")
	}
	return a.Type
}
