// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 863d8a7affe0

package shared

import (
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
)

type AnthropicContainer struct {
	ExpiresAt string                    `json:"expires_at"`
	ID        string                    `json:"id"`
	Skills    []AnthropicContainerSkill `json:"skills"`
}

func (a AnthropicContainer) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AnthropicContainer) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AnthropicContainer) GetExpiresAt() string {
	if a == nil {
		return ""
	}
	return a.ExpiresAt
}

func (a *AnthropicContainer) GetID() string {
	if a == nil {
		return ""
	}
	return a.ID
}

func (a *AnthropicContainer) GetSkills() []AnthropicContainerSkill {
	if a == nil {
		return nil
	}
	return a.Skills
}
