// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 0b41f2501f04

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
)

type AnthropicMessageUsageIterationType string

const (
	AnthropicMessageUsageIterationTypeMessage AnthropicMessageUsageIterationType = "message"
)

func (e AnthropicMessageUsageIterationType) ToPointer() *AnthropicMessageUsageIterationType {
	return &e
}
func (e *AnthropicMessageUsageIterationType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "message":
		*e = AnthropicMessageUsageIterationType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AnthropicMessageUsageIterationType: %v", v)
	}
}

type AnthropicMessageUsageIteration struct {
	CacheCreation            *AnthropicIterationCacheCreation   `json:"cache_creation,omitzero"`
	CacheCreationInputTokens *int64                             `json:"cache_creation_input_tokens,omitzero"`
	CacheReadInputTokens     *int64                             `json:"cache_read_input_tokens,omitzero"`
	InputTokens              *int64                             `json:"input_tokens,omitzero"`
	OutputTokens             *int64                             `json:"output_tokens,omitzero"`
	Model                    *string                            `json:"model,omitzero"`
	Type                     AnthropicMessageUsageIterationType `json:"type"`
}

func (a AnthropicMessageUsageIteration) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AnthropicMessageUsageIteration) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AnthropicMessageUsageIteration) GetCacheCreation() *AnthropicIterationCacheCreation {
	if a == nil {
		return nil
	}
	return a.CacheCreation
}

func (a *AnthropicMessageUsageIteration) GetCacheCreationInputTokens() *int64 {
	if a == nil {
		return nil
	}
	return a.CacheCreationInputTokens
}

func (a *AnthropicMessageUsageIteration) GetCacheReadInputTokens() *int64 {
	if a == nil {
		return nil
	}
	return a.CacheReadInputTokens
}

func (a *AnthropicMessageUsageIteration) GetInputTokens() *int64 {
	if a == nil {
		return nil
	}
	return a.InputTokens
}

func (a *AnthropicMessageUsageIteration) GetOutputTokens() *int64 {
	if a == nil {
		return nil
	}
	return a.OutputTokens
}

func (a *AnthropicMessageUsageIteration) GetModel() *string {
	if a == nil {
		return nil
	}
	return a.Model
}

func (a *AnthropicMessageUsageIteration) GetType() AnthropicMessageUsageIterationType {
	if a == nil {
		return AnthropicMessageUsageIterationType("")
	}
	return a.Type
}
