// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
)

type AnthropicToolSearchToolRegexName string

const (
	AnthropicToolSearchToolRegexNameToolSearchToolRegex AnthropicToolSearchToolRegexName = "tool_search_tool_regex"
)

func (e AnthropicToolSearchToolRegexName) ToPointer() *AnthropicToolSearchToolRegexName {
	return &e
}
func (e *AnthropicToolSearchToolRegexName) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "tool_search_tool_regex":
		*e = AnthropicToolSearchToolRegexName(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AnthropicToolSearchToolRegexName: %v", v)
	}
}

type AnthropicToolSearchToolRegexType string

const (
	AnthropicToolSearchToolRegexTypeToolSearchToolRegex20251119 AnthropicToolSearchToolRegexType = "tool_search_tool_regex_20251119"
	AnthropicToolSearchToolRegexTypeToolSearchToolRegex         AnthropicToolSearchToolRegexType = "tool_search_tool_regex"
)

func (e AnthropicToolSearchToolRegexType) ToPointer() *AnthropicToolSearchToolRegexType {
	return &e
}
func (e *AnthropicToolSearchToolRegexType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "tool_search_tool_regex_20251119":
		fallthrough
	case "tool_search_tool_regex":
		*e = AnthropicToolSearchToolRegexType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AnthropicToolSearchToolRegexType: %v", v)
	}
}

type AnthropicToolSearchToolRegex struct {
	AllowedCallers []AnthropicAllowedCallers `json:"allowed_callers,omitzero"`
	// Enable automatic prompt caching. When set at the top level, the system automatically applies cache breakpoints to the last cacheable block in the request. When set on an individual content block, it marks an explicit cache breakpoint; block-level markers also work on OpenAI models that support explicit prompt caching — OpenRouter converts them to the provider's native format.
	CacheControl *AnthropicCacheControlDirective  `json:"cache_control,omitzero"`
	DeferLoading *bool                            `json:"defer_loading,omitzero"`
	Name         AnthropicToolSearchToolRegexName `json:"name"`
	Strict       *bool                            `json:"strict,omitzero"`
	Type         AnthropicToolSearchToolRegexType `json:"type"`
}

func (a AnthropicToolSearchToolRegex) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AnthropicToolSearchToolRegex) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AnthropicToolSearchToolRegex) GetAllowedCallers() []AnthropicAllowedCallers {
	if a == nil {
		return nil
	}
	return a.AllowedCallers
}

func (a *AnthropicToolSearchToolRegex) GetCacheControl() *AnthropicCacheControlDirective {
	if a == nil {
		return nil
	}
	return a.CacheControl
}

func (a *AnthropicToolSearchToolRegex) GetDeferLoading() *bool {
	if a == nil {
		return nil
	}
	return a.DeferLoading
}

func (a *AnthropicToolSearchToolRegex) GetName() AnthropicToolSearchToolRegexName {
	if a == nil {
		return AnthropicToolSearchToolRegexName("")
	}
	return a.Name
}

func (a *AnthropicToolSearchToolRegex) GetStrict() *bool {
	if a == nil {
		return nil
	}
	return a.Strict
}

func (a *AnthropicToolSearchToolRegex) GetType() AnthropicToolSearchToolRegexType {
	if a == nil {
		return AnthropicToolSearchToolRegexType("")
	}
	return a.Type
}
