// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 559481f9c077

package shared

import (
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
)

type AnthropicBashCodeExecutionToolResult struct {
	Content   AnthropicBashCodeExecutionContent `json:"content"`
	ToolUseID string                            `json:"tool_use_id"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_ string `const:"bash_code_execution_tool_result" json:"type"`
}

func (a AnthropicBashCodeExecutionToolResult) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AnthropicBashCodeExecutionToolResult) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AnthropicBashCodeExecutionToolResult) GetContent() AnthropicBashCodeExecutionContent {
	if a == nil {
		return AnthropicBashCodeExecutionContent{}
	}
	return a.Content
}

func (a *AnthropicBashCodeExecutionToolResult) GetContentBashCodeExecutionResult() *AnthropicBashCodeExecutionResult {
	return a.GetContent().AnthropicBashCodeExecutionResult
}

func (a *AnthropicBashCodeExecutionToolResult) GetContentBashCodeExecutionToolResultError() *AnthropicBashCodeExecutionToolResultError {
	return a.GetContent().AnthropicBashCodeExecutionToolResultError
}

func (a *AnthropicBashCodeExecutionToolResult) GetToolUseID() string {
	if a == nil {
		return ""
	}
	return a.ToolUseID
}

func (a *AnthropicBashCodeExecutionToolResult) GetType() string {
	return "bash_code_execution_tool_result"
}
