// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
)

// ApplyPatchDeleteFileOperation - The `delete_file` variant of an `apply_patch_call.operation`. Identifies the file to remove; no diff is required.
type ApplyPatchDeleteFileOperation struct {
	Path string `json:"path"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_ string `const:"delete_file" json:"type"`
}

func (a ApplyPatchDeleteFileOperation) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *ApplyPatchDeleteFileOperation) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *ApplyPatchDeleteFileOperation) GetPath() string {
	if a == nil {
		return ""
	}
	return a.Path
}

func (a *ApplyPatchDeleteFileOperation) GetType() string {
	return "delete_file"
}
