// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 6ce4010671de

package shared

import (
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
)

type BaseReasoningConfig struct {
	// Controls which reasoning is available to the model. `auto` uses the model default (same as omitting); `all_turns` includes reasoning from earlier turns passed in input; `current_turn` limits to the current turn only. Only supported by OpenAI GPT-5.6 and newer.
	Context *ReasoningContext `json:"context,omitzero"`
	Effort  *ReasoningEffort  `json:"effort,omitzero"`
	// Selects the reasoning mode. `standard` is the default; `pro` engages deeper reasoning on models that support it, billed at standard token rates. Only supported by OpenAI GPT-5.6 and newer.
	Mode    *ReasoningMode             `json:"mode,omitzero"`
	Summary *ReasoningSummaryVerbosity `json:"summary,omitzero"`
}

func (b BaseReasoningConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BaseReasoningConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BaseReasoningConfig) GetContext() *ReasoningContext {
	if b == nil {
		return nil
	}
	return b.Context
}

func (b *BaseReasoningConfig) GetEffort() *ReasoningEffort {
	if b == nil {
		return nil
	}
	return b.Effort
}

func (b *BaseReasoningConfig) GetMode() *ReasoningMode {
	if b == nil {
		return nil
	}
	return b.Mode
}

func (b *BaseReasoningConfig) GetSummary() *ReasoningSummaryVerbosity {
	if b == nil {
		return nil
	}
	return b.Summary
}
