// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: d5cb6654f755

package shared

import (
	"encoding/json"
	"fmt"
)

type BatchListResponseObject string

const (
	BatchListResponseObjectList BatchListResponseObject = "list"
)

func (e BatchListResponseObject) ToPointer() *BatchListResponseObject {
	return &e
}
func (e *BatchListResponseObject) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "list":
		*e = BatchListResponseObject(v)
		return nil
	default:
		return fmt.Errorf("invalid value for BatchListResponseObject: %v", v)
	}
}

// BatchListResponse - A newest-first page of metadata-only batch objects.
type BatchListResponse struct {
	Data    []BatchListItem         `json:"data"`
	FirstID *string                 `json:"first_id"`
	HasMore bool                    `json:"has_more"`
	LastID  *string                 `json:"last_id"`
	Object  BatchListResponseObject `json:"object"`
}

func (b *BatchListResponse) GetData() []BatchListItem {
	if b == nil {
		return []BatchListItem{}
	}
	return b.Data
}

func (b *BatchListResponse) GetFirstID() *string {
	if b == nil {
		return nil
	}
	return b.FirstID
}

func (b *BatchListResponse) GetHasMore() bool {
	if b == nil {
		return false
	}
	return b.HasMore
}

func (b *BatchListResponse) GetLastID() *string {
	if b == nil {
		return nil
	}
	return b.LastID
}

func (b *BatchListResponse) GetObject() BatchListResponseObject {
	if b == nil {
		return BatchListResponseObject("")
	}
	return b.Object
}
