// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 513f6c2c4b53

package shared

import (
	"encoding/json"
	"fmt"
)

// BatchListStatus - A batch status that is durably represented by the list data source. `finalizing` and `cancelling` are not accepted because stored jobs collapse those phases into `in_progress`.
type BatchListStatus string

const (
	BatchListStatusValidating BatchListStatus = "validating"
	BatchListStatusInProgress BatchListStatus = "in_progress"
	BatchListStatusCompleted  BatchListStatus = "completed"
	BatchListStatusFailed     BatchListStatus = "failed"
	BatchListStatusExpired    BatchListStatus = "expired"
	BatchListStatusCancelled  BatchListStatus = "cancelled"
)

func (e BatchListStatus) ToPointer() *BatchListStatus {
	return &e
}
func (e *BatchListStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "validating":
		fallthrough
	case "in_progress":
		fallthrough
	case "completed":
		fallthrough
	case "failed":
		fallthrough
	case "expired":
		fallthrough
	case "cancelled":
		*e = BatchListStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for BatchListStatus: %v", v)
	}
}
