// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: eceb863a7ada

package shared

import (
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
)

type ChatContentFileFile struct {
	// File content as base64 data URL or URL
	FileData *string `json:"file_data,omitzero"`
	// File ID for previously uploaded files
	FileID *string `json:"file_id,omitzero"`
	// Original filename
	Filename *string `json:"filename,omitzero"`
}

func (c ChatContentFileFile) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ChatContentFileFile) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ChatContentFileFile) GetFileData() *string {
	if c == nil {
		return nil
	}
	return c.FileData
}

func (c *ChatContentFileFile) GetFileID() *string {
	if c == nil {
		return nil
	}
	return c.FileID
}

func (c *ChatContentFileFile) GetFilename() *string {
	if c == nil {
		return nil
	}
	return c.Filename
}

// ChatContentFile - File content part for document processing
type ChatContentFile struct {
	File ChatContentFileFile `json:"file"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_ string `const:"file" json:"type"`
}

func (c ChatContentFile) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ChatContentFile) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ChatContentFile) GetFile() ChatContentFileFile {
	if c == nil {
		return ChatContentFileFile{}
	}
	return c.File
}

func (c *ChatContentFile) GetType() string {
	return "file"
}
