// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: c8b455ad7865

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
)

type ChatContentCacheControlType string

const (
	ChatContentCacheControlTypeEphemeral ChatContentCacheControlType = "ephemeral"
)

func (e ChatContentCacheControlType) ToPointer() *ChatContentCacheControlType {
	return &e
}
func (e *ChatContentCacheControlType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ephemeral":
		*e = ChatContentCacheControlType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ChatContentCacheControlType: %v", v)
	}
}

// ChatContentCacheControl - Anthropic-style cache breakpoint for the content part. Interchangeable with the OpenAI-style `prompt_cache_breakpoint` marker: OpenRouter converts between the two based on the provider serving the request.
type ChatContentCacheControl struct {
	TTL  *AnthropicCacheControlTTL   `json:"ttl,omitzero"`
	Type ChatContentCacheControlType `json:"type"`
}

func (c ChatContentCacheControl) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ChatContentCacheControl) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ChatContentCacheControl) GetTTL() *AnthropicCacheControlTTL {
	if c == nil {
		return nil
	}
	return c.TTL
}

func (c *ChatContentCacheControl) GetType() ChatContentCacheControlType {
	if c == nil {
		return ChatContentCacheControlType("")
	}
	return c.Type
}
