// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: bebbbcb260e1

package shared

import (
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
)

// ChatFormatGrammarConfig - Custom grammar response format
type ChatFormatGrammarConfig struct {
	// Custom grammar for text generation
	Grammar string `json:"grammar"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_ string `const:"grammar" json:"type"`
}

func (c ChatFormatGrammarConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ChatFormatGrammarConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ChatFormatGrammarConfig) GetGrammar() string {
	if c == nil {
		return ""
	}
	return c.Grammar
}

func (c *ChatFormatGrammarConfig) GetType() string {
	return "grammar"
}
