// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 29d0c45f66a1

package shared

import (
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
)

// ChatContentVideo - Video input content part
type ChatContentVideo struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_ string `const:"video_url" json:"type"`
	// Video input object
	VideoURL ChatContentVideoInput `json:"video_url"`
}

func (c ChatContentVideo) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ChatContentVideo) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ChatContentVideo) GetType() string {
	return "video_url"
}

func (c *ChatContentVideo) GetVideoURL() ChatContentVideoInput {
	if c == nil {
		return ChatContentVideoInput{}
	}
	return c.VideoURL
}
