// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"errors"
	"fmt"
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
)

type ChatUserMessageContentType string

const (
	ChatUserMessageContentTypeStr                     ChatUserMessageContentType = "str"
	ChatUserMessageContentTypeArrayOfChatContentItems ChatUserMessageContentType = "arrayOfChatContentItems"
)

// ChatUserMessageContent - User message content
type ChatUserMessageContent struct {
	Str                     *string            `queryParam:"inline" union:"member"`
	ArrayOfChatContentItems []ChatContentItems `queryParam:"inline" union:"member"`

	Type ChatUserMessageContentType
}

func CreateChatUserMessageContentStr(str string) ChatUserMessageContent {
	typ := ChatUserMessageContentTypeStr

	return ChatUserMessageContent{
		Str:  &str,
		Type: typ,
	}
}

func CreateChatUserMessageContentArrayOfChatContentItems(arrayOfChatContentItems []ChatContentItems) ChatUserMessageContent {
	typ := ChatUserMessageContentTypeArrayOfChatContentItems

	return ChatUserMessageContent{
		ArrayOfChatContentItems: arrayOfChatContentItems,
		Type:                    typ,
	}
}

func (u *ChatUserMessageContent) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ChatUserMessageContentTypeStr,
			Value: &str,
		})
	}

	var arrayOfChatContentItems []ChatContentItems = []ChatContentItems{}
	if err := utils.UnmarshalJSON(data, &arrayOfChatContentItems, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ChatUserMessageContentTypeArrayOfChatContentItems,
			Value: arrayOfChatContentItems,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for ChatUserMessageContent", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for ChatUserMessageContent", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(ChatUserMessageContentType)
	switch best.Type {
	case ChatUserMessageContentTypeStr:
		u.Str = best.Value.(*string)
		return nil
	case ChatUserMessageContentTypeArrayOfChatContentItems:
		u.ArrayOfChatContentItems = best.Value.([]ChatContentItems)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for ChatUserMessageContent", string(data))
}

func (u ChatUserMessageContent) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.ArrayOfChatContentItems != nil {
		return utils.MarshalJSON(u.ArrayOfChatContentItems, "", true)
	}

	return nil, errors.New("could not marshal union type ChatUserMessageContent: all fields are null")
}

// ChatUserMessage - User message
type ChatUserMessage struct {
	// User message content
	Content ChatUserMessageContent `json:"content"`
	// Optional name for the user
	Name *string `json:"name,omitzero"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	role string `const:"user" json:"role"`
}

func (c ChatUserMessage) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ChatUserMessage) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ChatUserMessage) GetContent() ChatUserMessageContent {
	if c == nil {
		return ChatUserMessageContent{}
	}
	return c.Content
}

func (c *ChatUserMessage) GetName() *string {
	if c == nil {
		return nil
	}
	return c.Name
}

func (c *ChatUserMessage) GetRole() string {
	return "user"
}
