// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/speakeasy/terraform-provider-openrouter/internal/sdk/internal/utils"
)

// ChatFunctionToolFunctionFunction - Function definition for tool calling
type ChatFunctionToolFunctionFunction struct {
	// Function description for the model
	Description *string `json:"description,omitzero"`
	// Function name (a-z, A-Z, 0-9, underscores, dashes, max 64 chars)
	Name string `json:"name"`
	// Function parameters as JSON Schema object
	Parameters map[string]any `json:"parameters,omitzero"`
	// Enable strict schema adherence
	Strict *bool `json:"strict,omitzero"`
}

func (c ChatFunctionToolFunctionFunction) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ChatFunctionToolFunctionFunction) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ChatFunctionToolFunctionFunction) GetDescription() *string {
	if c == nil {
		return nil
	}
	return c.Description
}

func (c *ChatFunctionToolFunctionFunction) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *ChatFunctionToolFunctionFunction) GetParameters() map[string]any {
	if c == nil {
		return nil
	}
	return c.Parameters
}

func (c *ChatFunctionToolFunctionFunction) GetStrict() *bool {
	if c == nil {
		return nil
	}
	return c.Strict
}

type ChatFunctionToolFunction struct {
	// Anthropic-style cache breakpoint for the content part. Interchangeable with the OpenAI-style `prompt_cache_breakpoint` marker: OpenRouter converts between the two based on the provider serving the request.
	CacheControl *ChatContentCacheControl `json:"cache_control,omitzero"`
	// Function definition for tool calling
	Function ChatFunctionToolFunctionFunction `json:"function"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_ string `const:"function" json:"type"`
}

func (c ChatFunctionToolFunction) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ChatFunctionToolFunction) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ChatFunctionToolFunction) GetCacheControl() *ChatContentCacheControl {
	if c == nil {
		return nil
	}
	return c.CacheControl
}

func (c *ChatFunctionToolFunction) GetFunction() ChatFunctionToolFunctionFunction {
	if c == nil {
		return ChatFunctionToolFunctionFunction{}
	}
	return c.Function
}

func (c *ChatFunctionToolFunction) GetType() string {
	return "function"
}

type ChatFunctionToolUnionType string

const (
	ChatFunctionToolUnionTypeFunction                           ChatFunctionToolUnionType = "function"
	ChatFunctionToolUnionTypeOpenrouterAdvisor                  ChatFunctionToolUnionType = "openrouter:advisor"
	ChatFunctionToolUnionTypeOpenrouterBash                     ChatFunctionToolUnionType = "openrouter:bash"
	ChatFunctionToolUnionTypeOpenrouterDatetime                 ChatFunctionToolUnionType = "openrouter:datetime"
	ChatFunctionToolUnionTypeOpenrouterFiles                    ChatFunctionToolUnionType = "openrouter:files"
	ChatFunctionToolUnionTypeOpenrouterFusion                   ChatFunctionToolUnionType = "openrouter:fusion"
	ChatFunctionToolUnionTypeOpenrouterImageGeneration          ChatFunctionToolUnionType = "openrouter:image_generation"
	ChatFunctionToolUnionTypeOpenrouterExperimentalSearchModels ChatFunctionToolUnionType = "openrouter:experimental__search_models"
	ChatFunctionToolUnionTypeOpenrouterSubagent                 ChatFunctionToolUnionType = "openrouter:subagent"
	ChatFunctionToolUnionTypeOpenrouterWebFetch                 ChatFunctionToolUnionType = "openrouter:web_fetch"
	ChatFunctionToolUnionTypeOpenrouterWebSearch                ChatFunctionToolUnionType = "openrouter:web_search"
	ChatFunctionToolUnionTypeWebSearch                          ChatFunctionToolUnionType = "web_search"
	ChatFunctionToolUnionTypeWebSearchPreview                   ChatFunctionToolUnionType = "web_search_preview"
	ChatFunctionToolUnionTypeWebSearchPreview20250311           ChatFunctionToolUnionType = "web_search_preview_2025_03_11"
	ChatFunctionToolUnionTypeWebSearch20250826                  ChatFunctionToolUnionType = "web_search_2025_08_26"
)

// ChatFunctionTool - Tool definition for function calling (regular function or OpenRouter built-in server tool)
type ChatFunctionTool struct {
	ChatFunctionToolFunction            *ChatFunctionToolFunction            `queryParam:"inline" union:"member"`
	AdvisorServerToolOpenRouter         *AdvisorServerToolOpenRouter         `queryParam:"inline" union:"member"`
	BashServerTool                      *BashServerTool                      `queryParam:"inline" union:"member"`
	DatetimeServerTool                  *DatetimeServerTool                  `queryParam:"inline" union:"member"`
	FilesServerTool                     *FilesServerTool                     `queryParam:"inline" union:"member"`
	FusionServerToolOpenRouter          *FusionServerToolOpenRouter          `queryParam:"inline" union:"member"`
	ImageGenerationServerToolOpenRouter *ImageGenerationServerToolOpenRouter `queryParam:"inline" union:"member"`
	ChatSearchModelsServerTool          *ChatSearchModelsServerTool          `queryParam:"inline" union:"member"`
	SubagentServerToolOpenRouter        *SubagentServerToolOpenRouter        `queryParam:"inline" union:"member"`
	WebFetchServerTool                  *WebFetchServerTool                  `queryParam:"inline" union:"member"`
	OpenRouterWebSearchServerTool       *OpenRouterWebSearchServerTool       `queryParam:"inline" union:"member"`
	ChatWebSearchShorthand              *ChatWebSearchShorthand              `queryParam:"inline" union:"member"`

	Type ChatFunctionToolUnionType
}

func CreateChatFunctionToolFunction(function ChatFunctionToolFunction) ChatFunctionTool {
	typ := ChatFunctionToolUnionTypeFunction

	return ChatFunctionTool{
		ChatFunctionToolFunction: &function,
		Type:                     typ,
	}
}

func CreateChatFunctionToolOpenrouterAdvisor(openrouterAdvisor AdvisorServerToolOpenRouter) ChatFunctionTool {
	typ := ChatFunctionToolUnionTypeOpenrouterAdvisor

	typStr := AdvisorServerToolOpenRouterType(typ)
	openrouterAdvisor.Type = typStr

	return ChatFunctionTool{
		AdvisorServerToolOpenRouter: &openrouterAdvisor,
		Type:                        typ,
	}
}

func CreateChatFunctionToolOpenrouterBash(openrouterBash BashServerTool) ChatFunctionTool {
	typ := ChatFunctionToolUnionTypeOpenrouterBash

	typStr := BashServerToolType(typ)
	openrouterBash.Type = typStr

	return ChatFunctionTool{
		BashServerTool: &openrouterBash,
		Type:           typ,
	}
}

func CreateChatFunctionToolOpenrouterDatetime(openrouterDatetime DatetimeServerTool) ChatFunctionTool {
	typ := ChatFunctionToolUnionTypeOpenrouterDatetime

	typStr := DatetimeServerToolType(typ)
	openrouterDatetime.Type = typStr

	return ChatFunctionTool{
		DatetimeServerTool: &openrouterDatetime,
		Type:               typ,
	}
}

func CreateChatFunctionToolOpenrouterFiles(openrouterFiles FilesServerTool) ChatFunctionTool {
	typ := ChatFunctionToolUnionTypeOpenrouterFiles

	typStr := FilesServerToolType(typ)
	openrouterFiles.Type = typStr

	return ChatFunctionTool{
		FilesServerTool: &openrouterFiles,
		Type:            typ,
	}
}

func CreateChatFunctionToolOpenrouterFusion(openrouterFusion FusionServerToolOpenRouter) ChatFunctionTool {
	typ := ChatFunctionToolUnionTypeOpenrouterFusion

	typStr := FusionServerToolOpenRouterType(typ)
	openrouterFusion.Type = typStr

	return ChatFunctionTool{
		FusionServerToolOpenRouter: &openrouterFusion,
		Type:                       typ,
	}
}

func CreateChatFunctionToolOpenrouterImageGeneration(openrouterImageGeneration ImageGenerationServerToolOpenRouter) ChatFunctionTool {
	typ := ChatFunctionToolUnionTypeOpenrouterImageGeneration

	typStr := ImageGenerationServerToolOpenRouterType(typ)
	openrouterImageGeneration.Type = typStr

	return ChatFunctionTool{
		ImageGenerationServerToolOpenRouter: &openrouterImageGeneration,
		Type:                                typ,
	}
}

func CreateChatFunctionToolOpenrouterExperimentalSearchModels(openrouterExperimentalSearchModels ChatSearchModelsServerTool) ChatFunctionTool {
	typ := ChatFunctionToolUnionTypeOpenrouterExperimentalSearchModels

	return ChatFunctionTool{
		ChatSearchModelsServerTool: &openrouterExperimentalSearchModels,
		Type:                       typ,
	}
}

func CreateChatFunctionToolOpenrouterSubagent(openrouterSubagent SubagentServerToolOpenRouter) ChatFunctionTool {
	typ := ChatFunctionToolUnionTypeOpenrouterSubagent

	typStr := SubagentServerToolOpenRouterType(typ)
	openrouterSubagent.Type = typStr

	return ChatFunctionTool{
		SubagentServerToolOpenRouter: &openrouterSubagent,
		Type:                         typ,
	}
}

func CreateChatFunctionToolOpenrouterWebFetch(openrouterWebFetch WebFetchServerTool) ChatFunctionTool {
	typ := ChatFunctionToolUnionTypeOpenrouterWebFetch

	typStr := WebFetchServerToolType(typ)
	openrouterWebFetch.Type = typStr

	return ChatFunctionTool{
		WebFetchServerTool: &openrouterWebFetch,
		Type:               typ,
	}
}

func CreateChatFunctionToolOpenrouterWebSearch(openrouterWebSearch OpenRouterWebSearchServerTool) ChatFunctionTool {
	typ := ChatFunctionToolUnionTypeOpenrouterWebSearch

	typStr := OpenRouterWebSearchServerToolType(typ)
	openrouterWebSearch.Type = typStr

	return ChatFunctionTool{
		OpenRouterWebSearchServerTool: &openrouterWebSearch,
		Type:                          typ,
	}
}

func CreateChatFunctionToolWebSearch(webSearch ChatWebSearchShorthand) ChatFunctionTool {
	typ := ChatFunctionToolUnionTypeWebSearch

	typStr := ChatWebSearchShorthandType(typ)
	webSearch.Type = typStr

	return ChatFunctionTool{
		ChatWebSearchShorthand: &webSearch,
		Type:                   typ,
	}
}

func CreateChatFunctionToolWebSearchPreview(webSearchPreview ChatWebSearchShorthand) ChatFunctionTool {
	typ := ChatFunctionToolUnionTypeWebSearchPreview

	typStr := ChatWebSearchShorthandType(typ)
	webSearchPreview.Type = typStr

	return ChatFunctionTool{
		ChatWebSearchShorthand: &webSearchPreview,
		Type:                   typ,
	}
}

func CreateChatFunctionToolWebSearchPreview20250311(webSearchPreview20250311 ChatWebSearchShorthand) ChatFunctionTool {
	typ := ChatFunctionToolUnionTypeWebSearchPreview20250311

	typStr := ChatWebSearchShorthandType(typ)
	webSearchPreview20250311.Type = typStr

	return ChatFunctionTool{
		ChatWebSearchShorthand: &webSearchPreview20250311,
		Type:                   typ,
	}
}

func CreateChatFunctionToolWebSearch20250826(webSearch20250826 ChatWebSearchShorthand) ChatFunctionTool {
	typ := ChatFunctionToolUnionTypeWebSearch20250826

	typStr := ChatWebSearchShorthandType(typ)
	webSearch20250826.Type = typStr

	return ChatFunctionTool{
		ChatWebSearchShorthand: &webSearch20250826,
		Type:                   typ,
	}
}

func (u *ChatFunctionTool) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Type string `json:"type"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.Type {
	case "function":
		chatFunctionToolFunction := new(ChatFunctionToolFunction)
		if err := utils.UnmarshalJSON(data, &chatFunctionToolFunction, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == function) type ChatFunctionToolFunction within ChatFunctionTool: %w", string(data), err)
		}

		u.ChatFunctionToolFunction = chatFunctionToolFunction
		u.Type = ChatFunctionToolUnionTypeFunction
		return nil
	case "openrouter:advisor":
		advisorServerToolOpenRouter := new(AdvisorServerToolOpenRouter)
		if err := utils.UnmarshalJSON(data, &advisorServerToolOpenRouter, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == openrouter:advisor) type AdvisorServerToolOpenRouter within ChatFunctionTool: %w", string(data), err)
		}

		u.AdvisorServerToolOpenRouter = advisorServerToolOpenRouter
		u.Type = ChatFunctionToolUnionTypeOpenrouterAdvisor
		return nil
	case "openrouter:bash":
		bashServerTool := new(BashServerTool)
		if err := utils.UnmarshalJSON(data, &bashServerTool, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == openrouter:bash) type BashServerTool within ChatFunctionTool: %w", string(data), err)
		}

		u.BashServerTool = bashServerTool
		u.Type = ChatFunctionToolUnionTypeOpenrouterBash
		return nil
	case "openrouter:datetime":
		datetimeServerTool := new(DatetimeServerTool)
		if err := utils.UnmarshalJSON(data, &datetimeServerTool, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == openrouter:datetime) type DatetimeServerTool within ChatFunctionTool: %w", string(data), err)
		}

		u.DatetimeServerTool = datetimeServerTool
		u.Type = ChatFunctionToolUnionTypeOpenrouterDatetime
		return nil
	case "openrouter:files":
		filesServerTool := new(FilesServerTool)
		if err := utils.UnmarshalJSON(data, &filesServerTool, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == openrouter:files) type FilesServerTool within ChatFunctionTool: %w", string(data), err)
		}

		u.FilesServerTool = filesServerTool
		u.Type = ChatFunctionToolUnionTypeOpenrouterFiles
		return nil
	case "openrouter:fusion":
		fusionServerToolOpenRouter := new(FusionServerToolOpenRouter)
		if err := utils.UnmarshalJSON(data, &fusionServerToolOpenRouter, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == openrouter:fusion) type FusionServerToolOpenRouter within ChatFunctionTool: %w", string(data), err)
		}

		u.FusionServerToolOpenRouter = fusionServerToolOpenRouter
		u.Type = ChatFunctionToolUnionTypeOpenrouterFusion
		return nil
	case "openrouter:image_generation":
		imageGenerationServerToolOpenRouter := new(ImageGenerationServerToolOpenRouter)
		if err := utils.UnmarshalJSON(data, &imageGenerationServerToolOpenRouter, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == openrouter:image_generation) type ImageGenerationServerToolOpenRouter within ChatFunctionTool: %w", string(data), err)
		}

		u.ImageGenerationServerToolOpenRouter = imageGenerationServerToolOpenRouter
		u.Type = ChatFunctionToolUnionTypeOpenrouterImageGeneration
		return nil
	case "openrouter:experimental__search_models":
		chatSearchModelsServerTool := new(ChatSearchModelsServerTool)
		if err := utils.UnmarshalJSON(data, &chatSearchModelsServerTool, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == openrouter:experimental__search_models) type ChatSearchModelsServerTool within ChatFunctionTool: %w", string(data), err)
		}

		u.ChatSearchModelsServerTool = chatSearchModelsServerTool
		u.Type = ChatFunctionToolUnionTypeOpenrouterExperimentalSearchModels
		return nil
	case "openrouter:subagent":
		subagentServerToolOpenRouter := new(SubagentServerToolOpenRouter)
		if err := utils.UnmarshalJSON(data, &subagentServerToolOpenRouter, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == openrouter:subagent) type SubagentServerToolOpenRouter within ChatFunctionTool: %w", string(data), err)
		}

		u.SubagentServerToolOpenRouter = subagentServerToolOpenRouter
		u.Type = ChatFunctionToolUnionTypeOpenrouterSubagent
		return nil
	case "openrouter:web_fetch":
		webFetchServerTool := new(WebFetchServerTool)
		if err := utils.UnmarshalJSON(data, &webFetchServerTool, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == openrouter:web_fetch) type WebFetchServerTool within ChatFunctionTool: %w", string(data), err)
		}

		u.WebFetchServerTool = webFetchServerTool
		u.Type = ChatFunctionToolUnionTypeOpenrouterWebFetch
		return nil
	case "openrouter:web_search":
		openRouterWebSearchServerTool := new(OpenRouterWebSearchServerTool)
		if err := utils.UnmarshalJSON(data, &openRouterWebSearchServerTool, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == openrouter:web_search) type OpenRouterWebSearchServerTool within ChatFunctionTool: %w", string(data), err)
		}

		u.OpenRouterWebSearchServerTool = openRouterWebSearchServerTool
		u.Type = ChatFunctionToolUnionTypeOpenrouterWebSearch
		return nil
	case "web_search":
		chatWebSearchShorthand := new(ChatWebSearchShorthand)
		if err := utils.UnmarshalJSON(data, &chatWebSearchShorthand, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == web_search) type ChatWebSearchShorthand within ChatFunctionTool: %w", string(data), err)
		}

		u.ChatWebSearchShorthand = chatWebSearchShorthand
		u.Type = ChatFunctionToolUnionTypeWebSearch
		return nil
	case "web_search_preview":
		chatWebSearchShorthand := new(ChatWebSearchShorthand)
		if err := utils.UnmarshalJSON(data, &chatWebSearchShorthand, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == web_search_preview) type ChatWebSearchShorthand within ChatFunctionTool: %w", string(data), err)
		}

		u.ChatWebSearchShorthand = chatWebSearchShorthand
		u.Type = ChatFunctionToolUnionTypeWebSearchPreview
		return nil
	case "web_search_preview_2025_03_11":
		chatWebSearchShorthand := new(ChatWebSearchShorthand)
		if err := utils.UnmarshalJSON(data, &chatWebSearchShorthand, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == web_search_preview_2025_03_11) type ChatWebSearchShorthand within ChatFunctionTool: %w", string(data), err)
		}

		u.ChatWebSearchShorthand = chatWebSearchShorthand
		u.Type = ChatFunctionToolUnionTypeWebSearchPreview20250311
		return nil
	case "web_search_2025_08_26":
		chatWebSearchShorthand := new(ChatWebSearchShorthand)
		if err := utils.UnmarshalJSON(data, &chatWebSearchShorthand, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == web_search_2025_08_26) type ChatWebSearchShorthand within ChatFunctionTool: %w", string(data), err)
		}

		u.ChatWebSearchShorthand = chatWebSearchShorthand
		u.Type = ChatFunctionToolUnionTypeWebSearch20250826
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for ChatFunctionTool", string(data))
}

func (u ChatFunctionTool) MarshalJSON() ([]byte, error) {
	if u.ChatFunctionToolFunction != nil {
		return utils.MarshalJSON(u.ChatFunctionToolFunction, "", true)
	}

	if u.AdvisorServerToolOpenRouter != nil {
		return utils.MarshalJSON(u.AdvisorServerToolOpenRouter, "", true)
	}

	if u.BashServerTool != nil {
		return utils.MarshalJSON(u.BashServerTool, "", true)
	}

	if u.DatetimeServerTool != nil {
		return utils.MarshalJSON(u.DatetimeServerTool, "", true)
	}

	if u.FilesServerTool != nil {
		return utils.MarshalJSON(u.FilesServerTool, "", true)
	}

	if u.FusionServerToolOpenRouter != nil {
		return utils.MarshalJSON(u.FusionServerToolOpenRouter, "", true)
	}

	if u.ImageGenerationServerToolOpenRouter != nil {
		return utils.MarshalJSON(u.ImageGenerationServerToolOpenRouter, "", true)
	}

	if u.ChatSearchModelsServerTool != nil {
		return utils.MarshalJSON(u.ChatSearchModelsServerTool, "", true)
	}

	if u.SubagentServerToolOpenRouter != nil {
		return utils.MarshalJSON(u.SubagentServerToolOpenRouter, "", true)
	}

	if u.WebFetchServerTool != nil {
		return utils.MarshalJSON(u.WebFetchServerTool, "", true)
	}

	if u.OpenRouterWebSearchServerTool != nil {
		return utils.MarshalJSON(u.OpenRouterWebSearchServerTool, "", true)
	}

	if u.ChatWebSearchShorthand != nil {
		return utils.MarshalJSON(u.ChatWebSearchShorthand, "", true)
	}

	return nil, errors.New("could not marshal union type ChatFunctionTool: all fields are null")
}
