// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
)

type CodeInterpreterImageOutput struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_ string `const:"image" json:"type"`
	URL   string `json:"url"`
}

func (c CodeInterpreterImageOutput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CodeInterpreterImageOutput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CodeInterpreterImageOutput) GetType() string {
	return "image"
}

func (c *CodeInterpreterImageOutput) GetURL() string {
	if c == nil {
		return ""
	}
	return c.URL
}
