// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
)

type CompoundFilterType string

const (
	CompoundFilterTypeAnd CompoundFilterType = "and"
	CompoundFilterTypeOr  CompoundFilterType = "or"
)

func (e CompoundFilterType) ToPointer() *CompoundFilterType {
	return &e
}
func (e *CompoundFilterType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "and":
		fallthrough
	case "or":
		*e = CompoundFilterType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CompoundFilterType: %v", v)
	}
}

// CompoundFilter - A compound filter that combines multiple comparison or compound filters
type CompoundFilter struct {
	Filters []map[string]any   `json:"filters"`
	Type    CompoundFilterType `json:"type"`
}

func (c CompoundFilter) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CompoundFilter) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CompoundFilter) GetFilters() []map[string]any {
	if c == nil {
		return []map[string]any{}
	}
	return c.Filters
}

func (c *CompoundFilter) GetType() CompoundFilterType {
	if c == nil {
		return CompoundFilterType("")
	}
	return c.Type
}
