// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 8ee7aa3981c2

package shared

// ContentFilterEntry - A custom regex content filter that scans request messages for matching patterns.
type ContentFilterEntry struct {
	// Action taken when the pattern matches
	Action ContentFilterAction `json:"action"`
	// Optional label used in redaction placeholders or error messages
	Label *string `json:"label,omitzero"`
	// A regex pattern to match against request content
	Pattern string `json:"pattern"`
}

func (c *ContentFilterEntry) GetAction() ContentFilterAction {
	if c == nil {
		return ContentFilterAction("")
	}
	return c.Action
}

func (c *ContentFilterEntry) GetLabel() *string {
	if c == nil {
		return nil
	}
	return c.Label
}

func (c *ContentFilterEntry) GetPattern() string {
	if c == nil {
		return ""
	}
	return c.Pattern
}
