// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
)

type ContextCompressionPlugin struct {
	// Set to false to disable the context-compression plugin for this request. Defaults to true.
	Enabled *bool `json:"enabled,omitzero"`
	// The compression engine to use. Defaults to "middle-out".
	Engine *ContextCompressionEngine `json:"engine,omitzero"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	id string `const:"context-compression" json:"id"`
}

func (c ContextCompressionPlugin) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ContextCompressionPlugin) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ContextCompressionPlugin) GetEnabled() *bool {
	if c == nil {
		return nil
	}
	return c.Enabled
}

func (c *ContextCompressionPlugin) GetEngine() *ContextCompressionEngine {
	if c == nil {
		return nil
	}
	return c.Engine
}

func (c *ContextCompressionPlugin) GetID() string {
	return "context-compression"
}
