// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/openrouter/terraform-provider-openrouter/internal/sdk/internal/utils"
)

type ContentPartInputVideo struct {
	InputVideo MultimodalMedia `json:"input_video"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_ string `const:"input_video" json:"type"`
}

func (c ContentPartInputVideo) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ContentPartInputVideo) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ContentPartInputVideo) GetInputVideo() MultimodalMedia {
	if c == nil {
		return MultimodalMedia{}
	}
	return c.InputVideo
}

func (c *ContentPartInputVideo) GetType() string {
	return "input_video"
}
