// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
)

type ContentPartInputAudio struct {
	InputAudio MultimodalMedia `json:"input_audio"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_ string `const:"input_audio" json:"type"`
}

func (c ContentPartInputAudio) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ContentPartInputAudio) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ContentPartInputAudio) GetInputAudio() MultimodalMedia {
	if c == nil {
		return MultimodalMedia{}
	}
	return c.InputAudio
}

func (c *ContentPartInputAudio) GetType() string {
	return "input_audio"
}
