// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// ContentFilterAction - Action taken when the pattern matches
type ContentFilterAction string

const (
	ContentFilterActionRedact ContentFilterAction = "redact"
	ContentFilterActionBlock  ContentFilterAction = "block"
)

func (e ContentFilterAction) ToPointer() *ContentFilterAction {
	return &e
}
func (e *ContentFilterAction) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "redact":
		fallthrough
	case "block":
		*e = ContentFilterAction(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ContentFilterAction: %v", v)
	}
}
