// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 446644b46aa9

package shared

import (
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
)

type ContentPartImageImageURL struct {
	URL string `json:"url"`
}

func (c ContentPartImageImageURL) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ContentPartImageImageURL) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ContentPartImageImageURL) GetURL() string {
	if c == nil {
		return ""
	}
	return c.URL
}

type ContentPartImage struct {
	ImageURL ContentPartImageImageURL `json:"image_url"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_ string `const:"image_url" json:"type"`
}

func (c ContentPartImage) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ContentPartImage) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ContentPartImage) GetImageURL() ContentPartImageImageURL {
	if c == nil {
		return ContentPartImageImageURL{}
	}
	return c.ImageURL
}

func (c *ContentPartImage) GetType() string {
	return "image_url"
}
