// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CreateScimGroupMappingResponse struct {
	Data ScimGroupMapping `json:"data"`
}

func (c *CreateScimGroupMappingResponse) GetData() ScimGroupMapping {
	if c == nil {
		return ScimGroupMapping{}
	}
	return c.Data
}
