// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
)

// CreateGuardrailResponseData - The created guardrail
type CreateGuardrailResponseData struct {
	// Array of model canonical_slugs (immutable identifiers)
	AllowedModels []string `json:"allowed_models,omitzero"`
	// List of allowed provider IDs
	AllowedProviders []string `json:"allowed_providers,omitzero"`
	// Builtin content filters applied to requests. Includes PII detectors and the regex-based prompt injection detector.
	ContentFilterBuiltins []ContentFilterBuiltinEntry `json:"content_filter_builtins,omitzero"`
	// Custom regex content filters applied to request messages
	ContentFilters []ContentFilterEntry `json:"content_filters,omitzero"`
	// ISO 8601 timestamp of when the guardrail was created
	CreatedAt string `json:"created_at"`
	// Description of the guardrail
	Description *string `json:"description,omitzero"`
	// Deprecated. Use enforce_zdr_anthropic, enforce_zdr_openai, enforce_zdr_google, enforce_zdr_xai, and enforce_zdr_other instead. When provided, its value is copied into any of those per-provider fields that are not explicitly specified on the request.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	EnforceZdr *bool `json:"enforce_zdr,omitzero"`
	// Whether to enforce zero data retention for Anthropic models. Falls back to enforce_zdr when not provided.
	EnforceZdrAnthropic *bool `json:"enforce_zdr_anthropic,omitzero"`
	// Whether to enforce zero data retention for Google models. Falls back to enforce_zdr when not provided.
	EnforceZdrGoogle *bool `json:"enforce_zdr_google,omitzero"`
	// Whether to enforce zero data retention for OpenAI models. Falls back to enforce_zdr when not provided.
	EnforceZdrOpenai *bool `json:"enforce_zdr_openai,omitzero"`
	// Whether to enforce zero data retention for models that are not from Anthropic, OpenAI, Google, or xAI. Falls back to enforce_zdr when not provided.
	EnforceZdrOther *bool `json:"enforce_zdr_other,omitzero"`
	// Whether to enforce zero data retention for xAI models. Falls back to enforce_zdr when not provided.
	EnforceZdrXai *bool `json:"enforce_zdr_xai,omitzero"`
	// Unique identifier for the guardrail
	ID string `json:"id"`
	// Array of model canonical_slugs to exclude from routing
	IgnoredModels []string `json:"ignored_models,omitzero"`
	// List of provider IDs to exclude from routing
	IgnoredProviders []string `json:"ignored_providers,omitzero"`
	// Spending limit in USD
	LimitUsd *float64 `json:"limit_usd,omitzero"`
	// Name of the guardrail
	Name string `json:"name"`
	// Interval at which the limit resets (daily, weekly, monthly)
	ResetInterval *GuardrailInterval `json:"reset_interval,omitzero"`
	// ISO 8601 timestamp of when the guardrail was last updated
	UpdatedAt *string `json:"updated_at,omitzero"`
	// The workspace ID this guardrail belongs to.
	WorkspaceID string `json:"workspace_id"`
}

func (c CreateGuardrailResponseData) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateGuardrailResponseData) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateGuardrailResponseData) GetAllowedModels() []string {
	if c == nil {
		return nil
	}
	return c.AllowedModels
}

func (c *CreateGuardrailResponseData) GetAllowedProviders() []string {
	if c == nil {
		return nil
	}
	return c.AllowedProviders
}

func (c *CreateGuardrailResponseData) GetContentFilterBuiltins() []ContentFilterBuiltinEntry {
	if c == nil {
		return nil
	}
	return c.ContentFilterBuiltins
}

func (c *CreateGuardrailResponseData) GetContentFilters() []ContentFilterEntry {
	if c == nil {
		return nil
	}
	return c.ContentFilters
}

func (c *CreateGuardrailResponseData) GetCreatedAt() string {
	if c == nil {
		return ""
	}
	return c.CreatedAt
}

func (c *CreateGuardrailResponseData) GetDescription() *string {
	if c == nil {
		return nil
	}
	return c.Description
}

func (c *CreateGuardrailResponseData) GetEnforceZdr() *bool {
	if c == nil {
		return nil
	}
	return c.EnforceZdr
}

func (c *CreateGuardrailResponseData) GetEnforceZdrAnthropic() *bool {
	if c == nil {
		return nil
	}
	return c.EnforceZdrAnthropic
}

func (c *CreateGuardrailResponseData) GetEnforceZdrGoogle() *bool {
	if c == nil {
		return nil
	}
	return c.EnforceZdrGoogle
}

func (c *CreateGuardrailResponseData) GetEnforceZdrOpenai() *bool {
	if c == nil {
		return nil
	}
	return c.EnforceZdrOpenai
}

func (c *CreateGuardrailResponseData) GetEnforceZdrOther() *bool {
	if c == nil {
		return nil
	}
	return c.EnforceZdrOther
}

func (c *CreateGuardrailResponseData) GetEnforceZdrXai() *bool {
	if c == nil {
		return nil
	}
	return c.EnforceZdrXai
}

func (c *CreateGuardrailResponseData) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CreateGuardrailResponseData) GetIgnoredModels() []string {
	if c == nil {
		return nil
	}
	return c.IgnoredModels
}

func (c *CreateGuardrailResponseData) GetIgnoredProviders() []string {
	if c == nil {
		return nil
	}
	return c.IgnoredProviders
}

func (c *CreateGuardrailResponseData) GetLimitUsd() *float64 {
	if c == nil {
		return nil
	}
	return c.LimitUsd
}

func (c *CreateGuardrailResponseData) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateGuardrailResponseData) GetResetInterval() *GuardrailInterval {
	if c == nil {
		return nil
	}
	return c.ResetInterval
}

func (c *CreateGuardrailResponseData) GetUpdatedAt() *string {
	if c == nil {
		return nil
	}
	return c.UpdatedAt
}

func (c *CreateGuardrailResponseData) GetWorkspaceID() string {
	if c == nil {
		return ""
	}
	return c.WorkspaceID
}

type CreateGuardrailResponse struct {
	Data CreateGuardrailResponseData `json:"data"`
}

func (c *CreateGuardrailResponse) GetData() CreateGuardrailResponseData {
	if c == nil {
		return CreateGuardrailResponseData{}
	}
	return c.Data
}
