// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy/terraform-provider-openrouter/internal/sdk/internal/utils"
)

type CreateWorkspaceRequest struct {
	// Default image model for this workspace
	DefaultImageModel *string `json:"default_image_model,omitzero"`
	// Default provider sort preference (price, throughput, latency, exacto)
	DefaultProviderSort *string `json:"default_provider_sort,omitzero"`
	// Default text model for this workspace
	DefaultTextModel *string `json:"default_text_model,omitzero"`
	// Description of the workspace
	Description *string `json:"description,omitzero"`
	// Optional array of API key IDs to filter I/O logging
	IoLoggingAPIKeyIds []int64 `json:"io_logging_api_key_ids,omitzero"`
	// Sampling rate for I/O logging (0.0001-1)
	IoLoggingSamplingRate *float64 `json:"io_logging_sampling_rate,omitzero"`
	// Whether data discount logging is enabled
	IsDataDiscountLoggingEnabled *bool `json:"is_data_discount_logging_enabled,omitzero"`
	// Whether broadcast is enabled
	IsObservabilityBroadcastEnabled *bool `json:"is_observability_broadcast_enabled,omitzero"`
	// Whether private logging is enabled
	IsObservabilityIoLoggingEnabled *bool `json:"is_observability_io_logging_enabled,omitzero"`
	// Name for the new workspace
	Name string `json:"name"`
	// URL-friendly slug (lowercase alphanumeric segments separated by single hyphens, no leading/trailing hyphens)
	Slug string `json:"slug"`
}

func (c CreateWorkspaceRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateWorkspaceRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateWorkspaceRequest) GetDefaultImageModel() *string {
	if c == nil {
		return nil
	}
	return c.DefaultImageModel
}

func (c *CreateWorkspaceRequest) GetDefaultProviderSort() *string {
	if c == nil {
		return nil
	}
	return c.DefaultProviderSort
}

func (c *CreateWorkspaceRequest) GetDefaultTextModel() *string {
	if c == nil {
		return nil
	}
	return c.DefaultTextModel
}

func (c *CreateWorkspaceRequest) GetDescription() *string {
	if c == nil {
		return nil
	}
	return c.Description
}

func (c *CreateWorkspaceRequest) GetIoLoggingAPIKeyIds() []int64 {
	if c == nil {
		return nil
	}
	return c.IoLoggingAPIKeyIds
}

func (c *CreateWorkspaceRequest) GetIoLoggingSamplingRate() *float64 {
	if c == nil {
		return nil
	}
	return c.IoLoggingSamplingRate
}

func (c *CreateWorkspaceRequest) GetIsDataDiscountLoggingEnabled() *bool {
	if c == nil {
		return nil
	}
	return c.IsDataDiscountLoggingEnabled
}

func (c *CreateWorkspaceRequest) GetIsObservabilityBroadcastEnabled() *bool {
	if c == nil {
		return nil
	}
	return c.IsObservabilityBroadcastEnabled
}

func (c *CreateWorkspaceRequest) GetIsObservabilityIoLoggingEnabled() *bool {
	if c == nil {
		return nil
	}
	return c.IsObservabilityIoLoggingEnabled
}

func (c *CreateWorkspaceRequest) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateWorkspaceRequest) GetSlug() string {
	if c == nil {
		return ""
	}
	return c.Slug
}
