// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
)

// DatetimeServerToolConfig - Configuration for the openrouter:datetime server tool
type DatetimeServerToolConfig struct {
	// IANA timezone name (e.g. "America/New_York"). Defaults to UTC.
	Timezone *string `json:"timezone,omitzero"`
}

func (d DatetimeServerToolConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DatetimeServerToolConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DatetimeServerToolConfig) GetTimezone() *string {
	if d == nil {
		return nil
	}
	return d.Timezone
}
