// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 28820f50ef6f

package shared

import (
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
)

type DecisionsChoiceQuestion struct {
	Criteria     map[string]string `json:"criteria"`
	Instructions string            `json:"instructions"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_ string `const:"choice" json:"type"`
}

func (d DecisionsChoiceQuestion) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DecisionsChoiceQuestion) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DecisionsChoiceQuestion) GetCriteria() map[string]string {
	if d == nil {
		return map[string]string{}
	}
	return d.Criteria
}

func (d *DecisionsChoiceQuestion) GetInstructions() string {
	if d == nil {
		return ""
	}
	return d.Instructions
}

func (d *DecisionsChoiceQuestion) GetType() string {
	return "choice"
}
