// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: ea24f72db3bd

package shared

import (
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
)

type DeleteScimGroupMappingResponse struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	deleted bool `const:"true" json:"deleted"`
}

func (d DeleteScimGroupMappingResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteScimGroupMappingResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeleteScimGroupMappingResponse) GetDeleted() bool {
	return true
}
