// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
)

type FileResponseType string

const (
	FileResponseTypeAnthropic  FileResponseType = "anthropic"
	FileResponseTypeOpenai     FileResponseType = "openai"
	FileResponseTypeOpenrouter FileResponseType = "openrouter"
)

// FileResponse - A stored file. The shape is negotiated per request — see the endpoint description.
type FileResponse struct {
	OpenRouterFile *OpenRouterFile `queryParam:"inline" union:"member"`
	OpenAIFile     *OpenAIFile     `queryParam:"inline" union:"member"`
	AnthropicFile  *AnthropicFile  `queryParam:"inline" union:"member"`

	Type FileResponseType
}

func CreateFileResponseAnthropic(anthropic AnthropicFile) FileResponse {
	typ := FileResponseTypeAnthropic

	typStr := AnthropicFileShape(typ)
	anthropic.Shape = typStr

	return FileResponse{
		AnthropicFile: &anthropic,
		Type:          typ,
	}
}

func CreateFileResponseOpenai(openai OpenAIFile) FileResponse {
	typ := FileResponseTypeOpenai

	typStr := OpenAIFileShape(typ)
	openai.Shape = typStr

	return FileResponse{
		OpenAIFile: &openai,
		Type:       typ,
	}
}

func CreateFileResponseOpenrouter(openrouter OpenRouterFile) FileResponse {
	typ := FileResponseTypeOpenrouter

	typStr := OpenRouterFileShape(typ)
	openrouter.Shape = typStr

	return FileResponse{
		OpenRouterFile: &openrouter,
		Type:           typ,
	}
}

func (u *FileResponse) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Shape string `json:"_shape"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.Shape {
	case "anthropic":
		anthropicFile := new(AnthropicFile)
		if err := utils.UnmarshalJSON(data, &anthropicFile, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Shape == anthropic) type AnthropicFile within FileResponse: %w", string(data), err)
		}

		u.AnthropicFile = anthropicFile
		u.Type = FileResponseTypeAnthropic
		return nil
	case "openai":
		openAIFile := new(OpenAIFile)
		if err := utils.UnmarshalJSON(data, &openAIFile, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Shape == openai) type OpenAIFile within FileResponse: %w", string(data), err)
		}

		u.OpenAIFile = openAIFile
		u.Type = FileResponseTypeOpenai
		return nil
	case "openrouter":
		openRouterFile := new(OpenRouterFile)
		if err := utils.UnmarshalJSON(data, &openRouterFile, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Shape == openrouter) type OpenRouterFile within FileResponse: %w", string(data), err)
		}

		u.OpenRouterFile = openRouterFile
		u.Type = FileResponseTypeOpenrouter
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for FileResponse", string(data))
}

func (u FileResponse) MarshalJSON() ([]byte, error) {
	if u.OpenRouterFile != nil {
		return utils.MarshalJSON(u.OpenRouterFile, "", true)
	}

	if u.OpenAIFile != nil {
		return utils.MarshalJSON(u.OpenAIFile, "", true)
	}

	if u.AnthropicFile != nil {
		return utils.MarshalJSON(u.AnthropicFile, "", true)
	}

	return nil, errors.New("could not marshal union type FileResponse: all fields are null")
}
