// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy/terraform-provider-openrouter/internal/sdk/internal/utils"
)

type FileCitation struct {
	FileID   string `json:"file_id"`
	Filename string `json:"filename"`
	Index    int64  `json:"index"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_ string `const:"file_citation" json:"type"`
}

func (f FileCitation) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FileCitation) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FileCitation) GetFileID() string {
	if f == nil {
		return ""
	}
	return f.FileID
}

func (f *FileCitation) GetFilename() string {
	if f == nil {
		return ""
	}
	return f.Filename
}

func (f *FileCitation) GetIndex() int64 {
	if f == nil {
		return 0
	}
	return f.Index
}

func (f *FileCitation) GetType() string {
	return "file_citation"
}
