// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type FrameImageImageURL struct {
	URL string `json:"url"`
}

func (f *FrameImageImageURL) GetURL() string {
	if f == nil {
		return ""
	}
	return f.URL
}

type FrameImageType string

const (
	FrameImageTypeImageURL FrameImageType = "image_url"
)

func (e FrameImageType) ToPointer() *FrameImageType {
	return &e
}
func (e *FrameImageType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "image_url":
		*e = FrameImageType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FrameImageType: %v", v)
	}
}

// FrameType - Whether this image represents the first or last frame of the video
type FrameType string

const (
	FrameTypeFirstFrame FrameType = "first_frame"
	FrameTypeLastFrame  FrameType = "last_frame"
)

func (e FrameType) ToPointer() *FrameType {
	return &e
}
func (e *FrameType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "first_frame":
		fallthrough
	case "last_frame":
		*e = FrameType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FrameType: %v", v)
	}
}

type FrameImage struct {
	ImageURL FrameImageImageURL `json:"image_url"`
	Type     FrameImageType     `json:"type"`
	// Whether this image represents the first or last frame of the video
	FrameType FrameType `json:"frame_type"`
}

func (f *FrameImage) GetImageURL() FrameImageImageURL {
	if f == nil {
		return FrameImageImageURL{}
	}
	return f.ImageURL
}

func (f *FrameImage) GetType() FrameImageType {
	if f == nil {
		return FrameImageType("")
	}
	return f.Type
}

func (f *FrameImage) GetFrameType() FrameType {
	if f == nil {
		return FrameType("")
	}
	return f.FrameType
}
