// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
)

// FusionSource - A web page retrieved via web search during a fusion run.
type FusionSource struct {
	// Title of the retrieved web page.
	Title string `json:"title"`
	// URL of the web page a panel or the analyst retrieved during the run.
	URL string `json:"url"`
}

func (f FusionSource) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FusionSource) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FusionSource) GetTitle() string {
	if f == nil {
		return ""
	}
	return f.Title
}

func (f *FusionSource) GetURL() string {
	if f == nil {
		return ""
	}
	return f.URL
}
