// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type ImageOutputModality string

const (
	ImageOutputModalityText          ImageOutputModality = "text"
	ImageOutputModalityImage         ImageOutputModality = "image"
	ImageOutputModalityEmbeddings    ImageOutputModality = "embeddings"
	ImageOutputModalityAudio         ImageOutputModality = "audio"
	ImageOutputModalityVideo         ImageOutputModality = "video"
	ImageOutputModalityRerank        ImageOutputModality = "rerank"
	ImageOutputModalitySpeech        ImageOutputModality = "speech"
	ImageOutputModalityTranscription ImageOutputModality = "transcription"
)

func (e ImageOutputModality) ToPointer() *ImageOutputModality {
	return &e
}
func (e *ImageOutputModality) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "text":
		fallthrough
	case "image":
		fallthrough
	case "embeddings":
		fallthrough
	case "audio":
		fallthrough
	case "video":
		fallthrough
	case "rerank":
		fallthrough
	case "speech":
		fallthrough
	case "transcription":
		*e = ImageOutputModality(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ImageOutputModality: %v", v)
	}
}
