// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: b0988774f372

package shared

// ImageModelListItem - A single image model in the discovery listing.
type ImageModelListItem struct {
	Architecture ImageModelArchitecture `json:"architecture"`
	// Unix timestamp (seconds) of when the model was created
	Created     int64  `json:"created"`
	Description string `json:"description"`
	// Relative URL to the full per-endpoint records for this model
	Endpoints string `json:"endpoints"`
	// Model slug
	ID string `json:"id"`
	// Display name
	Name string `json:"name"`
	// Union of supported parameters across every endpoint of this model. Coarse discovery aid; the definitive per-endpoint set is behind the endpoints URL.
	SupportedParameters map[string]CapabilityDescriptor `json:"supported_parameters"`
	// Whether any endpoint of this model supports native SSE streaming on the dedicated Image API (i.e. `stream: true` in the request). OR across endpoints.
	SupportsStreaming bool `json:"supports_streaming"`
}

func (i *ImageModelListItem) GetArchitecture() ImageModelArchitecture {
	if i == nil {
		return ImageModelArchitecture{}
	}
	return i.Architecture
}

func (i *ImageModelListItem) GetCreated() int64 {
	if i == nil {
		return 0
	}
	return i.Created
}

func (i *ImageModelListItem) GetDescription() string {
	if i == nil {
		return ""
	}
	return i.Description
}

func (i *ImageModelListItem) GetEndpoints() string {
	if i == nil {
		return ""
	}
	return i.Endpoints
}

func (i *ImageModelListItem) GetID() string {
	if i == nil {
		return ""
	}
	return i.ID
}

func (i *ImageModelListItem) GetName() string {
	if i == nil {
		return ""
	}
	return i.Name
}

func (i *ImageModelListItem) GetSupportedParameters() map[string]CapabilityDescriptor {
	if i == nil {
		return map[string]CapabilityDescriptor{}
	}
	return i.SupportedParameters
}

func (i *ImageModelListItem) GetSupportsStreaming() bool {
	if i == nil {
		return false
	}
	return i.SupportsStreaming
}
