// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: d00faf933227

package shared

import (
	"encoding/json"
	"fmt"
)

type Billable string

const (
	BillableOutputImage    Billable = "output_image"
	BillableInputImage     Billable = "input_image"
	BillableInputFont      Billable = "input_font"
	BillableInputReference Billable = "input_reference"
	BillableInputText      Billable = "input_text"
)

func (e Billable) ToPointer() *Billable {
	return &e
}
func (e *Billable) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "output_image":
		fallthrough
	case "input_image":
		fallthrough
	case "input_font":
		fallthrough
	case "input_reference":
		fallthrough
	case "input_text":
		*e = Billable(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Billable: %v", v)
	}
}

type Unit string

const (
	UnitImage     Unit = "image"
	UnitMegapixel Unit = "megapixel"
	UnitToken     Unit = "token"
)

func (e Unit) ToPointer() *Unit {
	return &e
}
func (e *Unit) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "image":
		fallthrough
	case "megapixel":
		fallthrough
	case "token":
		*e = Unit(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Unit: %v", v)
	}
}

// ImagePricingEntry - One billable pricing line for an image provider.
type ImagePricingEntry struct {
	Billable Billable `json:"billable"`
	CostUsd  float64  `json:"cost_usd"`
	Unit     Unit     `json:"unit"`
	Variant  *string  `json:"variant,omitzero"`
}

func (i *ImagePricingEntry) GetBillable() Billable {
	if i == nil {
		return Billable("")
	}
	return i.Billable
}

func (i *ImagePricingEntry) GetCostUsd() float64 {
	if i == nil {
		return 0.0
	}
	return i.CostUsd
}

func (i *ImagePricingEntry) GetUnit() Unit {
	if i == nil {
		return Unit("")
	}
	return i.Unit
}

func (i *ImagePricingEntry) GetVariant() *string {
	if i == nil {
		return nil
	}
	return i.Variant
}
