// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
)

type FormatEnum string

const (
	FormatEnumMp3 FormatEnum = "mp3"
	FormatEnumWav FormatEnum = "wav"
)

func (e FormatEnum) ToPointer() *FormatEnum {
	return &e
}
func (e *FormatEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "mp3":
		fallthrough
	case "wav":
		*e = FormatEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FormatEnum: %v", v)
	}
}

type InputAudioInputAudio struct {
	Data   string     `json:"data"`
	Format FormatEnum `json:"format"`
}

func (i InputAudioInputAudio) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InputAudioInputAudio) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InputAudioInputAudio) GetData() string {
	if i == nil {
		return ""
	}
	return i.Data
}

func (i *InputAudioInputAudio) GetFormat() FormatEnum {
	if i == nil {
		return FormatEnum("")
	}
	return i.Format
}

// InputAudio - Audio input content item
type InputAudio struct {
	InputAudio InputAudioInputAudio `json:"input_audio"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_ string `const:"input_audio" json:"type"`
}

func (i InputAudio) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InputAudio) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InputAudio) GetInputAudio() InputAudioInputAudio {
	if i == nil {
		return InputAudioInputAudio{}
	}
	return i.InputAudio
}

func (i *InputAudio) GetType() string {
	return "input_audio"
}
