// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy/terraform-provider-openrouter/internal/sdk/internal/utils"
)

// InternalServerResponse - Internal Server Error - Unexpected server error
type InternalServerResponse struct {
	// Error data for InternalServerResponse
	Error              InternalServerResponseErrorData `json:"error"`
	OpenrouterMetadata map[string]any                  `json:"openrouter_metadata,omitzero"`
	UserID             *string                         `json:"user_id,omitzero"`
}

func (i InternalServerResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InternalServerResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InternalServerResponse) GetError() InternalServerResponseErrorData {
	if i == nil {
		return InternalServerResponseErrorData{}
	}
	return i.Error
}

func (i *InternalServerResponse) GetOpenrouterMetadata() map[string]any {
	if i == nil {
		return nil
	}
	return i.OpenrouterMetadata
}

func (i *InternalServerResponse) GetUserID() *string {
	if i == nil {
		return nil
	}
	return i.UserID
}
