// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: bb9acac4f74a

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
	"time"
)

// KeyBudgetResetInterval - UTC window the spend is counted over (weeks start Monday); null for a lifetime budget that never resets.
type KeyBudgetResetInterval string

const (
	KeyBudgetResetIntervalDaily   KeyBudgetResetInterval = "daily"
	KeyBudgetResetIntervalWeekly  KeyBudgetResetInterval = "weekly"
	KeyBudgetResetIntervalMonthly KeyBudgetResetInterval = "monthly"
)

func (e KeyBudgetResetInterval) ToPointer() *KeyBudgetResetInterval {
	return &e
}
func (e *KeyBudgetResetInterval) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "daily":
		fallthrough
	case "weekly":
		fallthrough
	case "monthly":
		*e = KeyBudgetResetInterval(v)
		return nil
	default:
		return fmt.Errorf("invalid value for KeyBudgetResetInterval: %v", v)
	}
}

// KeyBudgetScope - Which budget layer this is, in the order enforcement checks them: the workspace default guardrail against the member aggregate (`workspace_default_member`) and against this key (`workspace_default_key`), the member guardrail (`member`), the API key guardrail (`api_key`), a workspace budget (`workspace`), or the key's own limit (`key_limit`).
type KeyBudgetScope string

const (
	KeyBudgetScopeWorkspaceDefaultMember KeyBudgetScope = "workspace_default_member"
	KeyBudgetScopeWorkspaceDefaultKey    KeyBudgetScope = "workspace_default_key"
	KeyBudgetScopeMember                 KeyBudgetScope = "member"
	KeyBudgetScopeAPIKey                 KeyBudgetScope = "api_key"
	KeyBudgetScopeWorkspace              KeyBudgetScope = "workspace"
	KeyBudgetScopeKeyLimit               KeyBudgetScope = "key_limit"
)

func (e KeyBudgetScope) ToPointer() *KeyBudgetScope {
	return &e
}
func (e *KeyBudgetScope) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "workspace_default_member":
		fallthrough
	case "workspace_default_key":
		fallthrough
	case "member":
		fallthrough
	case "api_key":
		fallthrough
	case "workspace":
		fallthrough
	case "key_limit":
		*e = KeyBudgetScope(v)
		return nil
	default:
		return fmt.Errorf("invalid value for KeyBudgetScope: %v", v)
	}
}

// KeyBudget - One budget layer that applies to requests made with this key, with the spend enforcement compares against it.
type KeyBudget struct {
	// ID of the workspace budget for the `workspace` scope; null for other scopes.
	BudgetID *string `json:"budget_id"`
	// ID of the guardrail that carries this budget; null for other scopes.
	GuardrailID *string `json:"guardrail_id"`
	// Whether external BYOK inference spend counts toward this budget.
	IncludeByok bool `json:"include_byok"`
	// Budget limit in USD for the current window.
	LimitUsd float64 `json:"limit_usd"`
	// `limit_usd - spend_usd`. Zero or negative means this layer rejects requests with a 403 until it resets.
	RemainingUsd float64 `json:"remaining_usd"`
	// UTC window the spend is counted over (weeks start Monday); null for a lifetime budget that never resets.
	ResetInterval *KeyBudgetResetInterval `json:"reset_interval"`
	// ISO 8601 UTC instant at which the window rolls over and spend returns to zero; null for a lifetime budget.
	ResetsAt *time.Time `json:"resets_at"`
	// Which budget layer this is, in the order enforcement checks them: the workspace default guardrail against the member aggregate (`workspace_default_member`) and against this key (`workspace_default_key`), the member guardrail (`member`), the API key guardrail (`api_key`), a workspace budget (`workspace`), or the key's own limit (`key_limit`).
	Scope KeyBudgetScope `json:"scope"`
	// Spend in USD that enforcement counts against this limit in the current window: the member aggregate for member-scoped layers, otherwise this key or workspace.
	SpendUsd float64 `json:"spend_usd"`
}

func (k KeyBudget) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(k, "", false)
}

func (k *KeyBudget) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &k, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (k *KeyBudget) GetBudgetID() *string {
	if k == nil {
		return nil
	}
	return k.BudgetID
}

func (k *KeyBudget) GetGuardrailID() *string {
	if k == nil {
		return nil
	}
	return k.GuardrailID
}

func (k *KeyBudget) GetIncludeByok() bool {
	if k == nil {
		return false
	}
	return k.IncludeByok
}

func (k *KeyBudget) GetLimitUsd() float64 {
	if k == nil {
		return 0.0
	}
	return k.LimitUsd
}

func (k *KeyBudget) GetRemainingUsd() float64 {
	if k == nil {
		return 0.0
	}
	return k.RemainingUsd
}

func (k *KeyBudget) GetResetInterval() *KeyBudgetResetInterval {
	if k == nil {
		return nil
	}
	return k.ResetInterval
}

func (k *KeyBudget) GetResetsAt() *time.Time {
	if k == nil {
		return nil
	}
	return k.ResetsAt
}

func (k *KeyBudget) GetScope() KeyBudgetScope {
	if k == nil {
		return KeyBudgetScope("")
	}
	return k.Scope
}

func (k *KeyBudget) GetSpendUsd() float64 {
	if k == nil {
		return 0.0
	}
	return k.SpendUsd
}
