// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
)

type LegacyWebSearchServerToolType string

const (
	LegacyWebSearchServerToolTypeWebSearch LegacyWebSearchServerToolType = "web_search"
)

func (e LegacyWebSearchServerToolType) ToPointer() *LegacyWebSearchServerToolType {
	return &e
}
func (e *LegacyWebSearchServerToolType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "web_search":
		*e = LegacyWebSearchServerToolType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for LegacyWebSearchServerToolType: %v", v)
	}
}

// LegacyWebSearchServerTool - Web search tool configuration
type LegacyWebSearchServerTool struct {
	// Which search engine to use. "auto" (default) uses native if the provider supports it, otherwise Exa. "native" forces the provider's built-in search. "exa" forces the Exa search API. "firecrawl" uses Firecrawl (requires BYOK). "parallel" uses the Parallel search API. "perplexity" uses the Perplexity Search API (raw ranked results).
	Engine  *WebSearchEngineEnum   `json:"engine,omitzero"`
	Filters *WebSearchDomainFilter `json:"filters,omitzero"`
	// Maximum number of search results to return per search call. Defaults to 5. Applies to Exa, Firecrawl, Parallel, and Perplexity engines; ignored with native provider search. Perplexity supports a maximum of 20; values above 20 are clamped.
	MaxResults *int64 `json:"max_results,omitzero"`
	// Maximum number of web searches the model may perform in a single request. Once reached, further search calls return an error result instead of executing. Applies to the Exa, Firecrawl, Parallel, and Perplexity engines. With native provider search, forwarded only to Anthropic (as `max_uses`); other native search providers have no equivalent parameter and ignore it.
	MaxUses *int64 `json:"max_uses,omitzero"`
	// Engine-native search mode. Exa supports instant, fast, auto (default), deep-lite, deep, and deep-reasoning. Parallel supports turbo (default), basic, and advanced. Modes unsupported by the selected engine are ignored.
	Mode *WebSearchMode `json:"mode,omitzero"`
	// Size of the search context for web search tools
	SearchContextSize *SearchContextSizeEnum        `json:"search_context_size,omitzero"`
	Type              LegacyWebSearchServerToolType `json:"type"`
	// User location information for web search
	UserLocation *WebSearchUserLocation `json:"user_location,omitzero"`
}

func (l LegacyWebSearchServerTool) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *LegacyWebSearchServerTool) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *LegacyWebSearchServerTool) GetEngine() *WebSearchEngineEnum {
	if l == nil {
		return nil
	}
	return l.Engine
}

func (l *LegacyWebSearchServerTool) GetFilters() *WebSearchDomainFilter {
	if l == nil {
		return nil
	}
	return l.Filters
}

func (l *LegacyWebSearchServerTool) GetMaxResults() *int64 {
	if l == nil {
		return nil
	}
	return l.MaxResults
}

func (l *LegacyWebSearchServerTool) GetMaxUses() *int64 {
	if l == nil {
		return nil
	}
	return l.MaxUses
}

func (l *LegacyWebSearchServerTool) GetMode() *WebSearchMode {
	if l == nil {
		return nil
	}
	return l.Mode
}

func (l *LegacyWebSearchServerTool) GetSearchContextSize() *SearchContextSizeEnum {
	if l == nil {
		return nil
	}
	return l.SearchContextSize
}

func (l *LegacyWebSearchServerTool) GetType() LegacyWebSearchServerToolType {
	if l == nil {
		return LegacyWebSearchServerToolType("")
	}
	return l.Type
}

func (l *LegacyWebSearchServerTool) GetUserLocation() *WebSearchUserLocation {
	if l == nil {
		return nil
	}
	return l.UserLocation
}
