// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
)

type McpListToolsItemTool struct {
	Annotations any            `json:"annotations,omitzero"`
	Description *string        `json:"description,omitzero"`
	InputSchema map[string]any `json:"input_schema"`
	Name        string         `json:"name"`
}

func (m McpListToolsItemTool) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *McpListToolsItemTool) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *McpListToolsItemTool) GetAnnotations() any {
	if m == nil {
		return nil
	}
	return m.Annotations
}

func (m *McpListToolsItemTool) GetDescription() *string {
	if m == nil {
		return nil
	}
	return m.Description
}

func (m *McpListToolsItemTool) GetInputSchema() map[string]any {
	if m == nil {
		return map[string]any{}
	}
	return m.InputSchema
}

func (m *McpListToolsItemTool) GetName() string {
	if m == nil {
		return ""
	}
	return m.Name
}

type McpListToolsItemType string

const (
	McpListToolsItemTypeMcpListTools McpListToolsItemType = "mcp_list_tools"
)

func (e McpListToolsItemType) ToPointer() *McpListToolsItemType {
	return &e
}
func (e *McpListToolsItemType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "mcp_list_tools":
		*e = McpListToolsItemType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for McpListToolsItemType: %v", v)
	}
}

// McpListToolsItem - List of available MCP tools from a server
type McpListToolsItem struct {
	Error       *string                `json:"error,omitzero"`
	ID          string                 `json:"id"`
	ServerLabel string                 `json:"server_label"`
	Tools       []McpListToolsItemTool `json:"tools"`
	Type        McpListToolsItemType   `json:"type"`
}

func (m McpListToolsItem) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *McpListToolsItem) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *McpListToolsItem) GetError() *string {
	if m == nil {
		return nil
	}
	return m.Error
}

func (m *McpListToolsItem) GetID() string {
	if m == nil {
		return ""
	}
	return m.ID
}

func (m *McpListToolsItem) GetServerLabel() string {
	if m == nil {
		return ""
	}
	return m.ServerLabel
}

func (m *McpListToolsItem) GetTools() []McpListToolsItemTool {
	if m == nil {
		return []McpListToolsItemTool{}
	}
	return m.Tools
}

func (m *McpListToolsItem) GetType() McpListToolsItemType {
	if m == nil {
		return McpListToolsItemType("")
	}
	return m.Type
}
