// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: b59518be44d3

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
)

type McpProtocolErrorType string

const (
	McpProtocolErrorTypeMcpProtocolError McpProtocolErrorType = "mcp_protocol_error"
)

func (e McpProtocolErrorType) ToPointer() *McpProtocolErrorType {
	return &e
}
func (e *McpProtocolErrorType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "mcp_protocol_error":
		*e = McpProtocolErrorType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for McpProtocolErrorType: %v", v)
	}
}

// McpProtocolError - The MCP server returned a protocol-level error
type McpProtocolError struct {
	Code    int64                `json:"code"`
	Message string               `json:"message"`
	Type    McpProtocolErrorType `json:"type"`
}

func (m McpProtocolError) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *McpProtocolError) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *McpProtocolError) GetCode() int64 {
	if m == nil {
		return 0
	}
	return m.Code
}

func (m *McpProtocolError) GetMessage() string {
	if m == nil {
		return ""
	}
	return m.Message
}

func (m *McpProtocolError) GetType() McpProtocolErrorType {
	if m == nil {
		return McpProtocolErrorType("")
	}
	return m.Type
}
