// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 2417b39c5b93

package shared

import (
	"errors"
	"fmt"
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
)

type McpToolCallErrorType string

const (
	McpToolCallErrorTypeStr                   McpToolCallErrorType = "str"
	McpToolCallErrorTypeMcpProtocolError      McpToolCallErrorType = "McpProtocolError"
	McpToolCallErrorTypeMcpToolExecutionError McpToolCallErrorType = "McpToolExecutionError"
	McpToolCallErrorTypeMcpHTTPError          McpToolCallErrorType = "McpHttpError"
)

// McpToolCallError - Error from an MCP tool call, either a plain message or a structured error
type McpToolCallError struct {
	Str                   *string                `queryParam:"inline" union:"member"`
	McpProtocolError      *McpProtocolError      `queryParam:"inline" union:"member"`
	McpToolExecutionError *McpToolExecutionError `queryParam:"inline" union:"member"`
	McpHTTPError          *McpHTTPError          `queryParam:"inline" union:"member"`

	Type McpToolCallErrorType
}

func CreateMcpToolCallErrorStr(str string) McpToolCallError {
	typ := McpToolCallErrorTypeStr

	return McpToolCallError{
		Str:  &str,
		Type: typ,
	}
}

func CreateMcpToolCallErrorMcpProtocolError(mcpProtocolError McpProtocolError) McpToolCallError {
	typ := McpToolCallErrorTypeMcpProtocolError

	return McpToolCallError{
		McpProtocolError: &mcpProtocolError,
		Type:             typ,
	}
}

func CreateMcpToolCallErrorMcpToolExecutionError(mcpToolExecutionError McpToolExecutionError) McpToolCallError {
	typ := McpToolCallErrorTypeMcpToolExecutionError

	return McpToolCallError{
		McpToolExecutionError: &mcpToolExecutionError,
		Type:                  typ,
	}
}

func CreateMcpToolCallErrorMcpHTTPError(mcpHTTPError McpHTTPError) McpToolCallError {
	typ := McpToolCallErrorTypeMcpHTTPError

	return McpToolCallError{
		McpHTTPError: &mcpHTTPError,
		Type:         typ,
	}
}

func (u *McpToolCallError) UnmarshalJSON(data []byte) (err error) {
	previous := *u
	*u = McpToolCallError{}
	defer func() {
		if err != nil {
			*u = previous
		}
	}()

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  McpToolCallErrorTypeStr,
			Value: &str,
		})
	}

	var mcpProtocolError McpProtocolError = McpProtocolError{}
	if err := utils.UnmarshalJSON(data, &mcpProtocolError, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  McpToolCallErrorTypeMcpProtocolError,
			Value: &mcpProtocolError,
		})
	}

	var mcpToolExecutionError McpToolExecutionError = McpToolExecutionError{}
	if err := utils.UnmarshalJSON(data, &mcpToolExecutionError, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  McpToolCallErrorTypeMcpToolExecutionError,
			Value: &mcpToolExecutionError,
		})
	}

	var mcpHTTPError McpHTTPError = McpHTTPError{}
	if err := utils.UnmarshalJSON(data, &mcpHTTPError, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  McpToolCallErrorTypeMcpHTTPError,
			Value: &mcpHTTPError,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for McpToolCallError", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for McpToolCallError", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(McpToolCallErrorType)
	switch best.Type {
	case McpToolCallErrorTypeStr:
		u.Str = best.Value.(*string)
		return nil
	case McpToolCallErrorTypeMcpProtocolError:
		u.McpProtocolError = best.Value.(*McpProtocolError)
		return nil
	case McpToolCallErrorTypeMcpToolExecutionError:
		u.McpToolExecutionError = best.Value.(*McpToolExecutionError)
		return nil
	case McpToolCallErrorTypeMcpHTTPError:
		u.McpHTTPError = best.Value.(*McpHTTPError)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for McpToolCallError", string(data))
}

func (u McpToolCallError) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.McpProtocolError != nil {
		return utils.MarshalJSON(u.McpProtocolError, "", true)
	}

	if u.McpToolExecutionError != nil {
		return utils.MarshalJSON(u.McpToolExecutionError, "", true)
	}

	if u.McpHTTPError != nil {
		return utils.MarshalJSON(u.McpHTTPError, "", true)
	}

	return nil, errors.New("could not marshal union type McpToolCallError: all fields are null")
}
