// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: fd49c1025202

package shared

import (
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
)

// MessagesShellToolResultBlock - Output of an `openrouter:shell` call from a prior assistant turn. Accepted on replay and dropped before the provider request — Anthropic has no equivalent block.
type MessagesShellToolResultBlock struct {
	Content   map[string]any `json:"content"`
	ToolUseID string         `json:"tool_use_id"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_ string `const:"openrouter_shell_tool_result" json:"type"`
}

func (m MessagesShellToolResultBlock) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MessagesShellToolResultBlock) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *MessagesShellToolResultBlock) GetContent() map[string]any {
	if m == nil {
		return map[string]any{}
	}
	return m.Content
}

func (m *MessagesShellToolResultBlock) GetToolUseID() string {
	if m == nil {
		return ""
	}
	return m.ToolUseID
}

func (m *MessagesShellToolResultBlock) GetType() string {
	return "openrouter_shell_tool_result"
}
