// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// ModelAliasTarget - Concrete model targeted by this tilde-latest alias, when applicable
type ModelAliasTarget struct {
	// Human-readable name of the concrete model targeted by this alias
	Name string `json:"name"`
	// Routable model ID of the concrete target, matching that model row's id
	Slug string `json:"slug"`
}

func (m *ModelAliasTarget) GetName() string {
	if m == nil {
		return ""
	}
	return m.Name
}

func (m *ModelAliasTarget) GetSlug() string {
	if m == nil {
		return ""
	}
	return m.Slug
}
