// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 79db963b0585

package shared

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
)

type NamespaceToolToolType string

const (
	NamespaceToolToolTypeFunction NamespaceToolToolType = "function"
	NamespaceToolToolTypeCustom   NamespaceToolToolType = "custom"
)

type NamespaceToolTool struct {
	NamespaceFunctionTool *NamespaceFunctionTool `queryParam:"inline" union:"member"`
	CustomTool            *CustomTool            `queryParam:"inline" union:"member"`

	Type NamespaceToolToolType
}

func CreateNamespaceToolToolFunction(function NamespaceFunctionTool) NamespaceToolTool {
	typ := NamespaceToolToolTypeFunction

	return NamespaceToolTool{
		NamespaceFunctionTool: &function,
		Type:                  typ,
	}
}

func CreateNamespaceToolToolCustom(custom CustomTool) NamespaceToolTool {
	typ := NamespaceToolToolTypeCustom

	typStr := CustomToolTypeCustom(typ)
	custom.Type = typStr

	return NamespaceToolTool{
		CustomTool: &custom,
		Type:       typ,
	}
}

func (u *NamespaceToolTool) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Type string `json:"type"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.Type {
	case "function":
		namespaceFunctionTool := new(NamespaceFunctionTool)
		if err := utils.UnmarshalJSON(data, &namespaceFunctionTool, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == function) type NamespaceFunctionTool within NamespaceToolTool: %w", string(data), err)
		}

		u.NamespaceFunctionTool = namespaceFunctionTool
		u.Type = NamespaceToolToolTypeFunction
		return nil
	case "custom":
		customTool := new(CustomTool)
		if err := utils.UnmarshalJSON(data, &customTool, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == custom) type CustomTool within NamespaceToolTool: %w", string(data), err)
		}

		u.CustomTool = customTool
		u.Type = NamespaceToolToolTypeCustom
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for NamespaceToolTool", string(data))
}

func (u NamespaceToolTool) MarshalJSON() ([]byte, error) {
	if u.NamespaceFunctionTool != nil {
		return utils.MarshalJSON(u.NamespaceFunctionTool, "", true)
	}

	if u.CustomTool != nil {
		return utils.MarshalJSON(u.CustomTool, "", true)
	}

	return nil, errors.New("could not marshal union type NamespaceToolTool: all fields are null")
}

type NamespaceToolType string

const (
	NamespaceToolTypeNamespace NamespaceToolType = "namespace"
)

func (e NamespaceToolType) ToPointer() *NamespaceToolType {
	return &e
}
func (e *NamespaceToolType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "namespace":
		*e = NamespaceToolType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for NamespaceToolType: %v", v)
	}
}

// NamespaceTool - Groups function/custom tools under a shared namespace
type NamespaceTool struct {
	Description string              `json:"description"`
	Name        string              `json:"name"`
	Tools       []NamespaceToolTool `json:"tools"`
	Type        NamespaceToolType   `json:"type"`
}

func (n NamespaceTool) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(n, "", false)
}

func (n *NamespaceTool) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &n, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (n *NamespaceTool) GetDescription() string {
	if n == nil {
		return ""
	}
	return n.Description
}

func (n *NamespaceTool) GetName() string {
	if n == nil {
		return ""
	}
	return n.Name
}

func (n *NamespaceTool) GetTools() []NamespaceToolTool {
	if n == nil {
		return []NamespaceToolTool{}
	}
	return n.Tools
}

func (n *NamespaceTool) GetType() NamespaceToolType {
	if n == nil {
		return NamespaceToolType("")
	}
	return n.Type
}
