// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: de288c91bc35

package shared

import (
	"encoding/json"
	"fmt"
)

type ObservabilityDataRegion string

const (
	ObservabilityDataRegionGlobal ObservabilityDataRegion = "global"
	ObservabilityDataRegionEurope ObservabilityDataRegion = "europe"
	ObservabilityDataRegionUs     ObservabilityDataRegion = "us"
)

func (e ObservabilityDataRegion) ToPointer() *ObservabilityDataRegion {
	return &e
}
func (e *ObservabilityDataRegion) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "global":
		fallthrough
	case "europe":
		fallthrough
	case "us":
		*e = ObservabilityDataRegion(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ObservabilityDataRegion: %v", v)
	}
}
