// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: dea9035851c1

package shared

import (
	"encoding/json"
	"fmt"
)

// ObservabilityDataRegionInput - `eu` is accepted as an alias for `europe` and normalizes to `europe`.
type ObservabilityDataRegionInput string

const (
	ObservabilityDataRegionInputGlobal ObservabilityDataRegionInput = "global"
	ObservabilityDataRegionInputEurope ObservabilityDataRegionInput = "europe"
	ObservabilityDataRegionInputUs     ObservabilityDataRegionInput = "us"
	ObservabilityDataRegionInputEu     ObservabilityDataRegionInput = "eu"
)

func (e ObservabilityDataRegionInput) ToPointer() *ObservabilityDataRegionInput {
	return &e
}
func (e *ObservabilityDataRegionInput) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "global":
		fallthrough
	case "europe":
		fallthrough
	case "us":
		fallthrough
	case "eu":
		*e = ObservabilityDataRegionInput(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ObservabilityDataRegionInput: %v", v)
	}
}
