// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 552307fd0099

package shared

import (
	"encoding/json"
	"fmt"
)

type OpenAIResponsesResponseStatus string

const (
	OpenAIResponsesResponseStatusCompleted  OpenAIResponsesResponseStatus = "completed"
	OpenAIResponsesResponseStatusIncomplete OpenAIResponsesResponseStatus = "incomplete"
	OpenAIResponsesResponseStatusInProgress OpenAIResponsesResponseStatus = "in_progress"
	OpenAIResponsesResponseStatusFailed     OpenAIResponsesResponseStatus = "failed"
	OpenAIResponsesResponseStatusCancelled  OpenAIResponsesResponseStatus = "cancelled"
	OpenAIResponsesResponseStatusQueued     OpenAIResponsesResponseStatus = "queued"
)

func (e OpenAIResponsesResponseStatus) ToPointer() *OpenAIResponsesResponseStatus {
	return &e
}
func (e *OpenAIResponsesResponseStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "completed":
		fallthrough
	case "incomplete":
		fallthrough
	case "in_progress":
		fallthrough
	case "failed":
		fallthrough
	case "cancelled":
		fallthrough
	case "queued":
		*e = OpenAIResponsesResponseStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OpenAIResponsesResponseStatus: %v", v)
	}
}
