// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 3470f3ca3b68

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
)

type OpenAIFileListObject string

const (
	OpenAIFileListObjectList OpenAIFileListObject = "list"
)

func (e OpenAIFileListObject) ToPointer() *OpenAIFileListObject {
	return &e
}
func (e *OpenAIFileListObject) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "list":
		*e = OpenAIFileListObject(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OpenAIFileListObject: %v", v)
	}
}

// OpenAIFileList - A page of files in OpenAI's shape.
type OpenAIFileList struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	shape   string               `const:"openai" json:"_shape"`
	Data    []OpenAIFile         `json:"data"`
	FirstID *string              `json:"first_id"`
	HasMore bool                 `json:"has_more"`
	LastID  *string              `json:"last_id"`
	Object  OpenAIFileListObject `json:"object"`
}

func (o OpenAIFileList) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OpenAIFileList) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OpenAIFileList) GetShape() string {
	return "openai"
}

func (o *OpenAIFileList) GetData() []OpenAIFile {
	if o == nil {
		return []OpenAIFile{}
	}
	return o.Data
}

func (o *OpenAIFileList) GetFirstID() *string {
	if o == nil {
		return nil
	}
	return o.FirstID
}

func (o *OpenAIFileList) GetHasMore() bool {
	if o == nil {
		return false
	}
	return o.HasMore
}

func (o *OpenAIFileList) GetLastID() *string {
	if o == nil {
		return nil
	}
	return o.LastID
}

func (o *OpenAIFileList) GetObject() OpenAIFileListObject {
	if o == nil {
		return OpenAIFileListObject("")
	}
	return o.Object
}
