// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 91a5c1466f23

package shared

import (
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
)

// OpenResponsesErrorMetadataAlignment - Beta. The result of the alignment plugin for this request; the shape may change.
type OpenResponsesErrorMetadataAlignment struct {
	// One record per evaluated assistant message of the request, in the order the messages were produced.
	Calls    []AlignmentCallRecord `json:"calls"`
	Rejected *AlignmentRejected    `json:"rejected,omitzero"`
}

func (o OpenResponsesErrorMetadataAlignment) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OpenResponsesErrorMetadataAlignment) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OpenResponsesErrorMetadataAlignment) GetCalls() []AlignmentCallRecord {
	if o == nil {
		return []AlignmentCallRecord{}
	}
	return o.Calls
}

func (o *OpenResponsesErrorMetadataAlignment) GetRejected() *AlignmentRejected {
	if o == nil {
		return nil
	}
	return o.Rejected
}

// OpenResponsesErrorMetadata - OpenRouter-specific details of a failed response, such as the alignment object of an alignment error.
type OpenResponsesErrorMetadata struct {
	// Beta. The result of the alignment plugin for this request; the shape may change.
	Alignment *OpenResponsesErrorMetadataAlignment `json:"alignment,omitzero"`
}

func (o OpenResponsesErrorMetadata) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OpenResponsesErrorMetadata) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OpenResponsesErrorMetadata) GetAlignment() *OpenResponsesErrorMetadataAlignment {
	if o == nil {
		return nil
	}
	return o.Alignment
}
