// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 91cce534ed4c

package shared

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
)

type ORAnthropicNullableCallerType string

const (
	ORAnthropicNullableCallerTypeCodeExecution20250825 ORAnthropicNullableCallerType = "code_execution_20250825"
	ORAnthropicNullableCallerTypeCodeExecution20260120 ORAnthropicNullableCallerType = "code_execution_20260120"
	ORAnthropicNullableCallerTypeDirect                ORAnthropicNullableCallerType = "direct"
)

type ORAnthropicNullableCaller struct {
	AnthropicDirectCaller                *AnthropicDirectCaller                `queryParam:"inline" union:"member"`
	AnthropicCodeExecution20250825Caller *AnthropicCodeExecution20250825Caller `queryParam:"inline" union:"member"`
	AnthropicCodeExecution20260120Caller *AnthropicCodeExecution20260120Caller `queryParam:"inline" union:"member"`

	Type ORAnthropicNullableCallerType
}

func CreateORAnthropicNullableCallerCodeExecution20250825(codeExecution20250825 AnthropicCodeExecution20250825Caller) ORAnthropicNullableCaller {
	typ := ORAnthropicNullableCallerTypeCodeExecution20250825

	return ORAnthropicNullableCaller{
		AnthropicCodeExecution20250825Caller: &codeExecution20250825,
		Type:                                 typ,
	}
}

func CreateORAnthropicNullableCallerCodeExecution20260120(codeExecution20260120 AnthropicCodeExecution20260120Caller) ORAnthropicNullableCaller {
	typ := ORAnthropicNullableCallerTypeCodeExecution20260120

	return ORAnthropicNullableCaller{
		AnthropicCodeExecution20260120Caller: &codeExecution20260120,
		Type:                                 typ,
	}
}

func CreateORAnthropicNullableCallerDirect(direct AnthropicDirectCaller) ORAnthropicNullableCaller {
	typ := ORAnthropicNullableCallerTypeDirect

	return ORAnthropicNullableCaller{
		AnthropicDirectCaller: &direct,
		Type:                  typ,
	}
}

func (u *ORAnthropicNullableCaller) UnmarshalJSON(data []byte) (err error) {
	previous := *u
	*u = ORAnthropicNullableCaller{}
	defer func() {
		if err != nil {
			*u = previous
		}
	}()

	type discriminator struct {
		Type string `json:"type"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.Type {
	case "code_execution_20250825":
		anthropicCodeExecution20250825Caller := new(AnthropicCodeExecution20250825Caller)
		if err := utils.UnmarshalJSON(data, &anthropicCodeExecution20250825Caller, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == code_execution_20250825) type AnthropicCodeExecution20250825Caller within ORAnthropicNullableCaller: %w", string(data), err)
		}

		u.AnthropicCodeExecution20250825Caller = anthropicCodeExecution20250825Caller
		u.Type = ORAnthropicNullableCallerTypeCodeExecution20250825
		return nil
	case "code_execution_20260120":
		anthropicCodeExecution20260120Caller := new(AnthropicCodeExecution20260120Caller)
		if err := utils.UnmarshalJSON(data, &anthropicCodeExecution20260120Caller, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == code_execution_20260120) type AnthropicCodeExecution20260120Caller within ORAnthropicNullableCaller: %w", string(data), err)
		}

		u.AnthropicCodeExecution20260120Caller = anthropicCodeExecution20260120Caller
		u.Type = ORAnthropicNullableCallerTypeCodeExecution20260120
		return nil
	case "direct":
		anthropicDirectCaller := new(AnthropicDirectCaller)
		if err := utils.UnmarshalJSON(data, &anthropicDirectCaller, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == direct) type AnthropicDirectCaller within ORAnthropicNullableCaller: %w", string(data), err)
		}

		u.AnthropicDirectCaller = anthropicDirectCaller
		u.Type = ORAnthropicNullableCallerTypeDirect
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for ORAnthropicNullableCaller", string(data))
}

func (u ORAnthropicNullableCaller) MarshalJSON() ([]byte, error) {
	if u.AnthropicDirectCaller != nil {
		return utils.MarshalJSON(u.AnthropicDirectCaller, "", true)
	}

	if u.AnthropicCodeExecution20250825Caller != nil {
		return utils.MarshalJSON(u.AnthropicCodeExecution20250825Caller, "", true)
	}

	if u.AnthropicCodeExecution20260120Caller != nil {
		return utils.MarshalJSON(u.AnthropicCodeExecution20260120Caller, "", true)
	}

	return nil, errors.New("could not marshal union type ORAnthropicNullableCaller: all fields are null")
}
