// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 0837c1e8b659

package shared

import (
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
)

// ORAnthropicToolSearchResult - Router-owned deferred discovery result containing original selected tool definitions.
type ORAnthropicToolSearchResult struct {
	Content   map[string]any `json:"content"`
	ToolUseID string         `json:"tool_use_id"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_ string `const:"openrouter_tool_search_result" json:"type"`
}

func (o ORAnthropicToolSearchResult) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *ORAnthropicToolSearchResult) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *ORAnthropicToolSearchResult) GetContent() map[string]any {
	if o == nil {
		return map[string]any{}
	}
	return o.Content
}

func (o *ORAnthropicToolSearchResult) GetToolUseID() string {
	if o == nil {
		return ""
	}
	return o.ToolUseID
}

func (o *ORAnthropicToolSearchResult) GetType() string {
	return "openrouter_tool_search_result"
}
