// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/speakeasy/terraform-provider-openrouter/internal/sdk/internal/utils"
)

type OutputSubagentServerToolItemType string

const (
	OutputSubagentServerToolItemTypeOpenrouterSubagent OutputSubagentServerToolItemType = "openrouter:subagent"
)

func (e OutputSubagentServerToolItemType) ToPointer() *OutputSubagentServerToolItemType {
	return &e
}
func (e *OutputSubagentServerToolItemType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "openrouter:subagent":
		*e = OutputSubagentServerToolItemType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OutputSubagentServerToolItemType: %v", v)
	}
}

// OutputSubagentServerToolItem - An openrouter:subagent server tool output item
type OutputSubagentServerToolItem struct {
	// Error message when the subagent task did not produce an outcome.
	Error *string `json:"error,omitzero"`
	ID    *string `json:"id,omitzero"`
	// Slug of the worker model that executed the task.
	Model *string `json:"model,omitzero"`
	// The worker model's result (the outcome text returned to the delegating model).
	Outcome *string        `json:"outcome,omitzero"`
	Status  ToolCallStatus `json:"status"`
	// The task description the delegating model sent to the worker.
	TaskDescription *string `json:"task_description,omitzero"`
	// The short task identifier the delegating model supplied.
	TaskName *string                          `json:"task_name,omitzero"`
	Type     OutputSubagentServerToolItemType `json:"type"`
}

func (o OutputSubagentServerToolItem) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OutputSubagentServerToolItem) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OutputSubagentServerToolItem) GetError() *string {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *OutputSubagentServerToolItem) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *OutputSubagentServerToolItem) GetModel() *string {
	if o == nil {
		return nil
	}
	return o.Model
}

func (o *OutputSubagentServerToolItem) GetOutcome() *string {
	if o == nil {
		return nil
	}
	return o.Outcome
}

func (o *OutputSubagentServerToolItem) GetStatus() ToolCallStatus {
	if o == nil {
		return ToolCallStatus("")
	}
	return o.Status
}

func (o *OutputSubagentServerToolItem) GetTaskDescription() *string {
	if o == nil {
		return nil
	}
	return o.TaskDescription
}

func (o *OutputSubagentServerToolItem) GetTaskName() *string {
	if o == nil {
		return nil
	}
	return o.TaskName
}

func (o *OutputSubagentServerToolItem) GetType() OutputSubagentServerToolItemType {
	if o == nil {
		return OutputSubagentServerToolItemType("")
	}
	return o.Type
}
