// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 7446a499473b

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
)

type OutputShellServerToolItemAction struct {
	Commands        []string `json:"commands"`
	MaxOutputLength *int64   `json:"max_output_length,omitzero"`
	TimeoutMs       *int64   `json:"timeout_ms,omitzero"`
}

func (o OutputShellServerToolItemAction) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OutputShellServerToolItemAction) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OutputShellServerToolItemAction) GetCommands() []string {
	if o == nil {
		return []string{}
	}
	return o.Commands
}

func (o *OutputShellServerToolItemAction) GetMaxOutputLength() *int64 {
	if o == nil {
		return nil
	}
	return o.MaxOutputLength
}

func (o *OutputShellServerToolItemAction) GetTimeoutMs() *int64 {
	if o == nil {
		return nil
	}
	return o.TimeoutMs
}

type OutputShellServerToolItemType string

const (
	OutputShellServerToolItemTypeOpenrouterShell OutputShellServerToolItemType = "openrouter:shell"
)

func (e OutputShellServerToolItemType) ToPointer() *OutputShellServerToolItemType {
	return &e
}
func (e *OutputShellServerToolItemType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "openrouter:shell":
		*e = OutputShellServerToolItemType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OutputShellServerToolItemType: %v", v)
	}
}

// OutputShellServerToolItem - An openrouter:shell server tool output item
type OutputShellServerToolItem struct {
	Action *OutputShellServerToolItemAction `json:"action,omitzero"`
	// The raw tool-call arguments string as emitted by the model.
	Arguments *string `json:"arguments,omitzero"`
	// The model-generated tool call id from the originating turn.
	CallID *string                       `json:"call_id,omitzero"`
	ID     *string                       `json:"id,omitzero"`
	Output []ShellCallOutputContent      `json:"output,omitzero"`
	Status ToolCallStatus                `json:"status"`
	Type   OutputShellServerToolItemType `json:"type"`
}

func (o OutputShellServerToolItem) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OutputShellServerToolItem) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OutputShellServerToolItem) GetAction() *OutputShellServerToolItemAction {
	if o == nil {
		return nil
	}
	return o.Action
}

func (o *OutputShellServerToolItem) GetArguments() *string {
	if o == nil {
		return nil
	}
	return o.Arguments
}

func (o *OutputShellServerToolItem) GetCallID() *string {
	if o == nil {
		return nil
	}
	return o.CallID
}

func (o *OutputShellServerToolItem) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *OutputShellServerToolItem) GetOutput() []ShellCallOutputContent {
	if o == nil {
		return nil
	}
	return o.Output
}

func (o *OutputShellServerToolItem) GetStatus() ToolCallStatus {
	if o == nil {
		return ToolCallStatus("")
	}
	return o.Status
}

func (o *OutputShellServerToolItem) GetType() OutputShellServerToolItemType {
	if o == nil {
		return OutputShellServerToolItemType("")
	}
	return o.Type
}
