// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 31a9a1825bdb

package shared

import (
	"encoding/json"
	"fmt"
)

// PrivateEndpointDeclaredRegion - Where you attest this deployment processes data. `global` means not regional; `null` means undeclared.
type PrivateEndpointDeclaredRegion string

const (
	PrivateEndpointDeclaredRegionGlobal PrivateEndpointDeclaredRegion = "global"
	PrivateEndpointDeclaredRegionEurope PrivateEndpointDeclaredRegion = "europe"
	PrivateEndpointDeclaredRegionUs     PrivateEndpointDeclaredRegion = "us"
)

func (e PrivateEndpointDeclaredRegion) ToPointer() *PrivateEndpointDeclaredRegion {
	return &e
}
func (e *PrivateEndpointDeclaredRegion) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "global":
		fallthrough
	case "europe":
		fallthrough
	case "us":
		*e = PrivateEndpointDeclaredRegion(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PrivateEndpointDeclaredRegion: %v", v)
	}
}
