// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type Quantization string

const (
	QuantizationInt4    Quantization = "int4"
	QuantizationInt8    Quantization = "int8"
	QuantizationFp4     Quantization = "fp4"
	QuantizationMxfp4   Quantization = "mxfp4"
	QuantizationNvfp4   Quantization = "nvfp4"
	QuantizationFp6     Quantization = "fp6"
	QuantizationFp8     Quantization = "fp8"
	QuantizationMxfp8   Quantization = "mxfp8"
	QuantizationFp16    Quantization = "fp16"
	QuantizationBf16    Quantization = "bf16"
	QuantizationFp32    Quantization = "fp32"
	QuantizationUnknown Quantization = "unknown"
)

func (e Quantization) ToPointer() *Quantization {
	return &e
}
func (e *Quantization) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "int4":
		fallthrough
	case "int8":
		fallthrough
	case "fp4":
		fallthrough
	case "mxfp4":
		fallthrough
	case "nvfp4":
		fallthrough
	case "fp6":
		fallthrough
	case "fp8":
		fallthrough
	case "mxfp8":
		fallthrough
	case "fp16":
		fallthrough
	case "bf16":
		fallthrough
	case "fp32":
		fallthrough
	case "unknown":
		*e = Quantization(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Quantization: %v", v)
	}
}
