// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: dc1ae8ed5fe1

package shared

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
)

type ReasoningItemStatusInProgress string

const (
	ReasoningItemStatusInProgressInProgress ReasoningItemStatusInProgress = "in_progress"
)

func (e ReasoningItemStatusInProgress) ToPointer() *ReasoningItemStatusInProgress {
	return &e
}
func (e *ReasoningItemStatusInProgress) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "in_progress":
		*e = ReasoningItemStatusInProgress(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ReasoningItemStatusInProgress: %v", v)
	}
}

type ReasoningItemStatusIncomplete string

const (
	ReasoningItemStatusIncompleteIncomplete ReasoningItemStatusIncomplete = "incomplete"
)

func (e ReasoningItemStatusIncomplete) ToPointer() *ReasoningItemStatusIncomplete {
	return &e
}
func (e *ReasoningItemStatusIncomplete) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "incomplete":
		*e = ReasoningItemStatusIncomplete(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ReasoningItemStatusIncomplete: %v", v)
	}
}

type ReasoningItemStatusCompleted string

const (
	ReasoningItemStatusCompletedCompleted ReasoningItemStatusCompleted = "completed"
)

func (e ReasoningItemStatusCompleted) ToPointer() *ReasoningItemStatusCompleted {
	return &e
}
func (e *ReasoningItemStatusCompleted) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "completed":
		*e = ReasoningItemStatusCompleted(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ReasoningItemStatusCompleted: %v", v)
	}
}

type ReasoningItemStatusUnionType string

const (
	ReasoningItemStatusUnionTypeReasoningItemStatusCompleted  ReasoningItemStatusUnionType = "ReasoningItem_status_Completed"
	ReasoningItemStatusUnionTypeReasoningItemStatusIncomplete ReasoningItemStatusUnionType = "ReasoningItem_status_Incomplete"
	ReasoningItemStatusUnionTypeReasoningItemStatusInProgress ReasoningItemStatusUnionType = "ReasoningItem_status_InProgress"
)

type ReasoningItemStatusUnion struct {
	ReasoningItemStatusCompleted  *ReasoningItemStatusCompleted  `queryParam:"inline" union:"member"`
	ReasoningItemStatusIncomplete *ReasoningItemStatusIncomplete `queryParam:"inline" union:"member"`
	ReasoningItemStatusInProgress *ReasoningItemStatusInProgress `queryParam:"inline" union:"member"`

	Type ReasoningItemStatusUnionType
}

func CreateReasoningItemStatusUnionReasoningItemStatusCompleted(reasoningItemStatusCompleted ReasoningItemStatusCompleted) ReasoningItemStatusUnion {
	typ := ReasoningItemStatusUnionTypeReasoningItemStatusCompleted

	return ReasoningItemStatusUnion{
		ReasoningItemStatusCompleted: &reasoningItemStatusCompleted,
		Type:                         typ,
	}
}

func CreateReasoningItemStatusUnionReasoningItemStatusIncomplete(reasoningItemStatusIncomplete ReasoningItemStatusIncomplete) ReasoningItemStatusUnion {
	typ := ReasoningItemStatusUnionTypeReasoningItemStatusIncomplete

	return ReasoningItemStatusUnion{
		ReasoningItemStatusIncomplete: &reasoningItemStatusIncomplete,
		Type:                          typ,
	}
}

func CreateReasoningItemStatusUnionReasoningItemStatusInProgress(reasoningItemStatusInProgress ReasoningItemStatusInProgress) ReasoningItemStatusUnion {
	typ := ReasoningItemStatusUnionTypeReasoningItemStatusInProgress

	return ReasoningItemStatusUnion{
		ReasoningItemStatusInProgress: &reasoningItemStatusInProgress,
		Type:                          typ,
	}
}

func (u *ReasoningItemStatusUnion) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var reasoningItemStatusCompleted ReasoningItemStatusCompleted = ReasoningItemStatusCompleted("")
	if err := utils.UnmarshalJSON(data, &reasoningItemStatusCompleted, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ReasoningItemStatusUnionTypeReasoningItemStatusCompleted,
			Value: &reasoningItemStatusCompleted,
		})
	}

	var reasoningItemStatusIncomplete ReasoningItemStatusIncomplete = ReasoningItemStatusIncomplete("")
	if err := utils.UnmarshalJSON(data, &reasoningItemStatusIncomplete, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ReasoningItemStatusUnionTypeReasoningItemStatusIncomplete,
			Value: &reasoningItemStatusIncomplete,
		})
	}

	var reasoningItemStatusInProgress ReasoningItemStatusInProgress = ReasoningItemStatusInProgress("")
	if err := utils.UnmarshalJSON(data, &reasoningItemStatusInProgress, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ReasoningItemStatusUnionTypeReasoningItemStatusInProgress,
			Value: &reasoningItemStatusInProgress,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for ReasoningItemStatusUnion", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for ReasoningItemStatusUnion", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(ReasoningItemStatusUnionType)
	switch best.Type {
	case ReasoningItemStatusUnionTypeReasoningItemStatusCompleted:
		u.ReasoningItemStatusCompleted = best.Value.(*ReasoningItemStatusCompleted)
		return nil
	case ReasoningItemStatusUnionTypeReasoningItemStatusIncomplete:
		u.ReasoningItemStatusIncomplete = best.Value.(*ReasoningItemStatusIncomplete)
		return nil
	case ReasoningItemStatusUnionTypeReasoningItemStatusInProgress:
		u.ReasoningItemStatusInProgress = best.Value.(*ReasoningItemStatusInProgress)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for ReasoningItemStatusUnion", string(data))
}

func (u ReasoningItemStatusUnion) MarshalJSON() ([]byte, error) {
	if u.ReasoningItemStatusCompleted != nil {
		return utils.MarshalJSON(u.ReasoningItemStatusCompleted, "", true)
	}

	if u.ReasoningItemStatusIncomplete != nil {
		return utils.MarshalJSON(u.ReasoningItemStatusIncomplete, "", true)
	}

	if u.ReasoningItemStatusInProgress != nil {
		return utils.MarshalJSON(u.ReasoningItemStatusInProgress, "", true)
	}

	return nil, errors.New("could not marshal union type ReasoningItemStatusUnion: all fields are null")
}

type ReasoningItemType string

const (
	ReasoningItemTypeReasoning ReasoningItemType = "reasoning"
)

func (e ReasoningItemType) ToPointer() *ReasoningItemType {
	return &e
}
func (e *ReasoningItemType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "reasoning":
		*e = ReasoningItemType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ReasoningItemType: %v", v)
	}
}

// ReasoningItem - Reasoning output item with signature and format extensions
type ReasoningItem struct {
	Content          []ReasoningTextContent    `json:"content,omitzero"`
	EncryptedContent *string                   `json:"encrypted_content,omitzero"`
	ID               string                    `json:"id"`
	Status           *ReasoningItemStatusUnion `json:"status,omitzero"`
	Summary          []ReasoningSummaryText    `json:"summary"`
	Type             ReasoningItemType         `json:"type"`
	Format           *ReasoningFormat          `json:"format,omitzero"`
	Signature        *string                   `json:"signature,omitzero"`
}

func (r ReasoningItem) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ReasoningItem) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *ReasoningItem) GetContent() []ReasoningTextContent {
	if r == nil {
		return nil
	}
	return r.Content
}

func (r *ReasoningItem) GetEncryptedContent() *string {
	if r == nil {
		return nil
	}
	return r.EncryptedContent
}

func (r *ReasoningItem) GetID() string {
	if r == nil {
		return ""
	}
	return r.ID
}

func (r *ReasoningItem) GetStatus() *ReasoningItemStatusUnion {
	if r == nil {
		return nil
	}
	return r.Status
}

func (r *ReasoningItem) GetSummary() []ReasoningSummaryText {
	if r == nil {
		return []ReasoningSummaryText{}
	}
	return r.Summary
}

func (r *ReasoningItem) GetType() ReasoningItemType {
	if r == nil {
		return ReasoningItemType("")
	}
	return r.Type
}

func (r *ReasoningItem) GetFormat() *ReasoningFormat {
	if r == nil {
		return nil
	}
	return r.Format
}

func (r *ReasoningItem) GetSignature() *string {
	if r == nil {
		return nil
	}
	return r.Signature
}
