// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// ReasoningMode - Selects the reasoning mode. `standard` is the default; `pro` engages deeper reasoning on models that support it, billed at standard token rates. Only supported by OpenAI GPT-5.6 and newer.
type ReasoningMode string

const (
	ReasoningModeStandard ReasoningMode = "standard"
	ReasoningModePro      ReasoningMode = "pro"
)

func (e ReasoningMode) ToPointer() *ReasoningMode {
	return &e
}
func (e *ReasoningMode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "standard":
		fallthrough
	case "pro":
		*e = ReasoningMode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ReasoningMode: %v", v)
	}
}
