// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: aaa6c9ef054e

package shared

type ServerToolPrice struct {
	MaxUnitsPerCall int64 `json:"max_units_per_call"`
	// The `parameters.mode` this price applies to; null for prices that do not depend on the mode. A request bills exactly one `request` row
	Mode *string `json:"mode"`
	// USD per unit, as a decimal string
	Price string `json:"price"`
	Unit  string `json:"unit"`
}

func (s *ServerToolPrice) GetMaxUnitsPerCall() int64 {
	if s == nil {
		return 0
	}
	return s.MaxUnitsPerCall
}

func (s *ServerToolPrice) GetMode() *string {
	if s == nil {
		return nil
	}
	return s.Mode
}

func (s *ServerToolPrice) GetPrice() string {
	if s == nil {
		return ""
	}
	return s.Price
}

func (s *ServerToolPrice) GetUnit() string {
	if s == nil {
		return ""
	}
	return s.Unit
}
