// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type SessionCostResponse struct {
	Data []SessionCostItem `json:"data"`
	Meta SessionCostMeta   `json:"meta"`
}

func (s *SessionCostResponse) GetData() []SessionCostItem {
	if s == nil {
		return []SessionCostItem{}
	}
	return s.Data
}

func (s *SessionCostResponse) GetMeta() SessionCostMeta {
	if s == nil {
		return SessionCostMeta{}
	}
	return s.Meta
}
