// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// SessionCostMetaVersion - Dataset version.
type SessionCostMetaVersion string

const (
	SessionCostMetaVersionV1 SessionCostMetaVersion = "v1"
)

func (e SessionCostMetaVersion) ToPointer() *SessionCostMetaVersion {
	return &e
}
func (e *SessionCostMetaVersion) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "v1":
		*e = SessionCostMetaVersion(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SessionCostMetaVersion: %v", v)
	}
}

type SessionCostMeta struct {
	// ISO-8601 timestamp when the response was generated.
	AsOf string `json:"as_of"`
	// Dataset version.
	Version SessionCostMetaVersion `json:"version"`
	// Number of days in the weekly session sample window, or null when no snapshot is published.
	WindowDays *int64 `json:"window_days"`
	// UTC date of the final day in the session sample window, or null when no snapshot is published.
	WindowEndDate *string `json:"window_end_date"`
}

func (s *SessionCostMeta) GetAsOf() string {
	if s == nil {
		return ""
	}
	return s.AsOf
}

func (s *SessionCostMeta) GetVersion() SessionCostMetaVersion {
	if s == nil {
		return SessionCostMetaVersion("")
	}
	return s.Version
}

func (s *SessionCostMeta) GetWindowDays() *int64 {
	if s == nil {
		return nil
	}
	return s.WindowDays
}

func (s *SessionCostMeta) GetWindowEndDate() *string {
	if s == nil {
		return nil
	}
	return s.WindowEndDate
}
