// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 26be546d2382

package shared

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
)

type ShellServerToolEnvironmentType string

const (
	ShellServerToolEnvironmentTypeContainerAuto      ShellServerToolEnvironmentType = "container_auto"
	ShellServerToolEnvironmentTypeContainerReference ShellServerToolEnvironmentType = "container_reference"
)

// ShellServerToolEnvironment - Server-side execution environment for the shell tool. Only container-backed environments are supported; "local" shells are not.
type ShellServerToolEnvironment struct {
	ContainerAutoEnvironment      *ContainerAutoEnvironment      `queryParam:"inline" union:"member"`
	ContainerReferenceEnvironment *ContainerReferenceEnvironment `queryParam:"inline" union:"member"`

	Type ShellServerToolEnvironmentType
}

func CreateShellServerToolEnvironmentContainerAuto(containerAuto ContainerAutoEnvironment) ShellServerToolEnvironment {
	typ := ShellServerToolEnvironmentTypeContainerAuto

	return ShellServerToolEnvironment{
		ContainerAutoEnvironment: &containerAuto,
		Type:                     typ,
	}
}

func CreateShellServerToolEnvironmentContainerReference(containerReference ContainerReferenceEnvironment) ShellServerToolEnvironment {
	typ := ShellServerToolEnvironmentTypeContainerReference

	return ShellServerToolEnvironment{
		ContainerReferenceEnvironment: &containerReference,
		Type:                          typ,
	}
}

func (u *ShellServerToolEnvironment) UnmarshalJSON(data []byte) (err error) {
	previous := *u
	*u = ShellServerToolEnvironment{}
	defer func() {
		if err != nil {
			*u = previous
		}
	}()

	type discriminator struct {
		Type string `json:"type"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.Type {
	case "container_auto":
		containerAutoEnvironment := new(ContainerAutoEnvironment)
		if err := utils.UnmarshalJSON(data, &containerAutoEnvironment, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == container_auto) type ContainerAutoEnvironment within ShellServerToolEnvironment: %w", string(data), err)
		}

		u.ContainerAutoEnvironment = containerAutoEnvironment
		u.Type = ShellServerToolEnvironmentTypeContainerAuto
		return nil
	case "container_reference":
		containerReferenceEnvironment := new(ContainerReferenceEnvironment)
		if err := utils.UnmarshalJSON(data, &containerReferenceEnvironment, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == container_reference) type ContainerReferenceEnvironment within ShellServerToolEnvironment: %w", string(data), err)
		}

		u.ContainerReferenceEnvironment = containerReferenceEnvironment
		u.Type = ShellServerToolEnvironmentTypeContainerReference
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for ShellServerToolEnvironment", string(data))
}

func (u ShellServerToolEnvironment) MarshalJSON() ([]byte, error) {
	if u.ContainerAutoEnvironment != nil {
		return utils.MarshalJSON(u.ContainerAutoEnvironment, "", true)
	}

	if u.ContainerReferenceEnvironment != nil {
		return utils.MarshalJSON(u.ContainerReferenceEnvironment, "", true)
	}

	return nil, errors.New("could not marshal union type ShellServerToolEnvironment: all fields are null")
}
