// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: c9610be81e06

package shared

import (
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
)

// SpeechInputReferenceText - Transcript of the accompanying reference audio
type SpeechInputReferenceText struct {
	// Transcript of the accompanying reference audio.
	Text string `json:"text"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_ string `const:"text" json:"type"`
}

func (s SpeechInputReferenceText) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SpeechInputReferenceText) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SpeechInputReferenceText) GetText() string {
	if s == nil {
		return ""
	}
	return s.Text
}

func (s *SpeechInputReferenceText) GetType() string {
	return "text"
}
