// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 60da7e4aa865

package shared

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
)

type SpeechInputReferenceType string

const (
	SpeechInputReferenceTypeImageURL   SpeechInputReferenceType = "image_url"
	SpeechInputReferenceTypeInputAudio SpeechInputReferenceType = "input_audio"
	SpeechInputReferenceTypeText       SpeechInputReferenceType = "text"
)

// SpeechInputReference - Reference content part for stateless voice cloning or voice design
type SpeechInputReference struct {
	SpeechInputReferenceAudio *SpeechInputReferenceAudio `queryParam:"inline" union:"member"`
	SpeechInputReferenceText  *SpeechInputReferenceText  `queryParam:"inline" union:"member"`
	SpeechInputReferenceImage *SpeechInputReferenceImage `queryParam:"inline" union:"member"`

	Type SpeechInputReferenceType
}

func CreateSpeechInputReferenceImageURL(imageURL SpeechInputReferenceImage) SpeechInputReference {
	typ := SpeechInputReferenceTypeImageURL

	return SpeechInputReference{
		SpeechInputReferenceImage: &imageURL,
		Type:                      typ,
	}
}

func CreateSpeechInputReferenceInputAudio(inputAudio SpeechInputReferenceAudio) SpeechInputReference {
	typ := SpeechInputReferenceTypeInputAudio

	return SpeechInputReference{
		SpeechInputReferenceAudio: &inputAudio,
		Type:                      typ,
	}
}

func CreateSpeechInputReferenceText(text SpeechInputReferenceText) SpeechInputReference {
	typ := SpeechInputReferenceTypeText

	return SpeechInputReference{
		SpeechInputReferenceText: &text,
		Type:                     typ,
	}
}

func (u *SpeechInputReference) UnmarshalJSON(data []byte) (err error) {
	previous := *u
	*u = SpeechInputReference{}
	defer func() {
		if err != nil {
			*u = previous
		}
	}()

	type discriminator struct {
		Type string `json:"type"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.Type {
	case "image_url":
		speechInputReferenceImage := new(SpeechInputReferenceImage)
		if err := utils.UnmarshalJSON(data, &speechInputReferenceImage, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == image_url) type SpeechInputReferenceImage within SpeechInputReference: %w", string(data), err)
		}

		u.SpeechInputReferenceImage = speechInputReferenceImage
		u.Type = SpeechInputReferenceTypeImageURL
		return nil
	case "input_audio":
		speechInputReferenceAudio := new(SpeechInputReferenceAudio)
		if err := utils.UnmarshalJSON(data, &speechInputReferenceAudio, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == input_audio) type SpeechInputReferenceAudio within SpeechInputReference: %w", string(data), err)
		}

		u.SpeechInputReferenceAudio = speechInputReferenceAudio
		u.Type = SpeechInputReferenceTypeInputAudio
		return nil
	case "text":
		speechInputReferenceText := new(SpeechInputReferenceText)
		if err := utils.UnmarshalJSON(data, &speechInputReferenceText, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == text) type SpeechInputReferenceText within SpeechInputReference: %w", string(data), err)
		}

		u.SpeechInputReferenceText = speechInputReferenceText
		u.Type = SpeechInputReferenceTypeText
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for SpeechInputReference", string(data))
}

func (u SpeechInputReference) MarshalJSON() ([]byte, error) {
	if u.SpeechInputReferenceAudio != nil {
		return utils.MarshalJSON(u.SpeechInputReferenceAudio, "", true)
	}

	if u.SpeechInputReferenceText != nil {
		return utils.MarshalJSON(u.SpeechInputReferenceText, "", true)
	}

	if u.SpeechInputReferenceImage != nil {
		return utils.MarshalJSON(u.SpeechInputReferenceImage, "", true)
	}

	return nil, errors.New("could not marshal union type SpeechInputReference: all fields are null")
}
