// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy/terraform-provider-openrouter/internal/sdk/internal/utils"
)

// StopServerToolsWhenMaxCost - Stop once cumulative cost across the loop exceeds this dollar threshold.
type StopServerToolsWhenMaxCost struct {
	MaxCostInDollars float64 `json:"max_cost_in_dollars"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_ string `const:"max_cost" json:"type"`
}

func (s StopServerToolsWhenMaxCost) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StopServerToolsWhenMaxCost) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StopServerToolsWhenMaxCost) GetMaxCostInDollars() float64 {
	if s == nil {
		return 0.0
	}
	return s.MaxCostInDollars
}

func (s *StopServerToolsWhenMaxCost) GetType() string {
	return "max_cost"
}
