// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 29ab2fd4af92

package shared

import (
	"encoding/json"
	"fmt"
)

// STTTimestampGranularity - A timestamp detail level for verbose_json transcription responses.
type STTTimestampGranularity string

const (
	STTTimestampGranularityWord    STTTimestampGranularity = "word"
	STTTimestampGranularitySegment STTTimestampGranularity = "segment"
)

func (e STTTimestampGranularity) ToPointer() *STTTimestampGranularity {
	return &e
}
func (e *STTTimestampGranularity) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "word":
		fallthrough
	case "segment":
		*e = STTTimestampGranularity(v)
		return nil
	default:
		return fmt.Errorf("invalid value for STTTimestampGranularity: %v", v)
	}
}
