// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type TaskClassificationMacroCategory struct {
	// Macro-category identifier.
	Key string `json:"key"`
	// Human-readable label for the macro-category.
	Label string `json:"label"`
	// Combined token share of all classifications in this macro-category (0–1).
	TokenShare float64 `json:"token_share"`
	// Combined usage share of all classifications in this macro-category (0–1).
	UsageShare float64 `json:"usage_share"`
}

func (t *TaskClassificationMacroCategory) GetKey() string {
	if t == nil {
		return ""
	}
	return t.Key
}

func (t *TaskClassificationMacroCategory) GetLabel() string {
	if t == nil {
		return ""
	}
	return t.Label
}

func (t *TaskClassificationMacroCategory) GetTokenShare() float64 {
	if t == nil {
		return 0.0
	}
	return t.TokenShare
}

func (t *TaskClassificationMacroCategory) GetUsageShare() float64 {
	if t == nil {
		return 0.0
	}
	return t.UsageShare
}
