// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: bbcfffc62590

package shared

import (
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
)

// UnprocessableEntityResponseErrorData - Error data for UnprocessableEntityResponse
type UnprocessableEntityResponseErrorData struct {
	Code     int64          `json:"code"`
	Message  string         `json:"message"`
	Metadata map[string]any `json:"metadata,omitzero"`
}

func (u UnprocessableEntityResponseErrorData) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UnprocessableEntityResponseErrorData) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UnprocessableEntityResponseErrorData) GetCode() int64 {
	if u == nil {
		return 0
	}
	return u.Code
}

func (u *UnprocessableEntityResponseErrorData) GetMessage() string {
	if u == nil {
		return ""
	}
	return u.Message
}

func (u *UnprocessableEntityResponseErrorData) GetMetadata() map[string]any {
	if u == nil {
		return nil
	}
	return u.Metadata
}
