// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 0f798d733d36

package shared

import (
	"encoding/json"
	"fmt"
)

// UpdatePrivateEndpointRequestDeclaredRegion - Attest where this deployment processes data.
type UpdatePrivateEndpointRequestDeclaredRegion string

const (
	UpdatePrivateEndpointRequestDeclaredRegionGlobal UpdatePrivateEndpointRequestDeclaredRegion = "global"
	UpdatePrivateEndpointRequestDeclaredRegionEurope UpdatePrivateEndpointRequestDeclaredRegion = "europe"
	UpdatePrivateEndpointRequestDeclaredRegionUs     UpdatePrivateEndpointRequestDeclaredRegion = "us"
)

func (e UpdatePrivateEndpointRequestDeclaredRegion) ToPointer() *UpdatePrivateEndpointRequestDeclaredRegion {
	return &e
}
func (e *UpdatePrivateEndpointRequestDeclaredRegion) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "global":
		fallthrough
	case "europe":
		fallthrough
	case "us":
		*e = UpdatePrivateEndpointRequestDeclaredRegion(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UpdatePrivateEndpointRequestDeclaredRegion: %v", v)
	}
}

type UpdatePrivateEndpointRequest struct {
	// HTTPS base URL of your deployment. Required unless the provider derives its URL from the BYOK credential (Azure, Amazon Bedrock, Google Vertex).
	BaseURL *string `json:"base_url,omitzero"`
	// Attest where this deployment processes data.
	DeclaredRegion *UpdatePrivateEndpointRequestDeclaredRegion `json:"declared_region,omitzero"`
	// Attest that this deployment retains no prompt or completion data.
	DeclaredZdr *bool `json:"declared_zdr,omitzero"`
	// Model or deployment identifier sent to the upstream provider.
	UpstreamModelID string `json:"upstream_model_id"`
}

func (u *UpdatePrivateEndpointRequest) GetBaseURL() *string {
	if u == nil {
		return nil
	}
	return u.BaseURL
}

func (u *UpdatePrivateEndpointRequest) GetDeclaredRegion() *UpdatePrivateEndpointRequestDeclaredRegion {
	if u == nil {
		return nil
	}
	return u.DeclaredRegion
}

func (u *UpdatePrivateEndpointRequest) GetDeclaredZdr() *bool {
	if u == nil {
		return nil
	}
	return u.DeclaredZdr
}

func (u *UpdatePrivateEndpointRequest) GetUpstreamModelID() string {
	if u == nil {
		return ""
	}
	return u.UpstreamModelID
}
