// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 8227a1e8e903

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/internal/utils"
)

type UpdateWorkspaceRequestDisabledServerTool string

const (
	UpdateWorkspaceRequestDisabledServerToolOpenrouterAdvisor                  UpdateWorkspaceRequestDisabledServerTool = "openrouter:advisor"
	UpdateWorkspaceRequestDisabledServerToolOpenrouterApplyPatch               UpdateWorkspaceRequestDisabledServerTool = "openrouter:apply_patch"
	UpdateWorkspaceRequestDisabledServerToolOpenrouterBash                     UpdateWorkspaceRequestDisabledServerTool = "openrouter:bash"
	UpdateWorkspaceRequestDisabledServerToolOpenrouterDatetime                 UpdateWorkspaceRequestDisabledServerTool = "openrouter:datetime"
	UpdateWorkspaceRequestDisabledServerToolOpenrouterFusion                   UpdateWorkspaceRequestDisabledServerTool = "openrouter:fusion"
	UpdateWorkspaceRequestDisabledServerToolOpenrouterImageGeneration          UpdateWorkspaceRequestDisabledServerTool = "openrouter:image_generation"
	UpdateWorkspaceRequestDisabledServerToolOpenrouterExperimentalSearchModels UpdateWorkspaceRequestDisabledServerTool = "openrouter:experimental__search_models"
	UpdateWorkspaceRequestDisabledServerToolOpenrouterShell                    UpdateWorkspaceRequestDisabledServerTool = "openrouter:shell"
	UpdateWorkspaceRequestDisabledServerToolOpenrouterSubagent                 UpdateWorkspaceRequestDisabledServerTool = "openrouter:subagent"
	UpdateWorkspaceRequestDisabledServerToolOpenrouterToolSearch               UpdateWorkspaceRequestDisabledServerTool = "openrouter:tool_search"
	UpdateWorkspaceRequestDisabledServerToolOpenrouterWebFetch                 UpdateWorkspaceRequestDisabledServerTool = "openrouter:web_fetch"
	UpdateWorkspaceRequestDisabledServerToolOpenrouterWebSearch                UpdateWorkspaceRequestDisabledServerTool = "openrouter:web_search"
)

func (e UpdateWorkspaceRequestDisabledServerTool) ToPointer() *UpdateWorkspaceRequestDisabledServerTool {
	return &e
}
func (e *UpdateWorkspaceRequestDisabledServerTool) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "openrouter:advisor":
		fallthrough
	case "openrouter:apply_patch":
		fallthrough
	case "openrouter:bash":
		fallthrough
	case "openrouter:datetime":
		fallthrough
	case "openrouter:fusion":
		fallthrough
	case "openrouter:image_generation":
		fallthrough
	case "openrouter:experimental__search_models":
		fallthrough
	case "openrouter:shell":
		fallthrough
	case "openrouter:subagent":
		fallthrough
	case "openrouter:tool_search":
		fallthrough
	case "openrouter:web_fetch":
		fallthrough
	case "openrouter:web_search":
		*e = UpdateWorkspaceRequestDisabledServerTool(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UpdateWorkspaceRequestDisabledServerTool: %v", v)
	}
}

type UpdateWorkspaceRequest struct {
	// Default image model for this workspace
	DefaultImageModel *string `json:"default_image_model,omitzero"`
	// Default provider sort preference (price, throughput, latency, exacto)
	DefaultProviderSort *string `json:"default_provider_sort,omitzero"`
	// Default text model for this workspace
	DefaultTextModel *string `json:"default_text_model,omitzero"`
	// New description for the workspace
	Description *string `json:"description,omitzero"`
	// OpenRouter server tools that requests in this workspace may not invoke. Requests naming a disabled tool are rejected with 403. An empty array or null clears the list.
	DisabledServerTools []UpdateWorkspaceRequestDisabledServerTool `json:"disabled_server_tools,omitzero"`
	// Optional array of API key IDs to filter I/O logging
	IoLoggingAPIKeyIds []int64 `json:"io_logging_api_key_ids,omitzero"`
	// Sampling rate for I/O logging (0.0001-1)
	IoLoggingSamplingRate *float64 `json:"io_logging_sampling_rate,omitzero"`
	// Whether data discount logging is enabled
	IsDataDiscountLoggingEnabled *bool `json:"is_data_discount_logging_enabled,omitzero"`
	// Whether broadcast is enabled
	IsObservabilityBroadcastEnabled *bool `json:"is_observability_broadcast_enabled,omitzero"`
	// Whether private logging is enabled
	IsObservabilityIoLoggingEnabled *bool `json:"is_observability_io_logging_enabled,omitzero"`
	// New name for the workspace
	Name *string `json:"name,omitzero"`
	// New URL-friendly slug (lowercase alphanumeric segments separated by single hyphens, no leading/trailing hyphens)
	Slug *string `json:"slug,omitzero"`
}

func (u UpdateWorkspaceRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateWorkspaceRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateWorkspaceRequest) GetDefaultImageModel() *string {
	if u == nil {
		return nil
	}
	return u.DefaultImageModel
}

func (u *UpdateWorkspaceRequest) GetDefaultProviderSort() *string {
	if u == nil {
		return nil
	}
	return u.DefaultProviderSort
}

func (u *UpdateWorkspaceRequest) GetDefaultTextModel() *string {
	if u == nil {
		return nil
	}
	return u.DefaultTextModel
}

func (u *UpdateWorkspaceRequest) GetDescription() *string {
	if u == nil {
		return nil
	}
	return u.Description
}

func (u *UpdateWorkspaceRequest) GetDisabledServerTools() []UpdateWorkspaceRequestDisabledServerTool {
	if u == nil {
		return nil
	}
	return u.DisabledServerTools
}

func (u *UpdateWorkspaceRequest) GetIoLoggingAPIKeyIds() []int64 {
	if u == nil {
		return nil
	}
	return u.IoLoggingAPIKeyIds
}

func (u *UpdateWorkspaceRequest) GetIoLoggingSamplingRate() *float64 {
	if u == nil {
		return nil
	}
	return u.IoLoggingSamplingRate
}

func (u *UpdateWorkspaceRequest) GetIsDataDiscountLoggingEnabled() *bool {
	if u == nil {
		return nil
	}
	return u.IsDataDiscountLoggingEnabled
}

func (u *UpdateWorkspaceRequest) GetIsObservabilityBroadcastEnabled() *bool {
	if u == nil {
		return nil
	}
	return u.IsObservabilityBroadcastEnabled
}

func (u *UpdateWorkspaceRequest) GetIsObservabilityIoLoggingEnabled() *bool {
	if u == nil {
		return nil
	}
	return u.IsObservabilityIoLoggingEnabled
}

func (u *UpdateWorkspaceRequest) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UpdateWorkspaceRequest) GetSlug() *string {
	if u == nil {
		return nil
	}
	return u.Slug
}
