// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: df2491818c60

package shared

// UpdateBYOKKeyResponseData - The updated BYOK credential.
type UpdateBYOKKeyResponseData struct {
	// Optional allowlist of OpenRouter API key hashes (`api_keys.hash`) that may use this credential. `null` means no restriction.
	AllowedAPIKeyHashes []string `json:"allowed_api_key_hashes"`
	// Optional allowlist of model slugs this credential may be used for. `null` means no restriction.
	AllowedModels []string `json:"allowed_models"`
	// Optional allowlist of user IDs that may use this credential. `null` means no restriction.
	AllowedUserIds []string `json:"allowed_user_ids"`
	// ISO timestamp of when the credential was created.
	CreatedAt string `json:"created_at"`
	// Whether this credential is currently disabled.
	Disabled bool `json:"disabled"`
	// Stable public identifier for this BYOK credential.
	ID string `json:"id"`
	// Whether OpenRouter's shared endpoints on this provider are removed for every model, including models outside `allowed_models` and after all of your keys for the provider fail. The provider is skipped instead of spending OpenRouter credits. Only valid on non-fallback credentials.
	IsByokOnly bool `json:"is_byok_only"`
	// Whether this credential is treated as a fallback — used only after non-fallback keys for the same provider have been tried. Cannot be combined with `is_byok_only`.
	IsFallback bool `json:"is_fallback"`
	// Whether OpenRouter's shared endpoints on this provider are removed for the models this credential applies to (its `allowed_models`, or every model when `null`). Requests for those models run only on your keys; models outside the allowlist may still fall back to shared capacity on this provider.
	IsRequired bool `json:"is_required"`
	// Short masked snippet of the key (e.g. the first/last few characters) used to identify it in the UI.
	Label string `json:"label"`
	// Optional human-readable name for the credential.
	Name *string `json:"name,omitzero"`
	// The upstream provider this credential authenticates against, as a lowercase slug (e.g. `openai`, `anthropic`, `amazon-bedrock`).
	ProviderSlug BYOKProviderSlug `json:"provider"`
	// Position within the provider — credentials are tried in ascending sort order.
	SortOrder int64 `json:"sort_order"`
	// The workspace this credential is scoped to, or `null` when it is global — usable across every workspace in the account. A `null` value does not mean the default workspace.
	WorkspaceID *string `json:"workspace_id"`
}

func (u *UpdateBYOKKeyResponseData) GetAllowedAPIKeyHashes() []string {
	if u == nil {
		return nil
	}
	return u.AllowedAPIKeyHashes
}

func (u *UpdateBYOKKeyResponseData) GetAllowedModels() []string {
	if u == nil {
		return nil
	}
	return u.AllowedModels
}

func (u *UpdateBYOKKeyResponseData) GetAllowedUserIds() []string {
	if u == nil {
		return nil
	}
	return u.AllowedUserIds
}

func (u *UpdateBYOKKeyResponseData) GetCreatedAt() string {
	if u == nil {
		return ""
	}
	return u.CreatedAt
}

func (u *UpdateBYOKKeyResponseData) GetDisabled() bool {
	if u == nil {
		return false
	}
	return u.Disabled
}

func (u *UpdateBYOKKeyResponseData) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateBYOKKeyResponseData) GetIsByokOnly() bool {
	if u == nil {
		return false
	}
	return u.IsByokOnly
}

func (u *UpdateBYOKKeyResponseData) GetIsFallback() bool {
	if u == nil {
		return false
	}
	return u.IsFallback
}

func (u *UpdateBYOKKeyResponseData) GetIsRequired() bool {
	if u == nil {
		return false
	}
	return u.IsRequired
}

func (u *UpdateBYOKKeyResponseData) GetLabel() string {
	if u == nil {
		return ""
	}
	return u.Label
}

func (u *UpdateBYOKKeyResponseData) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UpdateBYOKKeyResponseData) GetProviderSlug() BYOKProviderSlug {
	if u == nil {
		return BYOKProviderSlug("")
	}
	return u.ProviderSlug
}

func (u *UpdateBYOKKeyResponseData) GetSortOrder() int64 {
	if u == nil {
		return 0
	}
	return u.SortOrder
}

func (u *UpdateBYOKKeyResponseData) GetWorkspaceID() *string {
	if u == nil {
		return nil
	}
	return u.WorkspaceID
}

type UpdateBYOKKeyResponse struct {
	Data UpdateBYOKKeyResponseData `json:"data"`
}

func (u *UpdateBYOKKeyResponse) GetData() UpdateBYOKKeyResponseData {
	if u == nil {
		return UpdateBYOKKeyResponseData{}
	}
	return u.Data
}
