// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 21ea790a75e4

package shared

type UpdatePrivateEndpointPricingRequest struct {
	// Negotiated per-token rates reported for requests routed to this endpoint.
	Pricing PrivateEndpointPricing `json:"pricing"`
}

func (u *UpdatePrivateEndpointPricingRequest) GetPricing() PrivateEndpointPricing {
	if u == nil {
		return PrivateEndpointPricing{}
	}
	return u.Pricing
}
