// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type UpsertWorkspaceBudgetResponse struct {
	Data WorkspaceBudget `json:"data"`
}

func (u *UpsertWorkspaceBudgetResponse) GetData() WorkspaceBudget {
	if u == nil {
		return WorkspaceBudget{}
	}
	return u.Data
}
