// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type UpsertWorkspaceBudgetRequest struct {
	// Spending limit in USD. Must be greater than 0.
	LimitUsd float64 `json:"limit_usd"`
}

func (u *UpsertWorkspaceBudgetRequest) GetLimitUsd() float64 {
	if u == nil {
		return 0.0
	}
	return u.LimitUsd
}
