// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 2f8490aceef4

package shared

type ValidatePrivateEndpointRequest struct {
	// Workspace whose BYOK credential is used for the live validation call. The workspace must belong to your account.
	WorkspaceID string `json:"workspace_id"`
}

func (v *ValidatePrivateEndpointRequest) GetWorkspaceID() string {
	if v == nil {
		return ""
	}
	return v.WorkspaceID
}
