// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: ce26d8026226

package shared

// VaultSecretResponse - Metadata for the stored secret.
type VaultSecretResponse struct {
	// Metadata for one stored secret. The secret value is never returned. `fingerprint` is an HMAC-SHA-256 of the value keyed with that vault's own data key, so it is comparable only within one vault: equal fingerprints in one vault mean equal values, and rewriting the same value keeps its fingerprint. The same value stored in two vaults (for example a workspace secret and its intern copy) carries different fingerprints, so comparing fingerprints across vaults cannot show that a copy matches or that a rotation propagated. `hosts` and `fingerprint` are `null` only for legacy rows written before host binding was required; storing the secret again assigns hosts.
	Data VaultSecret `json:"data"`
}

func (v *VaultSecretResponse) GetData() VaultSecret {
	if v == nil {
		return VaultSecret{}
	}
	return v.Data
}
