workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    OpenRouter API:
        inputs:
            - location: .speakeasy/in.openapi.yaml
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
            - location: .speakeasy/terraform-entities-overlay.yaml
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/openrouter/sdk/open-router-api
targets:
    open-router:
        target: terraform
        source: OpenRouter API
