// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 1d8183b1a1ac

package provider

import (
	"context"
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/provider/typeconvert"
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/models/operations"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"time"
)

func (r *APIKeyResourceModel) RefreshFromOperationsCreateKeysData(ctx context.Context, resp *operations.CreateKeysData) diag.Diagnostics {
	var diags diag.Diagnostics

	r.ByokUsage = types.Float64Value(resp.ByokUsage)
	r.ByokUsageDaily = types.Float64Value(resp.ByokUsageDaily)
	r.ByokUsageMonthly = types.Float64Value(resp.ByokUsageMonthly)
	r.ByokUsageWeekly = types.Float64Value(resp.ByokUsageWeekly)
	r.CreatedAt = types.StringValue(resp.CreatedAt)
	r.CreatorUserID = types.StringPointerValue(resp.CreatorUserID)
	r.Disabled = types.BoolValue(resp.Disabled)
	r.ExpiresAt = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.ExpiresAt))
	r.ExternalUser = types.StringPointerValue(resp.ExternalUser)
	r.Hash = types.StringValue(resp.Hash)
	r.IncludeByokInLimit = types.BoolValue(resp.IncludeByokInLimit)
	r.Label = types.StringValue(resp.Label)
	r.Limit = types.Float64PointerValue(resp.Limit)
	r.LimitRemaining = types.Float64PointerValue(resp.LimitRemaining)
	if resp.LimitReset != nil {
		r.LimitReset = types.StringValue(string(*resp.LimitReset))
	} else {
		r.LimitReset = types.StringNull()
	}
	r.Name = types.StringValue(resp.Name)
	r.UpdatedAt = types.StringPointerValue(resp.UpdatedAt)
	r.Usage = types.Float64Value(resp.Usage)
	r.UsageDaily = types.Float64Value(resp.UsageDaily)
	r.UsageMonthly = types.Float64Value(resp.UsageMonthly)
	r.UsageWeekly = types.Float64Value(resp.UsageWeekly)
	r.WorkspaceID = types.StringValue(resp.WorkspaceID)

	return diags
}

func (r *APIKeyResourceModel) RefreshFromOperationsCreateKeysResponseBody(ctx context.Context, resp *operations.CreateKeysResponseBody) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		diags.Append(r.RefreshFromOperationsCreateKeysData(ctx, &resp.Data)...)

		if diags.HasError() {
			return diags
		}

		r.Key = types.StringValue(resp.Key)
	}

	return diags
}

func (r *APIKeyResourceModel) RefreshFromOperationsGetKeyData(ctx context.Context, resp *operations.GetKeyData) diag.Diagnostics {
	var diags diag.Diagnostics

	r.ByokUsage = types.Float64Value(resp.ByokUsage)
	r.ByokUsageDaily = types.Float64Value(resp.ByokUsageDaily)
	r.ByokUsageMonthly = types.Float64Value(resp.ByokUsageMonthly)
	r.ByokUsageWeekly = types.Float64Value(resp.ByokUsageWeekly)
	r.CreatedAt = types.StringValue(resp.CreatedAt)
	r.CreatorUserID = types.StringPointerValue(resp.CreatorUserID)
	r.Disabled = types.BoolValue(resp.Disabled)
	r.ExpiresAt = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.ExpiresAt))
	r.ExternalUser = types.StringPointerValue(resp.ExternalUser)
	r.Hash = types.StringValue(resp.Hash)
	r.IncludeByokInLimit = types.BoolValue(resp.IncludeByokInLimit)
	r.Label = types.StringValue(resp.Label)
	r.Limit = types.Float64PointerValue(resp.Limit)
	r.LimitRemaining = types.Float64PointerValue(resp.LimitRemaining)
	if resp.LimitReset != nil {
		r.LimitReset = types.StringValue(string(*resp.LimitReset))
	} else {
		r.LimitReset = types.StringNull()
	}
	r.Name = types.StringValue(resp.Name)
	r.UpdatedAt = types.StringPointerValue(resp.UpdatedAt)
	r.Usage = types.Float64Value(resp.Usage)
	r.UsageDaily = types.Float64Value(resp.UsageDaily)
	r.UsageMonthly = types.Float64Value(resp.UsageMonthly)
	r.UsageWeekly = types.Float64Value(resp.UsageWeekly)
	r.WorkspaceID = types.StringValue(resp.WorkspaceID)

	return diags
}

func (r *APIKeyResourceModel) RefreshFromOperationsGetKeyResponseBody(ctx context.Context, resp *operations.GetKeyResponseBody) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		diags.Append(r.RefreshFromOperationsGetKeyData(ctx, &resp.Data)...)

		if diags.HasError() {
			return diags
		}

	}

	return diags
}

func (r *APIKeyResourceModel) RefreshFromOperationsUpdateKeysData(ctx context.Context, resp *operations.UpdateKeysData) diag.Diagnostics {
	var diags diag.Diagnostics

	r.ByokUsage = types.Float64Value(resp.ByokUsage)
	r.ByokUsageDaily = types.Float64Value(resp.ByokUsageDaily)
	r.ByokUsageMonthly = types.Float64Value(resp.ByokUsageMonthly)
	r.ByokUsageWeekly = types.Float64Value(resp.ByokUsageWeekly)
	r.CreatedAt = types.StringValue(resp.CreatedAt)
	r.CreatorUserID = types.StringPointerValue(resp.CreatorUserID)
	r.Disabled = types.BoolValue(resp.Disabled)
	r.ExpiresAt = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.ExpiresAt))
	r.ExternalUser = types.StringPointerValue(resp.ExternalUser)
	r.Hash = types.StringValue(resp.Hash)
	r.IncludeByokInLimit = types.BoolValue(resp.IncludeByokInLimit)
	r.Label = types.StringValue(resp.Label)
	r.Limit = types.Float64PointerValue(resp.Limit)
	r.LimitRemaining = types.Float64PointerValue(resp.LimitRemaining)
	if resp.LimitReset != nil {
		r.LimitReset = types.StringValue(string(*resp.LimitReset))
	} else {
		r.LimitReset = types.StringNull()
	}
	r.Name = types.StringValue(resp.Name)
	r.UpdatedAt = types.StringPointerValue(resp.UpdatedAt)
	r.Usage = types.Float64Value(resp.Usage)
	r.UsageDaily = types.Float64Value(resp.UsageDaily)
	r.UsageMonthly = types.Float64Value(resp.UsageMonthly)
	r.UsageWeekly = types.Float64Value(resp.UsageWeekly)
	r.WorkspaceID = types.StringValue(resp.WorkspaceID)

	return diags
}

func (r *APIKeyResourceModel) RefreshFromOperationsUpdateKeysResponseBody(ctx context.Context, resp *operations.UpdateKeysResponseBody) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		diags.Append(r.RefreshFromOperationsUpdateKeysData(ctx, &resp.Data)...)

		if diags.HasError() {
			return diags
		}

	}

	return diags
}

func (r *APIKeyResourceModel) ToOperationsCreateKeysRequest(ctx context.Context) (*operations.CreateKeysRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	creatorUserID := new(string)
	if !r.CreatorUserID.IsUnknown() && !r.CreatorUserID.IsNull() {
		*creatorUserID = r.CreatorUserID.ValueString()
	} else {
		creatorUserID = nil
	}
	expiresAt := new(time.Time)
	if !r.ExpiresAt.IsUnknown() && !r.ExpiresAt.IsNull() {
		*expiresAt, _ = time.Parse(time.RFC3339Nano, r.ExpiresAt.ValueString())
	} else {
		expiresAt = nil
	}
	var external *operations.External
	if r.External != nil {
		apiKey := new(string)
		if !r.External.APIKey.IsUnknown() && !r.External.APIKey.IsNull() {
			*apiKey = r.External.APIKey.ValueString()
		} else {
			apiKey = nil
		}
		var user string
		user = r.External.User.ValueString()

		external = &operations.External{
			APIKey: apiKey,
			User:   user,
		}
	}
	includeByokInLimit := new(bool)
	if !r.IncludeByokInLimit.IsUnknown() && !r.IncludeByokInLimit.IsNull() {
		*includeByokInLimit = r.IncludeByokInLimit.ValueBool()
	} else {
		includeByokInLimit = nil
	}
	limit := new(float64)
	if !r.Limit.IsUnknown() && !r.Limit.IsNull() {
		*limit = r.Limit.ValueFloat64()
	} else {
		limit = nil
	}
	limitReset := new(operations.CreateKeysLimitReset)
	if !r.LimitReset.IsUnknown() && !r.LimitReset.IsNull() {
		*limitReset = operations.CreateKeysLimitReset(r.LimitReset.ValueString())
	} else {
		limitReset = nil
	}
	var name string
	name = r.Name.ValueString()

	workspaceID := new(string)
	if !r.WorkspaceID.IsUnknown() && !r.WorkspaceID.IsNull() {
		*workspaceID = r.WorkspaceID.ValueString()
	} else {
		workspaceID = nil
	}
	out := operations.CreateKeysRequest{
		CreatorUserID:      creatorUserID,
		ExpiresAt:          expiresAt,
		External:           external,
		IncludeByokInLimit: includeByokInLimit,
		Limit:              limit,
		LimitReset:         limitReset,
		Name:               name,
		WorkspaceID:        workspaceID,
	}

	return &out, diags
}

func (r *APIKeyResourceModel) ToOperationsDeleteKeysRequest(ctx context.Context) (*operations.DeleteKeysRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var hash string
	hash = r.Hash.ValueString()

	out := operations.DeleteKeysRequest{
		Hash: hash,
	}

	return &out, diags
}

func (r *APIKeyResourceModel) ToOperationsGetKeyRequest(ctx context.Context) (*operations.GetKeyRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var hash string
	hash = r.Hash.ValueString()

	out := operations.GetKeyRequest{
		Hash: hash,
	}

	return &out, diags
}

func (r *APIKeyResourceModel) ToOperationsUpdateKeysRequest(ctx context.Context) (*operations.UpdateKeysRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var hash string
	hash = r.Hash.ValueString()

	body, bodyDiags := r.ToOperationsUpdateKeysRequestBody(ctx)
	diags.Append(bodyDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := operations.UpdateKeysRequest{
		Hash: hash,
		Body: *body,
	}

	return &out, diags
}

func (r *APIKeyResourceModel) ToOperationsUpdateKeysRequestBody(ctx context.Context) (*operations.UpdateKeysRequestBody, diag.Diagnostics) {
	var diags diag.Diagnostics

	disabled := new(bool)
	if !r.Disabled.IsUnknown() && !r.Disabled.IsNull() {
		*disabled = r.Disabled.ValueBool()
	} else {
		disabled = nil
	}
	includeByokInLimit := new(bool)
	if !r.IncludeByokInLimit.IsUnknown() && !r.IncludeByokInLimit.IsNull() {
		*includeByokInLimit = r.IncludeByokInLimit.ValueBool()
	} else {
		includeByokInLimit = nil
	}
	limit := new(float64)
	if !r.Limit.IsUnknown() && !r.Limit.IsNull() {
		*limit = r.Limit.ValueFloat64()
	} else {
		limit = nil
	}
	limitReset := new(operations.UpdateKeysLimitReset)
	if !r.LimitReset.IsUnknown() && !r.LimitReset.IsNull() {
		*limitReset = operations.UpdateKeysLimitReset(r.LimitReset.ValueString())
	} else {
		limitReset = nil
	}
	name := new(string)
	if !r.Name.IsUnknown() && !r.Name.IsNull() {
		*name = r.Name.ValueString()
	} else {
		name = nil
	}
	out := operations.UpdateKeysRequestBody{
		Disabled:           disabled,
		IncludeByokInLimit: includeByokInLimit,
		Limit:              limit,
		LimitReset:         limitReset,
		Name:               name,
	}

	return &out, diags
}
