// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 7e88f06cb718

package provider

import (
	"context"
	tfTypes "github.com/OpenRouterTeam/terraform-provider-openrouter/internal/provider/types"
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/models/operations"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *OrganizationMembersDataSourceModel) RefreshFromOperationsListOrganizationMembersResponseBody(ctx context.Context, resp *operations.ListOrganizationMembersResponseBody) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		if r.Data == nil {
			r.Data = []tfTypes.ListOrganizationMembersData{}
		}

		for _, dataItem := range resp.Data {
			var data tfTypes.ListOrganizationMembersData

			data.Email = types.StringValue(dataItem.Email)
			data.FirstName = types.StringPointerValue(dataItem.FirstName)
			data.ID = types.StringValue(dataItem.ID)
			data.LastName = types.StringPointerValue(dataItem.LastName)
			data.Role = types.StringValue(string(dataItem.Role))

			r.Data = append(r.Data, data)
		}
		r.TotalCount = types.Int64Value(resp.TotalCount)
	}

	return diags
}

func (r *OrganizationMembersDataSourceModel) ToOperationsListOrganizationMembersRequest(ctx context.Context) (*operations.ListOrganizationMembersRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	out := operations.ListOrganizationMembersRequest{}

	return &out, diags
}
