// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: c95e013b85a8

package provider

import (
	"context"
	tfTypes "github.com/OpenRouterTeam/terraform-provider-openrouter/internal/provider/types"
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/models/operations"
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *PresetsDataSourceModel) RefreshFromSharedListPresetsResponse(ctx context.Context, resp *shared.ListPresetsResponse) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		if r.Data == nil {
			r.Data = []tfTypes.Preset{}
		}

		for _, dataItem := range resp.Data {
			var data tfTypes.Preset

			data.CreatedAt = types.StringValue(dataItem.CreatedAt)
			data.CreatorUserID = types.StringPointerValue(dataItem.CreatorUserID)
			data.Description = types.StringPointerValue(dataItem.Description)
			data.DesignatedVersionID = types.StringPointerValue(dataItem.DesignatedVersionID)
			data.ID = types.StringValue(dataItem.ID)
			data.Name = types.StringValue(dataItem.Name)
			data.Slug = types.StringValue(dataItem.Slug)
			data.Status = types.StringValue(string(dataItem.Status))
			data.StatusUpdatedAt = types.StringPointerValue(dataItem.StatusUpdatedAt)
			data.UpdatedAt = types.StringValue(dataItem.UpdatedAt)
			data.WorkspaceID = types.StringPointerValue(dataItem.WorkspaceID)

			r.Data = append(r.Data, data)
		}
		r.TotalCount = types.Int64Value(resp.TotalCount)
	}

	return diags
}

func (r *PresetsDataSourceModel) ToOperationsListPresetsRequest(ctx context.Context) (*operations.ListPresetsRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	out := operations.ListPresetsRequest{}

	return &out, diags
}
