// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 9d3e119d8e7e

package provider

import (
	"context"
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/models/operations"
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *WorkspaceMemberDataSourceModel) RefreshFromSharedListWorkspaceMembersResponse(ctx context.Context, resp *shared.ListWorkspaceMembersResponse) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		if len(resp.Data) == 0 {
			diags.AddError("Unexpected response from API", "Missing response body array data.")
			return diags
		}

		diags.Append(r.RefreshFromSharedWorkspaceMember(ctx, &resp.Data[0])...)

		if diags.HasError() {
			return diags
		}

		r.TotalCount = types.Int64Value(resp.TotalCount)
	}

	return diags
}

func (r *WorkspaceMemberDataSourceModel) RefreshFromSharedWorkspaceMember(ctx context.Context, resp *shared.WorkspaceMember) diag.Diagnostics {
	var diags diag.Diagnostics

	r.CreatedAt = types.StringValue(resp.CreatedAt)
	r.ID = types.StringValue(resp.ID)
	r.Role = types.StringValue(string(resp.Role))
	r.UserID = types.StringValue(resp.UserID)
	r.WorkspaceID = types.StringValue(resp.WorkspaceID)

	return diags
}

func (r *WorkspaceMemberDataSourceModel) ToOperationsListWorkspaceMembersRequest(ctx context.Context) (*operations.ListWorkspaceMembersRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var id string
	id = r.ID.ValueString()

	out := operations.ListWorkspaceMembersRequest{
		ID: id,
	}

	return &out, diags
}
