// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 7e375470340b

package provider

import (
	"context"
	"fmt"
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ datasource.DataSource = &WorkspaceBudgetDataSource{}
var _ datasource.DataSourceWithConfigure = &WorkspaceBudgetDataSource{}

func NewWorkspaceBudgetDataSource() datasource.DataSource {
	return &WorkspaceBudgetDataSource{}
}

// WorkspaceBudgetDataSource is the data source implementation.
type WorkspaceBudgetDataSource struct {
	// Provider configured SDK client.
	client *sdk.OpenRouter
}

// WorkspaceBudgetDataSourceModel describes the data model.
type WorkspaceBudgetDataSourceModel struct {
	CreatedAt            types.String  `tfsdk:"created_at"`
	ID                   types.String  `tfsdk:"id"`
	IncludeByokInBudgets types.Bool    `tfsdk:"include_byok_in_budgets"`
	Interval             types.String  `tfsdk:"interval"`
	LimitUsd             types.Float64 `tfsdk:"limit_usd"`
	ResetInterval        types.String  `tfsdk:"reset_interval"`
	UpdatedAt            types.String  `tfsdk:"updated_at"`
	WorkspaceID          types.String  `tfsdk:"workspace_id"`
}

// Metadata returns the data source type name.
func (r *WorkspaceBudgetDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_workspace_budget"
}

// Schema defines the schema for the data source.
func (r *WorkspaceBudgetDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "WorkspaceBudget DataSource",

		Attributes: map[string]schema.Attribute{
			"created_at": schema.StringAttribute{
				Computed:    true,
				Description: `ISO 8601 timestamp of when the budget was created`,
			},
			"id": schema.StringAttribute{
				Required:    true,
				Description: `Unique identifier for the budget`,
				Validators: []validator.String{
					stringvalidator.UTF8LengthAtLeast(1),
				},
			},
			"include_byok_in_budgets": schema.BoolAttribute{
				Computed:    true,
				Description: `Whether BYOK (bring-your-own-key) spend is included when enforcing the workspace's budgets. This is a workspace-wide setting that applies to all budget intervals (daily, weekly, monthly, and lifetime).`,
			},
			"interval": schema.StringAttribute{
				Required:    true,
				Description: `Budget reset interval. Use "lifetime" for a one-time budget that never resets. must be one of ["daily", "weekly", "monthly", "lifetime"]`,
				Validators: []validator.String{
					stringvalidator.OneOf(
						"daily",
						"weekly",
						"monthly",
						"lifetime",
					),
				},
			},
			"limit_usd": schema.Float64Attribute{
				Computed:    true,
				Description: `Spending limit in USD for this interval`,
			},
			"reset_interval": schema.StringAttribute{
				Computed:    true,
				Description: `Interval at which spend resets. Null means a lifetime (one-time) budget.`,
			},
			"updated_at": schema.StringAttribute{
				Computed:    true,
				Description: `ISO 8601 timestamp of when the budget was last updated`,
			},
			"workspace_id": schema.StringAttribute{
				Computed:    true,
				Description: `ID of the workspace the budget belongs to`,
			},
		},
	}
}

func (r *WorkspaceBudgetDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*sdk.OpenRouter)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected DataSource Configure Type",
			fmt.Sprintf("Expected *sdk.OpenRouter, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = client
}

func (r *WorkspaceBudgetDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data *WorkspaceBudgetDataSourceModel
	var item types.Object

	resp.Diagnostics.Append(req.Config.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	request, requestDiags := data.ToOperationsGetWorkspaceBudgetRequest(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.Workspaces.GetBudget(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.GetWorkspaceBudgetResponse != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	resp.Diagnostics.Append(data.RefreshFromSharedGetWorkspaceBudgetResponse(ctx, res.GetWorkspaceBudgetResponse)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
