// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/models/operations"
	"github.com/OpenRouterTeam/terraform-provider-openrouter/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *WorkspaceResourceModel) RefreshFromSharedCreateWorkspaceResponse(ctx context.Context, resp *shared.CreateWorkspaceResponse) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		diags.Append(r.RefreshFromSharedCreateWorkspaceResponseData(ctx, &resp.Data)...)

		if diags.HasError() {
			return diags
		}

	}

	return diags
}

func (r *WorkspaceResourceModel) RefreshFromSharedCreateWorkspaceResponseData(ctx context.Context, resp *shared.CreateWorkspaceResponseData) diag.Diagnostics {
	var diags diag.Diagnostics

	r.CreatedAt = types.StringValue(resp.CreatedAt)
	r.CreatedBy = types.StringPointerValue(resp.CreatedBy)
	r.DefaultGuardrailID = types.StringValue(resp.DefaultGuardrailID)
	r.DefaultImageModel = types.StringPointerValue(resp.DefaultImageModel)
	r.DefaultProviderSort = types.StringPointerValue(resp.DefaultProviderSort)
	r.DefaultTextModel = types.StringPointerValue(resp.DefaultTextModel)
	r.Description = types.StringPointerValue(resp.Description)
	r.ID = types.StringValue(resp.ID)
	r.IncludeByokInBudgets = types.BoolPointerValue(resp.IncludeByokInBudgets)
	if resp.IoLoggingAPIKeyIds != nil {
		r.IoLoggingAPIKeyIds = make([]types.Int64, 0, len(resp.IoLoggingAPIKeyIds))
		for _, v := range resp.IoLoggingAPIKeyIds {
			r.IoLoggingAPIKeyIds = append(r.IoLoggingAPIKeyIds, types.Int64Value(v))
		}
	} else {
		r.IoLoggingAPIKeyIds = nil
	}
	r.IoLoggingSamplingRate = types.Float64Value(resp.IoLoggingSamplingRate)
	r.IsDataDiscountLoggingEnabled = types.BoolValue(resp.IsDataDiscountLoggingEnabled)
	r.IsObservabilityBroadcastEnabled = types.BoolValue(resp.IsObservabilityBroadcastEnabled)
	r.IsObservabilityIoLoggingEnabled = types.BoolValue(resp.IsObservabilityIoLoggingEnabled)
	r.Name = types.StringValue(resp.Name)
	r.Slug = types.StringValue(resp.Slug)
	r.UpdatedAt = types.StringPointerValue(resp.UpdatedAt)

	return diags
}

func (r *WorkspaceResourceModel) RefreshFromSharedGetWorkspaceResponse(ctx context.Context, resp *shared.GetWorkspaceResponse) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		diags.Append(r.RefreshFromSharedGetWorkspaceResponseData(ctx, &resp.Data)...)

		if diags.HasError() {
			return diags
		}

	}

	return diags
}

func (r *WorkspaceResourceModel) RefreshFromSharedGetWorkspaceResponseData(ctx context.Context, resp *shared.GetWorkspaceResponseData) diag.Diagnostics {
	var diags diag.Diagnostics

	r.CreatedAt = types.StringValue(resp.CreatedAt)
	r.CreatedBy = types.StringPointerValue(resp.CreatedBy)
	r.DefaultGuardrailID = types.StringValue(resp.DefaultGuardrailID)
	r.DefaultImageModel = types.StringPointerValue(resp.DefaultImageModel)
	r.DefaultProviderSort = types.StringPointerValue(resp.DefaultProviderSort)
	r.DefaultTextModel = types.StringPointerValue(resp.DefaultTextModel)
	r.Description = types.StringPointerValue(resp.Description)
	r.ID = types.StringValue(resp.ID)
	r.IncludeByokInBudgets = types.BoolPointerValue(resp.IncludeByokInBudgets)
	if resp.IoLoggingAPIKeyIds != nil {
		r.IoLoggingAPIKeyIds = make([]types.Int64, 0, len(resp.IoLoggingAPIKeyIds))
		for _, v := range resp.IoLoggingAPIKeyIds {
			r.IoLoggingAPIKeyIds = append(r.IoLoggingAPIKeyIds, types.Int64Value(v))
		}
	} else {
		r.IoLoggingAPIKeyIds = nil
	}
	r.IoLoggingSamplingRate = types.Float64Value(resp.IoLoggingSamplingRate)
	r.IsDataDiscountLoggingEnabled = types.BoolValue(resp.IsDataDiscountLoggingEnabled)
	r.IsObservabilityBroadcastEnabled = types.BoolValue(resp.IsObservabilityBroadcastEnabled)
	r.IsObservabilityIoLoggingEnabled = types.BoolValue(resp.IsObservabilityIoLoggingEnabled)
	r.Name = types.StringValue(resp.Name)
	r.Slug = types.StringValue(resp.Slug)
	r.UpdatedAt = types.StringPointerValue(resp.UpdatedAt)

	return diags
}

func (r *WorkspaceResourceModel) RefreshFromSharedUpdateWorkspaceResponse(ctx context.Context, resp *shared.UpdateWorkspaceResponse) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		diags.Append(r.RefreshFromSharedUpdateWorkspaceResponseData(ctx, &resp.Data)...)

		if diags.HasError() {
			return diags
		}

	}

	return diags
}

func (r *WorkspaceResourceModel) RefreshFromSharedUpdateWorkspaceResponseData(ctx context.Context, resp *shared.UpdateWorkspaceResponseData) diag.Diagnostics {
	var diags diag.Diagnostics

	r.CreatedAt = types.StringValue(resp.CreatedAt)
	r.CreatedBy = types.StringPointerValue(resp.CreatedBy)
	r.DefaultGuardrailID = types.StringValue(resp.DefaultGuardrailID)
	r.DefaultImageModel = types.StringPointerValue(resp.DefaultImageModel)
	r.DefaultProviderSort = types.StringPointerValue(resp.DefaultProviderSort)
	r.DefaultTextModel = types.StringPointerValue(resp.DefaultTextModel)
	r.Description = types.StringPointerValue(resp.Description)
	r.ID = types.StringValue(resp.ID)
	r.IncludeByokInBudgets = types.BoolPointerValue(resp.IncludeByokInBudgets)
	if resp.IoLoggingAPIKeyIds != nil {
		r.IoLoggingAPIKeyIds = make([]types.Int64, 0, len(resp.IoLoggingAPIKeyIds))
		for _, v := range resp.IoLoggingAPIKeyIds {
			r.IoLoggingAPIKeyIds = append(r.IoLoggingAPIKeyIds, types.Int64Value(v))
		}
	} else {
		r.IoLoggingAPIKeyIds = nil
	}
	r.IoLoggingSamplingRate = types.Float64Value(resp.IoLoggingSamplingRate)
	r.IsDataDiscountLoggingEnabled = types.BoolValue(resp.IsDataDiscountLoggingEnabled)
	r.IsObservabilityBroadcastEnabled = types.BoolValue(resp.IsObservabilityBroadcastEnabled)
	r.IsObservabilityIoLoggingEnabled = types.BoolValue(resp.IsObservabilityIoLoggingEnabled)
	r.Name = types.StringValue(resp.Name)
	r.Slug = types.StringValue(resp.Slug)
	r.UpdatedAt = types.StringPointerValue(resp.UpdatedAt)

	return diags
}

func (r *WorkspaceResourceModel) ToOperationsDeleteWorkspaceRequest(ctx context.Context) (*operations.DeleteWorkspaceRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var id string
	id = r.ID.ValueString()

	confirmDefaultSettingsDeletion := new(operations.ConfirmDefaultSettingsDeletion)
	if !r.ConfirmDefaultSettingsDeletion.IsUnknown() && !r.ConfirmDefaultSettingsDeletion.IsNull() {
		*confirmDefaultSettingsDeletion = operations.ConfirmDefaultSettingsDeletion(r.ConfirmDefaultSettingsDeletion.ValueString())
	} else {
		confirmDefaultSettingsDeletion = nil
	}
	out := operations.DeleteWorkspaceRequest{
		ID:                             id,
		ConfirmDefaultSettingsDeletion: confirmDefaultSettingsDeletion,
	}

	return &out, diags
}

func (r *WorkspaceResourceModel) ToOperationsGetWorkspaceRequest(ctx context.Context) (*operations.GetWorkspaceRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var id string
	id = r.ID.ValueString()

	out := operations.GetWorkspaceRequest{
		ID: id,
	}

	return &out, diags
}

func (r *WorkspaceResourceModel) ToOperationsUpdateWorkspaceRequest(ctx context.Context) (*operations.UpdateWorkspaceRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var id string
	id = r.ID.ValueString()

	body, bodyDiags := r.ToSharedUpdateWorkspaceRequest(ctx)
	diags.Append(bodyDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := operations.UpdateWorkspaceRequest{
		ID:   id,
		Body: *body,
	}

	return &out, diags
}

func (r *WorkspaceResourceModel) ToSharedCreateWorkspaceRequest(ctx context.Context) (*shared.CreateWorkspaceRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	defaultImageModel := new(string)
	if !r.DefaultImageModel.IsUnknown() && !r.DefaultImageModel.IsNull() {
		*defaultImageModel = r.DefaultImageModel.ValueString()
	} else {
		defaultImageModel = nil
	}
	defaultProviderSort := new(string)
	if !r.DefaultProviderSort.IsUnknown() && !r.DefaultProviderSort.IsNull() {
		*defaultProviderSort = r.DefaultProviderSort.ValueString()
	} else {
		defaultProviderSort = nil
	}
	defaultTextModel := new(string)
	if !r.DefaultTextModel.IsUnknown() && !r.DefaultTextModel.IsNull() {
		*defaultTextModel = r.DefaultTextModel.ValueString()
	} else {
		defaultTextModel = nil
	}
	description := new(string)
	if !r.Description.IsUnknown() && !r.Description.IsNull() {
		*description = r.Description.ValueString()
	} else {
		description = nil
	}
	var ioLoggingAPIKeyIds []int64
	if r.IoLoggingAPIKeyIds != nil {
		ioLoggingAPIKeyIds = make([]int64, 0, len(r.IoLoggingAPIKeyIds))
		for ioLoggingAPIKeyIdsIndex := range r.IoLoggingAPIKeyIds {
			ioLoggingAPIKeyIds = append(ioLoggingAPIKeyIds, r.IoLoggingAPIKeyIds[ioLoggingAPIKeyIdsIndex].ValueInt64())
		}
	}
	ioLoggingSamplingRate := new(float64)
	if !r.IoLoggingSamplingRate.IsUnknown() && !r.IoLoggingSamplingRate.IsNull() {
		*ioLoggingSamplingRate = r.IoLoggingSamplingRate.ValueFloat64()
	} else {
		ioLoggingSamplingRate = nil
	}
	isDataDiscountLoggingEnabled := new(bool)
	if !r.IsDataDiscountLoggingEnabled.IsUnknown() && !r.IsDataDiscountLoggingEnabled.IsNull() {
		*isDataDiscountLoggingEnabled = r.IsDataDiscountLoggingEnabled.ValueBool()
	} else {
		isDataDiscountLoggingEnabled = nil
	}
	isObservabilityBroadcastEnabled := new(bool)
	if !r.IsObservabilityBroadcastEnabled.IsUnknown() && !r.IsObservabilityBroadcastEnabled.IsNull() {
		*isObservabilityBroadcastEnabled = r.IsObservabilityBroadcastEnabled.ValueBool()
	} else {
		isObservabilityBroadcastEnabled = nil
	}
	isObservabilityIoLoggingEnabled := new(bool)
	if !r.IsObservabilityIoLoggingEnabled.IsUnknown() && !r.IsObservabilityIoLoggingEnabled.IsNull() {
		*isObservabilityIoLoggingEnabled = r.IsObservabilityIoLoggingEnabled.ValueBool()
	} else {
		isObservabilityIoLoggingEnabled = nil
	}
	var name string
	name = r.Name.ValueString()

	var slug string
	slug = r.Slug.ValueString()

	out := shared.CreateWorkspaceRequest{
		DefaultImageModel:               defaultImageModel,
		DefaultProviderSort:             defaultProviderSort,
		DefaultTextModel:                defaultTextModel,
		Description:                     description,
		IoLoggingAPIKeyIds:              ioLoggingAPIKeyIds,
		IoLoggingSamplingRate:           ioLoggingSamplingRate,
		IsDataDiscountLoggingEnabled:    isDataDiscountLoggingEnabled,
		IsObservabilityBroadcastEnabled: isObservabilityBroadcastEnabled,
		IsObservabilityIoLoggingEnabled: isObservabilityIoLoggingEnabled,
		Name:                            name,
		Slug:                            slug,
	}

	return &out, diags
}

func (r *WorkspaceResourceModel) ToSharedUpdateWorkspaceRequest(ctx context.Context) (*shared.UpdateWorkspaceRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	defaultImageModel := new(string)
	if !r.DefaultImageModel.IsUnknown() && !r.DefaultImageModel.IsNull() {
		*defaultImageModel = r.DefaultImageModel.ValueString()
	} else {
		defaultImageModel = nil
	}
	defaultProviderSort := new(string)
	if !r.DefaultProviderSort.IsUnknown() && !r.DefaultProviderSort.IsNull() {
		*defaultProviderSort = r.DefaultProviderSort.ValueString()
	} else {
		defaultProviderSort = nil
	}
	defaultTextModel := new(string)
	if !r.DefaultTextModel.IsUnknown() && !r.DefaultTextModel.IsNull() {
		*defaultTextModel = r.DefaultTextModel.ValueString()
	} else {
		defaultTextModel = nil
	}
	description := new(string)
	if !r.Description.IsUnknown() && !r.Description.IsNull() {
		*description = r.Description.ValueString()
	} else {
		description = nil
	}
	var ioLoggingAPIKeyIds []int64
	if r.IoLoggingAPIKeyIds != nil {
		ioLoggingAPIKeyIds = make([]int64, 0, len(r.IoLoggingAPIKeyIds))
		for ioLoggingAPIKeyIdsIndex := range r.IoLoggingAPIKeyIds {
			ioLoggingAPIKeyIds = append(ioLoggingAPIKeyIds, r.IoLoggingAPIKeyIds[ioLoggingAPIKeyIdsIndex].ValueInt64())
		}
	}
	ioLoggingSamplingRate := new(float64)
	if !r.IoLoggingSamplingRate.IsUnknown() && !r.IoLoggingSamplingRate.IsNull() {
		*ioLoggingSamplingRate = r.IoLoggingSamplingRate.ValueFloat64()
	} else {
		ioLoggingSamplingRate = nil
	}
	isDataDiscountLoggingEnabled := new(bool)
	if !r.IsDataDiscountLoggingEnabled.IsUnknown() && !r.IsDataDiscountLoggingEnabled.IsNull() {
		*isDataDiscountLoggingEnabled = r.IsDataDiscountLoggingEnabled.ValueBool()
	} else {
		isDataDiscountLoggingEnabled = nil
	}
	isObservabilityBroadcastEnabled := new(bool)
	if !r.IsObservabilityBroadcastEnabled.IsUnknown() && !r.IsObservabilityBroadcastEnabled.IsNull() {
		*isObservabilityBroadcastEnabled = r.IsObservabilityBroadcastEnabled.ValueBool()
	} else {
		isObservabilityBroadcastEnabled = nil
	}
	isObservabilityIoLoggingEnabled := new(bool)
	if !r.IsObservabilityIoLoggingEnabled.IsUnknown() && !r.IsObservabilityIoLoggingEnabled.IsNull() {
		*isObservabilityIoLoggingEnabled = r.IsObservabilityIoLoggingEnabled.ValueBool()
	} else {
		isObservabilityIoLoggingEnabled = nil
	}
	name := new(string)
	if !r.Name.IsUnknown() && !r.Name.IsNull() {
		*name = r.Name.ValueString()
	} else {
		name = nil
	}
	slug := new(string)
	if !r.Slug.IsUnknown() && !r.Slug.IsNull() {
		*slug = r.Slug.ValueString()
	} else {
		slug = nil
	}
	out := shared.UpdateWorkspaceRequest{
		DefaultImageModel:               defaultImageModel,
		DefaultProviderSort:             defaultProviderSort,
		DefaultTextModel:                defaultTextModel,
		Description:                     description,
		IoLoggingAPIKeyIds:              ioLoggingAPIKeyIds,
		IoLoggingSamplingRate:           ioLoggingSamplingRate,
		IsDataDiscountLoggingEnabled:    isDataDiscountLoggingEnabled,
		IsObservabilityBroadcastEnabled: isObservabilityBroadcastEnabled,
		IsObservabilityIoLoggingEnabled: isObservabilityIoLoggingEnabled,
		Name:                            name,
		Slug:                            slug,
	}

	return &out, diags
}
