// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type ContentFilterEntry struct {
	Action  types.String `tfsdk:"action"`
	Label   types.String `tfsdk:"label"`
	Pattern types.String `tfsdk:"pattern"`
}
