// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: f1be8d5cde0d

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type GetObservabilityDestinationResponseConfigPosthog struct {
	APIKey   types.String            `tfsdk:"api_key"`
	Endpoint types.String            `tfsdk:"endpoint"`
	Headers  map[string]types.String `tfsdk:"headers"`
}
