// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 4bfa1adcf48a

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type GetObservabilityDestinationResponseObservabilitySentryDestination struct {
	APIKeyHashes                      []types.String                                   `tfsdk:"api_key_hashes"`
	BroadcastGenerationCost           types.Bool                                       `tfsdk:"broadcast_generation_cost"`
	BroadcastGenerationIdentity       types.Bool                                       `tfsdk:"broadcast_generation_identity"`
	BroadcastGenerationRequestContext types.Bool                                       `tfsdk:"broadcast_generation_request_context"`
	Config                            *GetObservabilityDestinationResponseConfigSentry `tfsdk:"config"`
	CreatedAt                         types.String                                     `tfsdk:"created_at"`
	Enabled                           types.Bool                                       `tfsdk:"enabled"`
	FilterRules                       *ObservabilityFilterRulesConfig                  `tfsdk:"filter_rules"`
	ID                                types.String                                     `tfsdk:"id"`
	Name                              types.String                                     `tfsdk:"name"`
	PrivacyMode                       types.Bool                                       `tfsdk:"privacy_mode"`
	SamplingRate                      types.Float64                                    `tfsdk:"sampling_rate"`
	UpdatedAt                         types.String                                     `tfsdk:"updated_at"`
	WorkspaceID                       types.String                                     `tfsdk:"workspace_id"`
}
