// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type GetObservabilityDestinationResponseConfigLangsmith struct {
	APIKey      types.String            `tfsdk:"api_key"`
	Endpoint    types.String            `tfsdk:"endpoint"`
	Headers     map[string]types.String `tfsdk:"headers"`
	Project     types.String            `tfsdk:"project"`
	WorkspaceID types.String            `tfsdk:"workspace_id"`
}
