// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type GetObservabilityDestinationResponseConfigGrafana struct {
	APIKey     types.String            `tfsdk:"api_key"`
	BaseURL    types.String            `tfsdk:"base_url"`
	Headers    map[string]types.String `tfsdk:"headers"`
	InstanceID types.String            `tfsdk:"instance_id"`
}
