// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: d840c190dd64

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type GetObservabilityDestinationResponseConfigSentry struct {
	Dsn          types.String            `tfsdk:"dsn"`
	Headers      map[string]types.String `tfsdk:"headers"`
	OtlpEndpoint types.String            `tfsdk:"otlp_endpoint"`
}
