// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 5f8e09e66842

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type ModelReasoning struct {
	DefaultEffort     types.String   `tfsdk:"default_effort"`
	DefaultEnabled    types.Bool     `tfsdk:"default_enabled"`
	Mandatory         types.Bool     `tfsdk:"mandatory"`
	SupportedEfforts  []types.String `tfsdk:"supported_efforts"`
	SupportsMaxTokens types.Bool     `tfsdk:"supports_max_tokens"`
}
