// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: b050d2b1e7c6

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type ObservabilityDestinationConfigSnowflake struct {
	Account   types.String            `tfsdk:"account"`
	Database  types.String            `tfsdk:"database"`
	Headers   map[string]types.String `tfsdk:"headers"`
	Schema    types.String            `tfsdk:"schema"`
	Table     types.String            `tfsdk:"table"`
	Token     types.String            `tfsdk:"token"`
	Warehouse types.String            `tfsdk:"warehouse"`
}
