// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type ObservabilityFilterRuleGroupNullableRule struct {
	Field    types.String                               `tfsdk:"field"`
	Operator types.String                               `tfsdk:"operator"`
	Value    *ObservabilityFilterRuleGroupNullableValue `tfsdk:"value"`
}
