// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: df27253253a7

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type ObservabilityFilterRuleGroupNullableValue struct {
	Str    types.String  `queryParam:"inline" tfsdk:"str"`
	Number types.Float64 `queryParam:"inline" tfsdk:"number"`
}
