// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: db445acf423b

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type ObservabilityDestinationConfigClickhouse struct {
	Database                      types.String `tfsdk:"database"`
	Host                          types.String `tfsdk:"host"`
	ShouldIncludeCacheWriteTokens types.Bool   `tfsdk:"should_include_cache_write_tokens"`
	Table                         types.String `tfsdk:"table"`
	Username                      types.String `tfsdk:"username"`
}
