// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 80cc3c76b4e7

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type PrivateProvider struct {
	BaseURL          types.String                `tfsdk:"base_url"`
	CreatedAt        types.String                `tfsdk:"created_at"`
	DataPolicy       *PrivateProviderDataPolicy1 `tfsdk:"data_policy"`
	Datacenters      []types.String              `tfsdk:"datacenters"`
	DisplayName      types.String                `tfsdk:"display_name"`
	Headquarters     types.String                `tfsdk:"headquarters"`
	Name             types.String                `tfsdk:"name"`
	PrivacyPolicyURL types.String                `tfsdk:"privacy_policy_url"`
	Slug             types.String                `tfsdk:"slug"`
}
