// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 9b1de6c6d32b

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type TopProviderInfo struct {
	ContextLength       types.Int64 `tfsdk:"context_length"`
	IsModerated         types.Bool  `tfsdk:"is_moderated"`
	MaxCompletionTokens types.Int64 `tfsdk:"max_completion_tokens"`
}
